#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Move Behavior Data v0.18
# 分類：技能資料／效果覆蓋
#
# 【用途／機制】
# 定義 MoveDB、招式 Runtime 行為與 7005/7005 learnset reference 覆蓋。
#
# 【怎麼調整】
# 新增招式效果優先放在資料表與共用 foundation；不要為每招複製一份傷害流程。
#
# 【本腳本主要設定常數／資料表】
# - MOVE_BEHAVIOR_MANIFEST_V018 / MOVE_BEHAVIOR_V018
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#==============================================================================
# ■ PMD AutoChess Move Behavior Data v0.18 - GENERATED
#    Tier-1 canonical runtime mapping; legacy SKILL_DATA remains separate.
#==============================================================================
module PMD_AC
  MOVE_BEHAVIOR_MANIFEST_V018 = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:mapped_move_count=>39,:learnset_reference_total=>7005,:learnset_reference_covered=>816,:learnset_unique_covered=>39,:coverage_percent=>11.65,:runtime_checksum32=>1786978497,:runtime_file=>"Data/PMD_AutoChess_MoveBehaviors_v018_000.rvdata",:energy_runtime_mode=>:full_bar_v015,:notes=>["v0.15 combat Core remains intact; canonical moves enter through a thin skill_data adapter","official runtime skill namespace uses mv_* and never overwrites legacy custom SKILL_DATA","Tier-1 mapping avoids unsupported weather, accuracy stages, stat stages, recoil, multi-hit and switching semantics","Move-specific range is used for canonical runtime skills","v0.17 MoveDB and v0.16.1 SpeciesDB remain unchanged"]}
  MOVE_BEHAVIOR_V018 = {}
  MOVE_BEHAVIOR_V018[:pound] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:pound,:runtime_skill_key=>:mv_pound,:name=>"拍擊",:name_en=>"Pound",:type=>:normal,:category=>:physical,:canonical_power=>40,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>35,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>40}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:scratch] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:scratch,:runtime_skill_key=>:mv_scratch,:name=>"抓",:name_en=>"Scratch",:type=>:normal,:category=>:physical,:canonical_power=>40,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>35,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>40}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:tackle] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:tackle,:runtime_skill_key=>:mv_tackle,:name=>"撞擊",:name_en=>"Tackle",:type=>:normal,:category=>:physical,:canonical_power=>50,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>50}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:slam] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:slam,:runtime_skill_key=>:mv_slam,:name=>"摔打",:name_en=>"Slam",:type=>:normal,:category=>:physical,:canonical_power=>80,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:non_sky_battle,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>80}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:water_gun] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:water_gun,:runtime_skill_key=>:mv_water_gun,:name=>"水槍",:name_en=>"Water Gun",:type=>:water,:category=>:special,:canonical_power=>40,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>35,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:water,:effects=>[{:type=>:damage,:power=>40}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:hydro_pump] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:hydro_pump,:runtime_skill_key=>:mv_hydro_pump,:name=>"水炮",:name_en=>"Hydro Pump",:type=>:water,:category=>:special,:canonical_power=>120,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>65,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:water,:effects=>[{:type=>:damage,:power=>120}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:vine_whip] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:vine_whip,:runtime_skill_key=>:mv_vine_whip,:name=>"藤鞭",:name_en=>"Vine Whip",:type=>:grass,:category=>:physical,:canonical_power=>35,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>35,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>35}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:peck] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:peck,:runtime_skill_key=>:mv_peck,:name=>"啄",:name_en=>"Peck",:type=>:flying,:category=>:physical,:canonical_power=>35,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>35,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:distance,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>35}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:drill_peck] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:drill_peck,:runtime_skill_key=>:mv_drill_peck,:name=>"啄鑽",:name_en=>"Drill Peck",:type=>:flying,:category=>:physical,:canonical_power=>80,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:distance,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>80}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:wing_attack] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:wing_attack,:runtime_skill_key=>:mv_wing_attack,:name=>"翅膀攻擊",:name_en=>"Wing Attack",:type=>:flying,:category=>:physical,:canonical_power=>60,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:distance,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>60}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:gust] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:gust,:runtime_skill_key=>:mv_gust,:name=>"起風",:name_en=>"Gust",:type=>:flying,:category=>:special,:canonical_power=>40,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>35,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:distance,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>40}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:rock_throw] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:rock_throw,:runtime_skill_key=>:mv_rock_throw,:name=>"落石",:name_en=>"Rock Throw",:type=>:rock,:category=>:physical,:canonical_power=>50,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>50}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:horn_attack] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:horn_attack,:runtime_skill_key=>:mv_horn_attack,:name=>"角撞",:name_en=>"Horn Attack",:type=>:normal,:category=>:physical,:canonical_power=>65,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>65}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:vice_grip] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:vice_grip,:runtime_skill_key=>:mv_vice_grip,:name=>"夾住",:name_en=>"Vise Grip",:type=>:normal,:category=>:physical,:canonical_power=>55,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>55}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:mega_punch] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:mega_punch,:runtime_skill_key=>:mv_mega_punch,:name=>"百萬噸重拳",:name_en=>"Mega Punch",:type=>:normal,:category=>:physical,:canonical_power=>80,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect,:punch],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>80}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:mega_kick] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:mega_kick,:runtime_skill_key=>:mv_mega_kick,:name=>"百萬噸重踢",:name_en=>"Mega Kick",:type=>:normal,:category=>:physical,:canonical_power=>120,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>65,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>120}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:egg_bomb] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:egg_bomb,:runtime_skill_key=>:mv_egg_bomb,:name=>"炸蛋",:name_en=>"Egg Bomb",:type=>:normal,:category=>:physical,:canonical_power=>100,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>60,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:ballistics,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>100}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:power_gem] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:power_gem,:runtime_skill_key=>:mv_power_gem,:name=>"力量寶石",:name_en=>"Power Gem",:type=>:rock,:category=>:special,:canonical_power=>70,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>70}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:x_scissor] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:x_scissor,:runtime_skill_key=>:mv_x_scissor,:name=>"十字剪",:name_en=>"X-Scissor",:type=>:bug,:category=>:physical,:canonical_power=>80,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:web,:effects=>[{:type=>:damage,:power=>80}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:dragon_claw] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:dragon_claw,:runtime_skill_key=>:mv_dragon_claw,:name=>"龍爪",:name_en=>"Dragon Claw",:type=>:dragon,:category=>:physical,:canonical_power=>80,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>80}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:seed_bomb] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:seed_bomb,:runtime_skill_key=>:mv_seed_bomb,:name=>"種子炸彈",:name_en=>"Seed Bomb",:type=>:grass,:category=>:physical,:canonical_power=>80,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:ballistics,:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>80}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:power_whip] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:power_whip,:runtime_skill_key=>:mv_power_whip,:name=>"強力鞭打",:name_en=>"Power Whip",:type=>:grass,:category=>:physical,:canonical_power=>120,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>65,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>120}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:aqua_tail] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:aqua_tail,:runtime_skill_key=>:mv_aqua_tail,:name=>"水流尾",:name_en=>"Aqua Tail",:type=>:water,:category=>:physical,:canonical_power=>90,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:water,:effects=>[{:type=>:damage,:power=>90}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:megahorn] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:megahorn,:runtime_skill_key=>:mv_megahorn,:name=>"超級角擊",:name_en=>"Megahorn",:type=>:bug,:category=>:physical,:canonical_power=>120,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>65,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:web,:effects=>[{:type=>:damage,:power=>120}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:aura_sphere] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:aura_sphere,:runtime_skill_key=>:mv_aura_sphere,:name=>"波導彈",:name_en=>"Aura Sphere",:type=>:fighting,:category=>:special,:canonical_power=>90,:target=>:selected_pokemon,:contact=>false,:pulse=>true,:sound=>false,:behavior_status=>:implemented_primary,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:ballistics,:distance,:mirror,:protect,:pulse],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>90}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:perfect}
  MOVE_BEHAVIOR_V018[:dragon_pulse] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:dragon_pulse,:runtime_skill_key=>:mv_dragon_pulse,:name=>"龍之波動",:name_en=>"Dragon Pulse",:type=>:dragon,:category=>:special,:canonical_power=>90,:target=>:selected_pokemon,:contact=>false,:pulse=>true,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:distance,:mirror,:protect,:pulse],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>90}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:magical_leaf] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:magical_leaf,:runtime_skill_key=>:mv_magical_leaf,:name=>"魔法葉",:name_en=>"Magical Leaf",:type=>:grass,:category=>:special,:canonical_power=>60,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_primary,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>60}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:perfect}
  MOVE_BEHAVIOR_V018[:shock_wave] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:shock_wave,:runtime_skill_key=>:mv_shock_wave,:name=>"電擊波",:name_en=>"Shock Wave",:type=>:electric,:category=>:special,:canonical_power=>60,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_primary,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:electric,:effects=>[{:type=>:damage,:power=>60}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:perfect}
  MOVE_BEHAVIOR_V018[:magnet_bomb] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:magnet_bomb,:runtime_skill_key=>:mv_magnet_bomb,:name=>"磁鐵炸彈",:name_en=>"Magnet Bomb",:type=>:steel,:category=>:physical,:canonical_power=>60,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_primary,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:ballistics,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>60}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:perfect}
  MOVE_BEHAVIOR_V018[:feint_attack] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:feint_attack,:runtime_skill_key=>:mv_feint_attack,:name=>"出奇一擊",:name_en=>"Feint Attack",:type=>:dark,:category=>:physical,:canonical_power=>60,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_primary,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>60}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:aerial_ace] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:aerial_ace,:runtime_skill_key=>:mv_aerial_ace,:name=>"燕返",:name_en=>"Aerial Ace",:type=>:flying,:category=>:physical,:canonical_power=>60,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_primary,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:distance,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>60}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:shadow_punch] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:shadow_punch,:runtime_skill_key=>:mv_shadow_punch,:name=>"暗影拳",:name_en=>"Shadow Punch",:type=>:ghost,:category=>:physical,:canonical_power=>60,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_primary,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect,:punch],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>60}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:absorb] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:absorb,:runtime_skill_key=>:mv_absorb,:name=>"吸取",:name_en=>"Absorb",:type=>:grass,:category=>:special,:canonical_power=>20,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>30,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>20},{:type=>:drain,:ratio=>0.5}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:mega_drain] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:mega_drain,:runtime_skill_key=>:mv_mega_drain,:name=>"超級吸取",:name_en=>"Mega Drain",:type=>:grass,:category=>:special,:canonical_power=>40,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>35,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>40},{:type=>:drain,:ratio=>0.5}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:giga_drain] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:giga_drain,:runtime_skill_key=>:mv_giga_drain,:name=>"終極吸取",:name_en=>"Giga Drain",:type=>:grass,:category=>:special,:canonical_power=>75,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>75},{:type=>:drain,:ratio=>0.5}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:leech_life] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:leech_life,:runtime_skill_key=>:mv_leech_life,:name=>"吸血",:name_en=>"Leech Life",:type=>:bug,:category=>:physical,:canonical_power=>20,:target=>:selected_pokemon,:contact=>true,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>30,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:heal,:mirror,:protect],:vfx_style=>:web,:effects=>[{:type=>:damage,:power=>20},{:type=>:drain,:ratio=>0.5}],:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil}
  MOVE_BEHAVIOR_V018[:hyper_voice] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:hyper_voice,:runtime_skill_key=>:mv_hyper_voice,:name=>"巨聲",:name_en=>"Hyper Voice",:type=>:normal,:category=>:special,:canonical_power=>90,:target=>:all_opponents,:contact=>false,:pulse=>false,:sound=>true,:behavior_status=>:implemented_exact,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:authentic,:mirror,:protect,:sound],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>90}],:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:radius=>999.0,:range_px=>260.0,:projectile_tracking=>:strong}
  MOVE_BEHAVIOR_V018[:swift] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:swift,:runtime_skill_key=>:mv_swift,:name=>"高速星星",:name_en=>"Swift",:type=>:normal,:category=>:special,:canonical_power=>60,:target=>:all_opponents,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_primary,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>60}],:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:radius=>999.0,:range_px=>260.0,:projectile_tracking=>:perfect}
  MOVE_BEHAVIOR_V018[:substitute] = {:schema_version=>"1.0",:content_version=>"0.18.0",:canon_snapshot=>"2026-08-07",:move_key=>:substitute,:runtime_skill_key=>:mv_substitute,:name=>"替身",:name_en=>"Substitute",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:user,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:non_sky_battle,:snatch],:vfx_style=>:neutral,:effects=>[{:type=>:battle_object,:object=>:substitute,:placement=>:self,:hp_cost_ratio=>0.25,:offset_x=>18}],:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:projectile_tracking=>nil}
end
