#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Stat Stage Data v0.19
# 分類：關卡／Stage
#
# 【用途／機制】
# 定義可選關卡、敵方編成、解鎖、招募與關卡 metadata。
#
# 【怎麼調整】
# 修改關卡時優先調整 STAGE_DB；例如新增第 4 關時複製一個關卡 Hash，改 enemy_setup、建議等級與招募池。
#
# 【本腳本主要設定常數／資料表】
# - STAT_STAGE_MANIFEST_V019 / STAT_STAGE_MOVE_V019
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#==============================================================================
# ■ PMD AutoChess Stat Stage Data v0.19 - GENERATED
#    Standard Pokemon battle stat-stage mapping; v0.18 behavior data untouched.
#==============================================================================
module PMD_AC
  STAT_STAGE_MANIFEST_V019 = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:new_mapped_move_count=>16,:previous_mapped_move_count=>39,:cumulative_mapped_move_count=>55,:learnset_reference_total=>7005,:new_reference_covered=>584,:cumulative_reference_covered=>1400,:cumulative_coverage_percent=>19.99,:runtime_checksum32=>1516240753,:runtime_file=>"Data/PMD_AutoChess_StatStages_v019_000.rvdata",:stat_stage_min=>-6,:stat_stage_max=>6,:speed_stage_runtime=>"stored_only_deferred_until_realtime_speed_mapping",:notes=>["Standard Pokémon stat stages use (2+n)/2 for nonnegative stages and 2/(2-n) for negative stages.","Stages are battle-runtime state and are not persisted into PokemonInstance.","v0.19 maps Attack, Defense, Sp.Atk and Sp.Def stage moves only; Speed-stage moves remain deferred.","Existing v0.18 39 canonical move behaviors remain unchanged and separate.","Existing custom percentage statuses still compose multiplicatively with Pokémon stat stages."]}
  STAT_STAGE_MOVE_V019 = {}
  STAT_STAGE_MOVE_V019[:acid_armor] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:acid_armor,:runtime_skill_key=>:mv_acid_armor,:name=>"溶化",:name_en=>"Acid Armor",:type=>:poison,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>2}]}
  STAT_STAGE_MOVE_V019[:amnesia] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:amnesia,:runtime_skill_key=>:mv_amnesia,:name=>"瞬間失憶",:name_en=>"Amnesia",:type=>:psychic,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:spdef,:stages=>2}]}
  STAT_STAGE_MOVE_V019[:barrier] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:barrier,:runtime_skill_key=>:mv_barrier,:name=>"屏障",:name_en=>"Barrier",:type=>:psychic,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>2}]}
  STAT_STAGE_MOVE_V019[:bulk_up] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:bulk_up,:runtime_skill_key=>:mv_bulk_up,:name=>"健美",:name_en=>"Bulk Up",:type=>:fighting,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>1},{:type=>:stat_stage,:stat=>:def,:stages=>1}]}
  STAT_STAGE_MOVE_V019[:calm_mind] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:calm_mind,:runtime_skill_key=>:mv_calm_mind,:name=>"冥想",:name_en=>"Calm Mind",:type=>:psychic,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:spatk,:stages=>1},{:type=>:stat_stage,:stat=>:spdef,:stages=>1}]}
  STAT_STAGE_MOVE_V019[:defense_curl] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:defense_curl,:runtime_skill_key=>:mv_defense_curl,:name=>"變圓",:name_en=>"Defense Curl",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>1}]}
  STAT_STAGE_MOVE_V019[:growl] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:growl,:runtime_skill_key=>:mv_growl,:name=>"叫聲",:name_en=>"Growl",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:all_opponents,:target_type=>:ground_enemy,:policy=>:current_target,:delivery=>:aoe,:range_px=>260.0,:radius=>999.0,:global_direct=>true,:contact=>false,:pulse=>false,:sound=>true,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:authentic,:mirror,:protect,:reflectable,:sound],:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>-1}]}
  STAT_STAGE_MOVE_V019[:harden] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:harden,:runtime_skill_key=>:mv_harden,:name=>"變硬",:name_en=>"Harden",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>1}]}
  STAT_STAGE_MOVE_V019[:howl] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:howl,:runtime_skill_key=>:mv_howl,:name=>"長嚎",:name_en=>"Howl",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>true,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch,:sound],:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>1}]}
  STAT_STAGE_MOVE_V019[:iron_defense] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:iron_defense,:runtime_skill_key=>:mv_iron_defense,:name=>"鐵壁",:name_en=>"Iron Defense",:type=>:steel,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>2}]}
  STAT_STAGE_MOVE_V019[:leer] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:leer,:runtime_skill_key=>:mv_leer,:name=>"瞪眼",:name_en=>"Leer",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:all_opponents,:target_type=>:ground_enemy,:policy=>:current_target,:delivery=>:aoe,:range_px=>260.0,:radius=>999.0,:global_direct=>true,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect,:reflectable],:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>-1}]}
  STAT_STAGE_MOVE_V019[:meditate] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:meditate,:runtime_skill_key=>:mv_meditate,:name=>"瑜伽姿勢",:name_en=>"Meditate",:type=>:psychic,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>1}]}
  STAT_STAGE_MOVE_V019[:nasty_plot] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:nasty_plot,:runtime_skill_key=>:mv_nasty_plot,:name=>"詭計",:name_en=>"Nasty Plot",:type=>:dark,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:effects=>[{:type=>:stat_stage,:stat=>:spatk,:stages=>2}]}
  STAT_STAGE_MOVE_V019[:screech] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:screech,:runtime_skill_key=>:mv_screech,:name=>"刺耳聲",:name_en=>"Screech",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:selected_pokemon,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>true,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:authentic,:mirror,:protect,:reflectable,:sound],:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>-2}]}
  STAT_STAGE_MOVE_V019[:swords_dance] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:swords_dance,:runtime_skill_key=>:mv_swords_dance,:name=>"劍舞",:name_en=>"Swords Dance",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:self,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:radius=>nil,:global_direct=>false,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:dance,:snatch],:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>2}]}
  STAT_STAGE_MOVE_V019[:tail_whip] = {:schema_version=>"1.0",:content_version=>"0.19.0",:canon_snapshot=>"2026-08-07",:move_key=>:tail_whip,:runtime_skill_key=>:mv_tail_whip,:name=>"搖尾巴",:name_en=>"Tail Whip",:type=>:normal,:category=>:status,:canonical_power=>nil,:target=>:all_opponents,:target_type=>:ground_enemy,:policy=>:current_target,:delivery=>:aoe,:range_px=>260.0,:radius=>999.0,:global_direct=>true,:contact=>false,:pulse=>false,:sound=>false,:behavior_status=>:implemented_exact,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect,:reflectable],:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>-1}]}
end
