#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Sustain Recoil Data v0.20
# 分類：命中／狀態
#
# 【用途／機制】
# 處理命中率、閃避、能力階級、持續效果、次要效果、速度／行動狀態。
#
# 【怎麼調整】
# 新增狀態時要同時處理附加、免疫、AI 判斷、Popup／戰鬥文字與清除時機。
#
# 【本腳本主要設定常數／資料表】
# - SUSTAIN_RECOIL_MANIFEST_V020 / SUSTAIN_RECOIL_MOVE_V020
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#==============================================================================
# ■ PMD AutoChess Sustain/Recoil Data v0.20 - GENERATED
#==============================================================================
module PMD_AC
  SUSTAIN_RECOIL_MANIFEST_V020 = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:new_mapped_move_count=>15,:previous_mapped_move_count=>55,:cumulative_mapped_move_count=>70,:learnset_reference_total=>7005,:new_reference_covered=>205,:cumulative_reference_covered=>1605,:cumulative_coverage_percent=>22.91,:recovery_move_count=>8,:recoil_move_count=>7,:runtime_checksum32=>1406345673,:runtime_file=>"Data/PMD_AutoChess_SustainRecoil_v020_000.rvdata",:deferred_moves=>[:roost,:rest,:flare_blitz,:volt_tackle],:notes=>["Recovery uses canonical 50 percent max-HP healing from the move_meta snapshot.","Synthesis/Morning Sun/Moonlight use neutral-weather 50 percent because the project has no Weather Core yet.","Recoil uses canonical negative drain percentages and is applied after successful damage.","Recoil bypasses shields/damage-link and may KO the user, matching self-inflicted recoil semantics.","Roost remains deferred because temporary Flying-type removal is not implemented.","Flare Blitz and Volt Tackle remain deferred until canonical secondary-effect chance is implemented."]}
  SUSTAIN_RECOIL_MOVE_V020 = {}
  SUSTAIN_RECOIL_MOVE_V020[:brave_bird] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:brave_bird,:runtime_skill_key=>:mv_brave_bird,:name=>"勇鳥猛攻",:name_en=>"Brave Bird",:type=>:flying,:category=>:physical,:canonical_power=>120,:contact=>true,:pulse=>false,:sound=>false,:energy_cost_hint=>65,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:distance,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>120},{:type=>:recoil_last_damage,:ratio=>0.33}],:target=>:selected_pokemon,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_primary,:canonical_recoil_percent=>33}
  SUSTAIN_RECOIL_MOVE_V020[:double_edge] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:double_edge,:runtime_skill_key=>:mv_double_edge,:name=>"捨身衝撞",:name_en=>"Double-Edge",:type=>:normal,:category=>:physical,:canonical_power=>120,:contact=>true,:pulse=>false,:sound=>false,:energy_cost_hint=>65,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>120},{:type=>:recoil_last_damage,:ratio=>0.33}],:target=>:selected_pokemon,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_primary,:canonical_recoil_percent=>33}
  SUSTAIN_RECOIL_MOVE_V020[:head_smash] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:head_smash,:runtime_skill_key=>:mv_head_smash,:name=>"雙刃頭錘",:name_en=>"Head Smash",:type=>:rock,:category=>:physical,:canonical_power=>150,:contact=>true,:pulse=>false,:sound=>false,:energy_cost_hint=>75,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>150},{:type=>:recoil_last_damage,:ratio=>0.5}],:target=>:selected_pokemon,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_primary,:canonical_recoil_percent=>50}
  SUSTAIN_RECOIL_MOVE_V020[:heal_order] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:heal_order,:runtime_skill_key=>:mv_heal_order,:name=>"回復指令",:name_en=>"Heal Order",:type=>:bug,:category=>:status,:canonical_power=>nil,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:snatch],:vfx_style=>:web,:effects=>[{:type=>:heal_maxhp_ratio,:ratio=>0.5}],:target=>:user,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_no_weather}
  SUSTAIN_RECOIL_MOVE_V020[:milk_drink] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:milk_drink,:runtime_skill_key=>:mv_milk_drink,:name=>"喝牛奶",:name_en=>"Milk Drink",:type=>:normal,:category=>:status,:canonical_power=>nil,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:snatch],:vfx_style=>:neutral,:effects=>[{:type=>:heal_maxhp_ratio,:ratio=>0.5}],:target=>:user,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_no_weather}
  SUSTAIN_RECOIL_MOVE_V020[:moonlight] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:moonlight,:runtime_skill_key=>:mv_moonlight,:name=>"月光",:name_en=>"Moonlight",:type=>:normal,:category=>:status,:canonical_power=>nil,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:snatch],:vfx_style=>:neutral,:effects=>[{:type=>:heal_maxhp_ratio,:ratio=>0.5}],:target=>:user,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_no_weather,:weather_dependency=>"neutral_weather_50_percent; weather modifiers deferred until Weather phase"}
  SUSTAIN_RECOIL_MOVE_V020[:morning_sun] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:morning_sun,:runtime_skill_key=>:mv_morning_sun,:name=>"晨光",:name_en=>"Morning Sun",:type=>:normal,:category=>:status,:canonical_power=>nil,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:snatch],:vfx_style=>:neutral,:effects=>[{:type=>:heal_maxhp_ratio,:ratio=>0.5}],:target=>:user,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_no_weather,:weather_dependency=>"neutral_weather_50_percent; weather modifiers deferred until Weather phase"}
  SUSTAIN_RECOIL_MOVE_V020[:recover] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:recover,:runtime_skill_key=>:mv_recover,:name=>"自我再生",:name_en=>"Recover",:type=>:normal,:category=>:status,:canonical_power=>nil,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:snatch],:vfx_style=>:neutral,:effects=>[{:type=>:heal_maxhp_ratio,:ratio=>0.5}],:target=>:user,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_no_weather}
  SUSTAIN_RECOIL_MOVE_V020[:slack_off] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:slack_off,:runtime_skill_key=>:mv_slack_off,:name=>"偷懶",:name_en=>"Slack Off",:type=>:normal,:category=>:status,:canonical_power=>nil,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:snatch],:vfx_style=>:neutral,:effects=>[{:type=>:heal_maxhp_ratio,:ratio=>0.5}],:target=>:user,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_no_weather}
  SUSTAIN_RECOIL_MOVE_V020[:soft_boiled] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:soft_boiled,:runtime_skill_key=>:mv_soft_boiled,:name=>"生蛋",:name_en=>"Soft-Boiled",:type=>:normal,:category=>:status,:canonical_power=>nil,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:snatch],:vfx_style=>:neutral,:effects=>[{:type=>:heal_maxhp_ratio,:ratio=>0.5}],:target=>:user,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_no_weather}
  SUSTAIN_RECOIL_MOVE_V020[:submission] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:submission,:runtime_skill_key=>:mv_submission,:name=>"地獄翻滾",:name_en=>"Submission",:type=>:fighting,:category=>:physical,:canonical_power=>80,:contact=>true,:pulse=>false,:sound=>false,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>80},{:type=>:recoil_last_damage,:ratio=>0.25}],:target=>:selected_pokemon,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_primary,:canonical_recoil_percent=>25}
  SUSTAIN_RECOIL_MOVE_V020[:synthesis] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:synthesis,:runtime_skill_key=>:mv_synthesis,:name=>"光合作用",:name_en=>"Synthesis",:type=>:grass,:category=>:status,:canonical_power=>nil,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:heal,:snatch],:vfx_style=>:seed,:effects=>[{:type=>:heal_maxhp_ratio,:ratio=>0.5}],:target=>:user,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0.0,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_no_weather,:weather_dependency=>"neutral_weather_50_percent; weather modifiers deferred until Weather phase"}
  SUSTAIN_RECOIL_MOVE_V020[:take_down] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:take_down,:runtime_skill_key=>:mv_take_down,:name=>"猛撞",:name_en=>"Take Down",:type=>:normal,:category=>:physical,:canonical_power=>90,:contact=>true,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:neutral,:effects=>[{:type=>:damage,:power=>90},{:type=>:recoil_last_damage,:ratio=>0.25}],:target=>:selected_pokemon,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_primary,:canonical_recoil_percent=>25}
  SUSTAIN_RECOIL_MOVE_V020[:wild_charge] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:wild_charge,:runtime_skill_key=>:mv_wild_charge,:name=>"瘋狂伏特",:name_en=>"Wild Charge",:type=>:electric,:category=>:physical,:canonical_power=>90,:contact=>true,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:electric,:effects=>[{:type=>:damage,:power=>90},{:type=>:recoil_last_damage,:ratio=>0.25}],:target=>:selected_pokemon,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_primary,:canonical_recoil_percent=>25}
  SUSTAIN_RECOIL_MOVE_V020[:wood_hammer] = {:schema_version=>"1.0",:content_version=>"0.20.0",:canon_snapshot=>"2026-08-07",:move_key=>:wood_hammer,:runtime_skill_key=>:mv_wood_hammer,:name=>"木槌",:name_en=>"Wood Hammer",:type=>:grass,:category=>:physical,:canonical_power=>120,:contact=>true,:pulse=>false,:sound=>false,:energy_cost_hint=>65,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:contact,:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>120},{:type=>:recoil_last_damage,:ratio=>0.33}],:target=>:selected_pokemon,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:force_contact_range=>true,:projectile_tracking=>nil,:behavior_status=>:implemented_exact_primary,:canonical_recoil_percent=>33}
end
