#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Ability Data v0.24
# 分類：特性 Ability
#
# 【用途／機制】
# 定義特性資料、觸發時機、被動效果與 Runtime 覆蓋。
#
# 【怎麼調整】
# 新增特性時先放 Data，再在對應 Runtime helper 實作；需要 Popup／LOG 的觸發效果要同步補呈現。
#
# 【本腳本主要設定常數／資料表】
# - ABILITY_MANIFEST_V024 / ABILITY_BEHAVIOR_V024 / ABILITY_SPECIES_SLOTS_V024
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#==============================================================================
# ■ PMD AutoChess Ability Data v0.24 - GENERATED
#==============================================================================
module PMD_AC
  ABILITY_MANIFEST_V024 = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:target_generation=>5,:species_count=>494,:unique_ability_count=>157,:total_slot_count=>1193,:corrected_slot_count=>27,:implemented_ability_count=>42,:implemented_normal_slot_ability_count=>40,:implemented_slot_count=>403,:implemented_slot_coverage_percent=>33.78,:species_with_any_implemented_ability=>318,:species_coverage_percent=>64.37,:form_specific_behavior_count=>2,:runtime_checksum32=>1129678711,:runtime_file=>"Data/PMD_AutoChess_Abilities_v024_000.rvdata",:source_commit=>"fb1605aac09064bb34a12a8b790c2b800b4d0550",:deferred_groups=>{:weather=>[:swift_swim,:chlorophyll,:sand_veil,:rain_dish,:solar_power,:hydration,:leaf_guard,:ice_body,:sand_force,:drought],:accuracy_evasion=>[:keen_eye,:compound_eyes,:hustle,:tangled_feet,:no_guard],:item_switch=>[:pressure,:run_away,:natural_cure,:pickup,:gluttony,:unnerve,:regenerator,:unburden,:frisk],:advanced_trigger=>[:shed_skin,:early_bird,:synchronize,:effect_spore,:speed_boost,:steadfast,:rattled,:weak_armor,:moxie,:defiant,:competitive,:analytic,:sniper,:magic_guard],:redirection_partial=>[:lightning_rod,:storm_drain],:other=>[:damp,:oblivious,:rivalry,:cute_charm,:telepathy,:infiltrator,:scrappy,:overcoat,:moody]},:notes=>["Generation V ability slots are reconstructed from pokemon_abilities.csv plus pokemon_abilities_past.csv instead of using modern slots blindly.","27 slot values differ from the modern snapshot for National Dex 0001-0494.","Weather, accuracy/evasion, item/switch and target-redirection abilities remain data-only until their dependent systems exist.","Tough Claws and Mega Launcher are enabled as form-specific behavior because contact/pulse move tags are now available."]}
  ABILITY_BEHAVIOR_V024 = {}
  ABILITY_SPECIES_SLOTS_V024 = {}
  ABILITY_BEHAVIOR_V024[:adaptability] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:adaptability,:kind=>:stab_multiplier,:behavior_status=>:implemented_ability_v024,:canonical_stab=>2.0,:base_stab=>1.5}
  ABILITY_BEHAVIOR_V024[:battle_armor] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:battle_armor,:kind=>:critical_immunity,:behavior_status=>:implemented_ability_v024}
  ABILITY_BEHAVIOR_V024[:blaze] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:blaze,:kind=>:low_hp_type,:behavior_status=>:implemented_ability_v024,:hook=>:low_hp_type,:type=>:fire,:threshold=>0.3333333333333333,:mult=>1.5}
  ABILITY_BEHAVIOR_V024[:clear_body] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:clear_body,:kind=>:stat_drop_immunity,:behavior_status=>:implemented_ability_v024,:stats=>:all}
  ABILITY_BEHAVIOR_V024[:filter] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:filter,:kind=>:super_effective_reduction,:behavior_status=>:implemented_ability_v024,:mult=>0.75}
  ABILITY_BEHAVIOR_V024[:flame_body] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:flame_body,:kind=>:contact_status,:behavior_status=>:implemented_ability_v024,:status=>:burn,:chance=>30}
  ABILITY_BEHAVIOR_V024[:flash_fire] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:flash_fire,:kind=>:type_absorb_boost,:behavior_status=>:implemented_ability_v024,:type=>:fire,:boost_mult=>1.5}
  ABILITY_BEHAVIOR_V024[:guts] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:guts,:kind=>:status_physical,:behavior_status=>:implemented_ability_v024,:hook=>:status_physical,:mult=>1.5}
  ABILITY_BEHAVIOR_V024[:huge_power] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:huge_power,:kind=>:physical_multiplier,:behavior_status=>:implemented_ability_v024,:mult=>2.0}
  ABILITY_BEHAVIOR_V024[:hyper_cutter] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:hyper_cutter,:kind=>:stat_drop_immunity,:behavior_status=>:implemented_ability_v024,:stats=>[:atk]}
  ABILITY_BEHAVIOR_V024[:immunity] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:immunity,:kind=>:status_immunity,:behavior_status=>:implemented_ability_v024,:statuses=>[:poison]}
  ABILITY_BEHAVIOR_V024[:inner_focus] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:inner_focus,:kind=>:status_immunity,:behavior_status=>:implemented_ability_v024,:statuses=>[:flinch]}
  ABILITY_BEHAVIOR_V024[:insomnia] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:insomnia,:kind=>:status_immunity,:behavior_status=>:implemented_ability_v024,:statuses=>[:sleep]}
  ABILITY_BEHAVIOR_V024[:intimidate] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:intimidate,:kind=>:entry_stat_stage,:behavior_status=>:implemented_ability_v024,:target=>:all_opponents,:stat=>:atk,:stages=>-1}
  ABILITY_BEHAVIOR_V024[:iron_fist] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:iron_fist,:kind=>:move_flag_power,:behavior_status=>:implemented_ability_v024,:flag=>:punch,:mult=>1.2}
  ABILITY_BEHAVIOR_V024[:levitate] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:levitate,:kind=>:type_immunity,:behavior_status=>:implemented_ability_v024,:type=>:ground}
  ABILITY_BEHAVIOR_V024[:limber] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:limber,:kind=>:status_immunity,:behavior_status=>:implemented_ability_v024,:statuses=>[:paralysis]}
  ABILITY_BEHAVIOR_V024[:magma_armor] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:magma_armor,:kind=>:status_immunity,:behavior_status=>:implemented_ability_v024,:statuses=>[:freeze]}
  ABILITY_BEHAVIOR_V024[:mega_launcher] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:mega_launcher,:kind=>:move_flag_power,:behavior_status=>:implemented_ability_v024,:flag=>:pulse,:mult=>1.5,:form_only=>true}
  ABILITY_BEHAVIOR_V024[:overgrow] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:overgrow,:kind=>:low_hp_type,:behavior_status=>:implemented_ability_v024,:hook=>:low_hp_type,:type=>:grass,:threshold=>0.3333333333333333,:mult=>1.5}
  ABILITY_BEHAVIOR_V024[:own_tempo] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:own_tempo,:kind=>:status_immunity,:behavior_status=>:implemented_ability_v024,:statuses=>[:confusion]}
  ABILITY_BEHAVIOR_V024[:poison_point] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:poison_point,:kind=>:contact_status,:behavior_status=>:implemented_ability_v024,:status=>:poison,:chance=>30}
  ABILITY_BEHAVIOR_V024[:pure_power] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:pure_power,:kind=>:physical_multiplier,:behavior_status=>:implemented_ability_v024,:mult=>2.0}
  ABILITY_BEHAVIOR_V024[:reckless] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:reckless,:kind=>:recoil_move_power,:behavior_status=>:implemented_ability_v024,:mult=>1.2}
  ABILITY_BEHAVIOR_V024[:rock_head] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:rock_head,:kind=>:recoil_immunity,:behavior_status=>:implemented_ability_v024}
  ABILITY_BEHAVIOR_V024[:serene_grace] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:serene_grace,:kind=>:secondary_chance_multiplier,:behavior_status=>:implemented_ability_v024,:mult=>2.0}
  ABILITY_BEHAVIOR_V024[:shell_armor] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:shell_armor,:kind=>:critical_immunity,:behavior_status=>:implemented_ability_v024}
  ABILITY_BEHAVIOR_V024[:shield_dust] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:shield_dust,:kind=>:secondary_block,:behavior_status=>:implemented_ability_v024}
  ABILITY_BEHAVIOR_V024[:solid_rock] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:solid_rock,:kind=>:super_effective_reduction,:behavior_status=>:implemented_ability_v024,:mult=>0.75}
  ABILITY_BEHAVIOR_V024[:soundproof] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:soundproof,:kind=>:sound_immunity,:behavior_status=>:implemented_ability_v024}
  ABILITY_BEHAVIOR_V024[:static] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:static,:kind=>:contact_status,:behavior_status=>:implemented_ability_v024,:status=>:paralysis,:chance=>30}
  ABILITY_BEHAVIOR_V024[:swarm] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:swarm,:kind=>:low_hp_type,:behavior_status=>:implemented_ability_v024,:type=>:bug,:threshold=>0.3333333333333333,:mult=>1.5}
  ABILITY_BEHAVIOR_V024[:technician] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:technician,:kind=>:move_power_threshold,:behavior_status=>:implemented_ability_v024,:max_power=>60,:mult=>1.5}
  ABILITY_BEHAVIOR_V024[:thick_fat] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:thick_fat,:kind=>:incoming_type_reduction,:behavior_status=>:implemented_ability_v024,:hook=>:incoming_type_reduction,:types=>[:fire,:ice],:mult=>0.5}
  ABILITY_BEHAVIOR_V024[:tinted_lens] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:tinted_lens,:kind=>:resist_break,:behavior_status=>:implemented_ability_v024,:hook=>:resist_break,:mult=>2.0}
  ABILITY_BEHAVIOR_V024[:torrent] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:torrent,:kind=>:low_hp_type,:behavior_status=>:implemented_ability_v024,:hook=>:low_hp_type,:type=>:water,:threshold=>0.3333333333333333,:mult=>1.5}
  ABILITY_BEHAVIOR_V024[:tough_claws] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:tough_claws,:kind=>:move_flag_power,:behavior_status=>:implemented_ability_v024,:flag=>:contact,:mult=>1.3,:form_only=>true}
  ABILITY_BEHAVIOR_V024[:vital_spirit] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:vital_spirit,:kind=>:status_immunity,:behavior_status=>:implemented_ability_v024,:statuses=>[:sleep]}
  ABILITY_BEHAVIOR_V024[:volt_absorb] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:volt_absorb,:kind=>:type_absorb,:behavior_status=>:implemented_ability_v024,:type=>:electric,:heal_ratio=>0.25}
  ABILITY_BEHAVIOR_V024[:water_absorb] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:water_absorb,:kind=>:type_absorb,:behavior_status=>:implemented_ability_v024,:type=>:water,:heal_ratio=>0.25}
  ABILITY_BEHAVIOR_V024[:water_veil] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:water_veil,:kind=>:status_immunity,:behavior_status=>:implemented_ability_v024,:statuses=>[:burn]}
  ABILITY_BEHAVIOR_V024[:white_smoke] = {:schema_version=>"1.0",:content_version=>"0.24.0",:canon_snapshot=>"2026-08-07",:ruleset=>"black_white",:ability_key=>:white_smoke,:kind=>:stat_drop_immunity,:behavior_status=>:implemented_ability_v024,:stats=>:all}
  ABILITY_SPECIES_SLOTS_V024[:abomasnow] = {:primary=>:snow_warning,:secondary=>nil,:hidden=>:soundproof}
  ABILITY_SPECIES_SLOTS_V024[:abra] = {:primary=>:synchronize,:secondary=>:inner_focus,:hidden=>:magic_guard}
  ABILITY_SPECIES_SLOTS_V024[:absol] = {:primary=>:pressure,:secondary=>:super_luck,:hidden=>:justified}
  ABILITY_SPECIES_SLOTS_V024[:aerodactyl] = {:primary=>:rock_head,:secondary=>:pressure,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:aggron] = {:primary=>:sturdy,:secondary=>:rock_head,:hidden=>:heavy_metal}
  ABILITY_SPECIES_SLOTS_V024[:aipom] = {:primary=>:run_away,:secondary=>:pickup,:hidden=>:skill_link}
  ABILITY_SPECIES_SLOTS_V024[:alakazam] = {:primary=>:synchronize,:secondary=>:inner_focus,:hidden=>:magic_guard}
  ABILITY_SPECIES_SLOTS_V024[:altaria] = {:primary=>:natural_cure,:secondary=>nil,:hidden=>:cloud_nine}
  ABILITY_SPECIES_SLOTS_V024[:ambipom] = {:primary=>:technician,:secondary=>:pickup,:hidden=>:skill_link}
  ABILITY_SPECIES_SLOTS_V024[:ampharos] = {:primary=>:static,:secondary=>nil,:hidden=>:plus}
  ABILITY_SPECIES_SLOTS_V024[:anorith] = {:primary=>:battle_armor,:secondary=>nil,:hidden=>:swift_swim}
  ABILITY_SPECIES_SLOTS_V024[:arbok] = {:primary=>:intimidate,:secondary=>:shed_skin,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:arcanine] = {:primary=>:intimidate,:secondary=>:flash_fire,:hidden=>:justified}
  ABILITY_SPECIES_SLOTS_V024[:arceus] = {:primary=>:multitype,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:ariados] = {:primary=>:swarm,:secondary=>:insomnia,:hidden=>:sniper}
  ABILITY_SPECIES_SLOTS_V024[:armaldo] = {:primary=>:battle_armor,:secondary=>nil,:hidden=>:swift_swim}
  ABILITY_SPECIES_SLOTS_V024[:aron] = {:primary=>:sturdy,:secondary=>:rock_head,:hidden=>:heavy_metal}
  ABILITY_SPECIES_SLOTS_V024[:articuno] = {:primary=>:pressure,:secondary=>nil,:hidden=>:snow_cloak}
  ABILITY_SPECIES_SLOTS_V024[:azelf] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:azumarill] = {:primary=>:thick_fat,:secondary=>:huge_power,:hidden=>:sap_sipper}
  ABILITY_SPECIES_SLOTS_V024[:azurill] = {:primary=>:thick_fat,:secondary=>:huge_power,:hidden=>:sap_sipper}
  ABILITY_SPECIES_SLOTS_V024[:bagon] = {:primary=>:rock_head,:secondary=>nil,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:baltoy] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:banette] = {:primary=>:insomnia,:secondary=>:frisk,:hidden=>:cursed_body}
  ABILITY_SPECIES_SLOTS_V024[:barboach] = {:primary=>:oblivious,:secondary=>:anticipation,:hidden=>:hydration}
  ABILITY_SPECIES_SLOTS_V024[:bastiodon] = {:primary=>:sturdy,:secondary=>nil,:hidden=>:soundproof}
  ABILITY_SPECIES_SLOTS_V024[:bayleef] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:leaf_guard}
  ABILITY_SPECIES_SLOTS_V024[:beautifly] = {:primary=>:swarm,:secondary=>nil,:hidden=>:rivalry}
  ABILITY_SPECIES_SLOTS_V024[:beedrill] = {:primary=>:swarm,:secondary=>nil,:hidden=>:sniper}
  ABILITY_SPECIES_SLOTS_V024[:beldum] = {:primary=>:clear_body,:secondary=>nil,:hidden=>:light_metal}
  ABILITY_SPECIES_SLOTS_V024[:bellossom] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:healer}
  ABILITY_SPECIES_SLOTS_V024[:bellsprout] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:bibarel] = {:primary=>:simple,:secondary=>:unaware,:hidden=>:moody}
  ABILITY_SPECIES_SLOTS_V024[:bidoof] = {:primary=>:simple,:secondary=>:unaware,:hidden=>:moody}
  ABILITY_SPECIES_SLOTS_V024[:blastoise] = {:primary=>:torrent,:secondary=>nil,:hidden=>:rain_dish}
  ABILITY_SPECIES_SLOTS_V024[:blaziken] = {:primary=>:blaze,:secondary=>nil,:hidden=>:speed_boost}
  ABILITY_SPECIES_SLOTS_V024[:blissey] = {:primary=>:natural_cure,:secondary=>:serene_grace,:hidden=>:healer}
  ABILITY_SPECIES_SLOTS_V024[:bonsly] = {:primary=>:sturdy,:secondary=>:rock_head,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:breloom] = {:primary=>:effect_spore,:secondary=>:poison_heal,:hidden=>:technician}
  ABILITY_SPECIES_SLOTS_V024[:bronzong] = {:primary=>:levitate,:secondary=>:heatproof,:hidden=>:heavy_metal}
  ABILITY_SPECIES_SLOTS_V024[:bronzor] = {:primary=>:levitate,:secondary=>:heatproof,:hidden=>:heavy_metal}
  ABILITY_SPECIES_SLOTS_V024[:budew] = {:primary=>:natural_cure,:secondary=>:poison_point,:hidden=>:leaf_guard}
  ABILITY_SPECIES_SLOTS_V024[:buizel] = {:primary=>:swift_swim,:secondary=>nil,:hidden=>:water_veil}
  ABILITY_SPECIES_SLOTS_V024[:bulbasaur] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:chlorophyll}
  ABILITY_SPECIES_SLOTS_V024[:buneary] = {:primary=>:run_away,:secondary=>:klutz,:hidden=>:limber}
  ABILITY_SPECIES_SLOTS_V024[:burmy] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>:overcoat}
  ABILITY_SPECIES_SLOTS_V024[:butterfree] = {:primary=>:compound_eyes,:secondary=>nil,:hidden=>:tinted_lens}
  ABILITY_SPECIES_SLOTS_V024[:cacnea] = {:primary=>:sand_veil,:secondary=>nil,:hidden=>:water_absorb}
  ABILITY_SPECIES_SLOTS_V024[:cacturne] = {:primary=>:sand_veil,:secondary=>nil,:hidden=>:water_absorb}
  ABILITY_SPECIES_SLOTS_V024[:camerupt] = {:primary=>:magma_armor,:secondary=>:solid_rock,:hidden=>:anger_point}
  ABILITY_SPECIES_SLOTS_V024[:carnivine] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:carvanha] = {:primary=>:rough_skin,:secondary=>nil,:hidden=>:speed_boost}
  ABILITY_SPECIES_SLOTS_V024[:cascoon] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:castform] = {:primary=>:forecast,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:caterpie] = {:primary=>:shield_dust,:secondary=>nil,:hidden=>:run_away}
  ABILITY_SPECIES_SLOTS_V024[:celebi] = {:primary=>:natural_cure,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:chansey] = {:primary=>:natural_cure,:secondary=>:serene_grace,:hidden=>:healer}
  ABILITY_SPECIES_SLOTS_V024[:charizard] = {:primary=>:blaze,:secondary=>nil,:hidden=>:solar_power}
  ABILITY_SPECIES_SLOTS_V024[:charmander] = {:primary=>:blaze,:secondary=>nil,:hidden=>:solar_power}
  ABILITY_SPECIES_SLOTS_V024[:charmeleon] = {:primary=>:blaze,:secondary=>nil,:hidden=>:solar_power}
  ABILITY_SPECIES_SLOTS_V024[:chatot] = {:primary=>:keen_eye,:secondary=>:tangled_feet,:hidden=>:big_pecks}
  ABILITY_SPECIES_SLOTS_V024[:cherrim] = {:primary=>:flower_gift,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:cherubi] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:chikorita] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:leaf_guard}
  ABILITY_SPECIES_SLOTS_V024[:chimchar] = {:primary=>:blaze,:secondary=>nil,:hidden=>:iron_fist}
  ABILITY_SPECIES_SLOTS_V024[:chimecho] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:chinchou] = {:primary=>:volt_absorb,:secondary=>:illuminate,:hidden=>:water_absorb}
  ABILITY_SPECIES_SLOTS_V024[:chingling] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:clamperl] = {:primary=>:shell_armor,:secondary=>nil,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:claydol] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:clefable] = {:primary=>:cute_charm,:secondary=>:magic_guard,:hidden=>:unaware}
  ABILITY_SPECIES_SLOTS_V024[:clefairy] = {:primary=>:cute_charm,:secondary=>:magic_guard,:hidden=>:friend_guard}
  ABILITY_SPECIES_SLOTS_V024[:cleffa] = {:primary=>:cute_charm,:secondary=>:magic_guard,:hidden=>:friend_guard}
  ABILITY_SPECIES_SLOTS_V024[:cloyster] = {:primary=>:shell_armor,:secondary=>:skill_link,:hidden=>:overcoat}
  ABILITY_SPECIES_SLOTS_V024[:combee] = {:primary=>:honey_gather,:secondary=>nil,:hidden=>:hustle}
  ABILITY_SPECIES_SLOTS_V024[:combusken] = {:primary=>:blaze,:secondary=>nil,:hidden=>:speed_boost}
  ABILITY_SPECIES_SLOTS_V024[:corphish] = {:primary=>:hyper_cutter,:secondary=>:shell_armor,:hidden=>:adaptability}
  ABILITY_SPECIES_SLOTS_V024[:corsola] = {:primary=>:hustle,:secondary=>:natural_cure,:hidden=>:regenerator}
  ABILITY_SPECIES_SLOTS_V024[:cradily] = {:primary=>:suction_cups,:secondary=>nil,:hidden=>:storm_drain}
  ABILITY_SPECIES_SLOTS_V024[:cranidos] = {:primary=>:mold_breaker,:secondary=>nil,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:crawdaunt] = {:primary=>:hyper_cutter,:secondary=>:shell_armor,:hidden=>:adaptability}
  ABILITY_SPECIES_SLOTS_V024[:cresselia] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:croagunk] = {:primary=>:anticipation,:secondary=>:dry_skin,:hidden=>:poison_touch}
  ABILITY_SPECIES_SLOTS_V024[:crobat] = {:primary=>:inner_focus,:secondary=>nil,:hidden=>:infiltrator}
  ABILITY_SPECIES_SLOTS_V024[:croconaw] = {:primary=>:torrent,:secondary=>nil,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:cubone] = {:primary=>:rock_head,:secondary=>:lightning_rod,:hidden=>:battle_armor}
  ABILITY_SPECIES_SLOTS_V024[:cyndaquil] = {:primary=>:blaze,:secondary=>nil,:hidden=>:flash_fire}
  ABILITY_SPECIES_SLOTS_V024[:darkrai] = {:primary=>:bad_dreams,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:delcatty] = {:primary=>:cute_charm,:secondary=>:normalize,:hidden=>:wonder_skin}
  ABILITY_SPECIES_SLOTS_V024[:delibird] = {:primary=>:vital_spirit,:secondary=>:hustle,:hidden=>:insomnia}
  ABILITY_SPECIES_SLOTS_V024[:deoxys] = {:primary=>:pressure,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:dewgong] = {:primary=>:thick_fat,:secondary=>:hydration,:hidden=>:ice_body}
  ABILITY_SPECIES_SLOTS_V024[:dialga] = {:primary=>:pressure,:secondary=>nil,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:diglett] = {:primary=>:sand_veil,:secondary=>:arena_trap,:hidden=>:sand_force}
  ABILITY_SPECIES_SLOTS_V024[:ditto] = {:primary=>:limber,:secondary=>nil,:hidden=>:imposter}
  ABILITY_SPECIES_SLOTS_V024[:dodrio] = {:primary=>:run_away,:secondary=>:early_bird,:hidden=>:tangled_feet}
  ABILITY_SPECIES_SLOTS_V024[:doduo] = {:primary=>:run_away,:secondary=>:early_bird,:hidden=>:tangled_feet}
  ABILITY_SPECIES_SLOTS_V024[:donphan] = {:primary=>:sturdy,:secondary=>nil,:hidden=>:sand_veil}
  ABILITY_SPECIES_SLOTS_V024[:dragonair] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>:marvel_scale}
  ABILITY_SPECIES_SLOTS_V024[:dragonite] = {:primary=>:inner_focus,:secondary=>nil,:hidden=>:multiscale}
  ABILITY_SPECIES_SLOTS_V024[:drapion] = {:primary=>:battle_armor,:secondary=>:sniper,:hidden=>:keen_eye}
  ABILITY_SPECIES_SLOTS_V024[:dratini] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>:marvel_scale}
  ABILITY_SPECIES_SLOTS_V024[:drifblim] = {:primary=>:aftermath,:secondary=>:unburden,:hidden=>:flare_boost}
  ABILITY_SPECIES_SLOTS_V024[:drifloon] = {:primary=>:aftermath,:secondary=>:unburden,:hidden=>:flare_boost}
  ABILITY_SPECIES_SLOTS_V024[:drowzee] = {:primary=>:insomnia,:secondary=>:forewarn,:hidden=>:inner_focus}
  ABILITY_SPECIES_SLOTS_V024[:dugtrio] = {:primary=>:sand_veil,:secondary=>:arena_trap,:hidden=>:sand_force}
  ABILITY_SPECIES_SLOTS_V024[:dunsparce] = {:primary=>:serene_grace,:secondary=>:run_away,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:dusclops] = {:primary=>:pressure,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:dusknoir] = {:primary=>:pressure,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:duskull] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:dustox] = {:primary=>:shield_dust,:secondary=>nil,:hidden=>:compound_eyes}
  ABILITY_SPECIES_SLOTS_V024[:eevee] = {:primary=>:run_away,:secondary=>:adaptability,:hidden=>:anticipation}
  ABILITY_SPECIES_SLOTS_V024[:ekans] = {:primary=>:intimidate,:secondary=>:shed_skin,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:electabuzz] = {:primary=>:static,:secondary=>nil,:hidden=>:vital_spirit}
  ABILITY_SPECIES_SLOTS_V024[:electivire] = {:primary=>:motor_drive,:secondary=>nil,:hidden=>:vital_spirit}
  ABILITY_SPECIES_SLOTS_V024[:electrike] = {:primary=>:static,:secondary=>:lightning_rod,:hidden=>:minus}
  ABILITY_SPECIES_SLOTS_V024[:electrode] = {:primary=>:soundproof,:secondary=>:static,:hidden=>:aftermath}
  ABILITY_SPECIES_SLOTS_V024[:elekid] = {:primary=>:static,:secondary=>nil,:hidden=>:vital_spirit}
  ABILITY_SPECIES_SLOTS_V024[:empoleon] = {:primary=>:torrent,:secondary=>nil,:hidden=>:defiant}
  ABILITY_SPECIES_SLOTS_V024[:entei] = {:primary=>:pressure,:secondary=>nil,:hidden=>:flash_fire}
  ABILITY_SPECIES_SLOTS_V024[:espeon] = {:primary=>:synchronize,:secondary=>nil,:hidden=>:magic_bounce}
  ABILITY_SPECIES_SLOTS_V024[:exeggcute] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:harvest}
  ABILITY_SPECIES_SLOTS_V024[:exeggutor] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:harvest}
  ABILITY_SPECIES_SLOTS_V024[:exploud] = {:primary=>:soundproof,:secondary=>nil,:hidden=>:scrappy}
  ABILITY_SPECIES_SLOTS_V024[:farfetchd] = {:primary=>:keen_eye,:secondary=>:inner_focus,:hidden=>:defiant}
  ABILITY_SPECIES_SLOTS_V024[:fearow] = {:primary=>:keen_eye,:secondary=>nil,:hidden=>:sniper}
  ABILITY_SPECIES_SLOTS_V024[:feebas] = {:primary=>:swift_swim,:secondary=>nil,:hidden=>:adaptability}
  ABILITY_SPECIES_SLOTS_V024[:feraligatr] = {:primary=>:torrent,:secondary=>nil,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:finneon] = {:primary=>:swift_swim,:secondary=>:storm_drain,:hidden=>:water_veil}
  ABILITY_SPECIES_SLOTS_V024[:flaaffy] = {:primary=>:static,:secondary=>nil,:hidden=>:plus}
  ABILITY_SPECIES_SLOTS_V024[:flareon] = {:primary=>:flash_fire,:secondary=>nil,:hidden=>:guts}
  ABILITY_SPECIES_SLOTS_V024[:floatzel] = {:primary=>:swift_swim,:secondary=>nil,:hidden=>:water_veil}
  ABILITY_SPECIES_SLOTS_V024[:flygon] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:forretress] = {:primary=>:sturdy,:secondary=>nil,:hidden=>:overcoat}
  ABILITY_SPECIES_SLOTS_V024[:froslass] = {:primary=>:snow_cloak,:secondary=>nil,:hidden=>:cursed_body}
  ABILITY_SPECIES_SLOTS_V024[:furret] = {:primary=>:run_away,:secondary=>:keen_eye,:hidden=>:frisk}
  ABILITY_SPECIES_SLOTS_V024[:gabite] = {:primary=>:sand_veil,:secondary=>nil,:hidden=>:rough_skin}
  ABILITY_SPECIES_SLOTS_V024[:gallade] = {:primary=>:steadfast,:secondary=>nil,:hidden=>:justified}
  ABILITY_SPECIES_SLOTS_V024[:garchomp] = {:primary=>:sand_veil,:secondary=>nil,:hidden=>:rough_skin}
  ABILITY_SPECIES_SLOTS_V024[:gardevoir] = {:primary=>:synchronize,:secondary=>:trace,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:gastly] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:gastrodon] = {:primary=>:sticky_hold,:secondary=>:storm_drain,:hidden=>:sand_force}
  ABILITY_SPECIES_SLOTS_V024[:gengar] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:geodude] = {:primary=>:rock_head,:secondary=>:sturdy,:hidden=>:sand_veil}
  ABILITY_SPECIES_SLOTS_V024[:gible] = {:primary=>:sand_veil,:secondary=>nil,:hidden=>:rough_skin}
  ABILITY_SPECIES_SLOTS_V024[:girafarig] = {:primary=>:inner_focus,:secondary=>:early_bird,:hidden=>:sap_sipper}
  ABILITY_SPECIES_SLOTS_V024[:giratina] = {:primary=>:pressure,:secondary=>nil,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:glaceon] = {:primary=>:snow_cloak,:secondary=>nil,:hidden=>:ice_body}
  ABILITY_SPECIES_SLOTS_V024[:glalie] = {:primary=>:inner_focus,:secondary=>:ice_body,:hidden=>:moody}
  ABILITY_SPECIES_SLOTS_V024[:glameow] = {:primary=>:limber,:secondary=>:own_tempo,:hidden=>:keen_eye}
  ABILITY_SPECIES_SLOTS_V024[:gligar] = {:primary=>:hyper_cutter,:secondary=>:sand_veil,:hidden=>:immunity}
  ABILITY_SPECIES_SLOTS_V024[:gliscor] = {:primary=>:hyper_cutter,:secondary=>:sand_veil,:hidden=>:poison_heal}
  ABILITY_SPECIES_SLOTS_V024[:gloom] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:stench}
  ABILITY_SPECIES_SLOTS_V024[:golbat] = {:primary=>:inner_focus,:secondary=>nil,:hidden=>:infiltrator}
  ABILITY_SPECIES_SLOTS_V024[:goldeen] = {:primary=>:swift_swim,:secondary=>:water_veil,:hidden=>:lightning_rod}
  ABILITY_SPECIES_SLOTS_V024[:golduck] = {:primary=>:damp,:secondary=>:cloud_nine,:hidden=>:swift_swim}
  ABILITY_SPECIES_SLOTS_V024[:golem] = {:primary=>:rock_head,:secondary=>:sturdy,:hidden=>:sand_veil}
  ABILITY_SPECIES_SLOTS_V024[:gorebyss] = {:primary=>:swift_swim,:secondary=>nil,:hidden=>:hydration}
  ABILITY_SPECIES_SLOTS_V024[:granbull] = {:primary=>:intimidate,:secondary=>:quick_feet,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:graveler] = {:primary=>:rock_head,:secondary=>:sturdy,:hidden=>:sand_veil}
  ABILITY_SPECIES_SLOTS_V024[:grimer] = {:primary=>:stench,:secondary=>:sticky_hold,:hidden=>:poison_touch}
  ABILITY_SPECIES_SLOTS_V024[:grotle] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:shell_armor}
  ABILITY_SPECIES_SLOTS_V024[:groudon] = {:primary=>:drought,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:grovyle] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:unburden}
  ABILITY_SPECIES_SLOTS_V024[:growlithe] = {:primary=>:intimidate,:secondary=>:flash_fire,:hidden=>:justified}
  ABILITY_SPECIES_SLOTS_V024[:grumpig] = {:primary=>:thick_fat,:secondary=>:own_tempo,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:gulpin] = {:primary=>:liquid_ooze,:secondary=>:sticky_hold,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:gyarados] = {:primary=>:intimidate,:secondary=>nil,:hidden=>:moxie}
  ABILITY_SPECIES_SLOTS_V024[:happiny] = {:primary=>:natural_cure,:secondary=>:serene_grace,:hidden=>:friend_guard}
  ABILITY_SPECIES_SLOTS_V024[:hariyama] = {:primary=>:thick_fat,:secondary=>:guts,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:haunter] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:heatran] = {:primary=>:flash_fire,:secondary=>nil,:hidden=>:flame_body}
  ABILITY_SPECIES_SLOTS_V024[:heracross] = {:primary=>:swarm,:secondary=>:guts,:hidden=>:moxie}
  ABILITY_SPECIES_SLOTS_V024[:hippopotas] = {:primary=>:sand_stream,:secondary=>nil,:hidden=>:sand_force}
  ABILITY_SPECIES_SLOTS_V024[:hippowdon] = {:primary=>:sand_stream,:secondary=>nil,:hidden=>:sand_force}
  ABILITY_SPECIES_SLOTS_V024[:hitmonchan] = {:primary=>:keen_eye,:secondary=>:iron_fist,:hidden=>:inner_focus}
  ABILITY_SPECIES_SLOTS_V024[:hitmonlee] = {:primary=>:limber,:secondary=>:reckless,:hidden=>:unburden}
  ABILITY_SPECIES_SLOTS_V024[:hitmontop] = {:primary=>:intimidate,:secondary=>:technician,:hidden=>:steadfast}
  ABILITY_SPECIES_SLOTS_V024[:ho_oh] = {:primary=>:pressure,:secondary=>nil,:hidden=>:regenerator}
  ABILITY_SPECIES_SLOTS_V024[:honchkrow] = {:primary=>:insomnia,:secondary=>:super_luck,:hidden=>:moxie}
  ABILITY_SPECIES_SLOTS_V024[:hoothoot] = {:primary=>:insomnia,:secondary=>:keen_eye,:hidden=>:tinted_lens}
  ABILITY_SPECIES_SLOTS_V024[:hoppip] = {:primary=>:chlorophyll,:secondary=>:leaf_guard,:hidden=>:infiltrator}
  ABILITY_SPECIES_SLOTS_V024[:horsea] = {:primary=>:swift_swim,:secondary=>:sniper,:hidden=>:damp}
  ABILITY_SPECIES_SLOTS_V024[:houndoom] = {:primary=>:early_bird,:secondary=>:flash_fire,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:houndour] = {:primary=>:early_bird,:secondary=>:flash_fire,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:huntail] = {:primary=>:swift_swim,:secondary=>nil,:hidden=>:water_veil}
  ABILITY_SPECIES_SLOTS_V024[:hypno] = {:primary=>:insomnia,:secondary=>:forewarn,:hidden=>:inner_focus}
  ABILITY_SPECIES_SLOTS_V024[:igglybuff] = {:primary=>:cute_charm,:secondary=>nil,:hidden=>:friend_guard}
  ABILITY_SPECIES_SLOTS_V024[:illumise] = {:primary=>:oblivious,:secondary=>:tinted_lens,:hidden=>:prankster}
  ABILITY_SPECIES_SLOTS_V024[:infernape] = {:primary=>:blaze,:secondary=>nil,:hidden=>:iron_fist}
  ABILITY_SPECIES_SLOTS_V024[:ivysaur] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:chlorophyll}
  ABILITY_SPECIES_SLOTS_V024[:jigglypuff] = {:primary=>:cute_charm,:secondary=>nil,:hidden=>:friend_guard}
  ABILITY_SPECIES_SLOTS_V024[:jirachi] = {:primary=>:serene_grace,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:jolteon] = {:primary=>:volt_absorb,:secondary=>nil,:hidden=>:quick_feet}
  ABILITY_SPECIES_SLOTS_V024[:jumpluff] = {:primary=>:chlorophyll,:secondary=>:leaf_guard,:hidden=>:infiltrator}
  ABILITY_SPECIES_SLOTS_V024[:jynx] = {:primary=>:oblivious,:secondary=>:forewarn,:hidden=>:dry_skin}
  ABILITY_SPECIES_SLOTS_V024[:kabuto] = {:primary=>:swift_swim,:secondary=>:battle_armor,:hidden=>:weak_armor}
  ABILITY_SPECIES_SLOTS_V024[:kabutops] = {:primary=>:swift_swim,:secondary=>:battle_armor,:hidden=>:weak_armor}
  ABILITY_SPECIES_SLOTS_V024[:kadabra] = {:primary=>:synchronize,:secondary=>:inner_focus,:hidden=>:magic_guard}
  ABILITY_SPECIES_SLOTS_V024[:kakuna] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:kangaskhan] = {:primary=>:early_bird,:secondary=>:scrappy,:hidden=>:inner_focus}
  ABILITY_SPECIES_SLOTS_V024[:kecleon] = {:primary=>:color_change,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:kingdra] = {:primary=>:swift_swim,:secondary=>:sniper,:hidden=>:damp}
  ABILITY_SPECIES_SLOTS_V024[:kingler] = {:primary=>:hyper_cutter,:secondary=>:shell_armor,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:kirlia] = {:primary=>:synchronize,:secondary=>:trace,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:koffing] = {:primary=>:levitate,:secondary=>nil,:hidden=>:stench}
  ABILITY_SPECIES_SLOTS_V024[:krabby] = {:primary=>:hyper_cutter,:secondary=>:shell_armor,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:kricketot] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>:run_away}
  ABILITY_SPECIES_SLOTS_V024[:kricketune] = {:primary=>:swarm,:secondary=>nil,:hidden=>:technician}
  ABILITY_SPECIES_SLOTS_V024[:kyogre] = {:primary=>:drizzle,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:lairon] = {:primary=>:sturdy,:secondary=>:rock_head,:hidden=>:heavy_metal}
  ABILITY_SPECIES_SLOTS_V024[:lanturn] = {:primary=>:volt_absorb,:secondary=>:illuminate,:hidden=>:water_absorb}
  ABILITY_SPECIES_SLOTS_V024[:lapras] = {:primary=>:water_absorb,:secondary=>:shell_armor,:hidden=>:hydration}
  ABILITY_SPECIES_SLOTS_V024[:larvitar] = {:primary=>:guts,:secondary=>nil,:hidden=>:sand_veil}
  ABILITY_SPECIES_SLOTS_V024[:latias] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:latios] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:leafeon] = {:primary=>:leaf_guard,:secondary=>nil,:hidden=>:chlorophyll}
  ABILITY_SPECIES_SLOTS_V024[:ledian] = {:primary=>:swarm,:secondary=>:early_bird,:hidden=>:iron_fist}
  ABILITY_SPECIES_SLOTS_V024[:ledyba] = {:primary=>:swarm,:secondary=>:early_bird,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:lickilicky] = {:primary=>:own_tempo,:secondary=>:oblivious,:hidden=>:cloud_nine}
  ABILITY_SPECIES_SLOTS_V024[:lickitung] = {:primary=>:own_tempo,:secondary=>:oblivious,:hidden=>:cloud_nine}
  ABILITY_SPECIES_SLOTS_V024[:lileep] = {:primary=>:suction_cups,:secondary=>nil,:hidden=>:storm_drain}
  ABILITY_SPECIES_SLOTS_V024[:linoone] = {:primary=>:pickup,:secondary=>:gluttony,:hidden=>:quick_feet}
  ABILITY_SPECIES_SLOTS_V024[:lombre] = {:primary=>:swift_swim,:secondary=>:rain_dish,:hidden=>:own_tempo}
  ABILITY_SPECIES_SLOTS_V024[:lopunny] = {:primary=>:cute_charm,:secondary=>:klutz,:hidden=>:limber}
  ABILITY_SPECIES_SLOTS_V024[:lotad] = {:primary=>:swift_swim,:secondary=>:rain_dish,:hidden=>:own_tempo}
  ABILITY_SPECIES_SLOTS_V024[:loudred] = {:primary=>:soundproof,:secondary=>nil,:hidden=>:scrappy}
  ABILITY_SPECIES_SLOTS_V024[:lucario] = {:primary=>:steadfast,:secondary=>:inner_focus,:hidden=>:justified}
  ABILITY_SPECIES_SLOTS_V024[:ludicolo] = {:primary=>:swift_swim,:secondary=>:rain_dish,:hidden=>:own_tempo}
  ABILITY_SPECIES_SLOTS_V024[:lugia] = {:primary=>:pressure,:secondary=>nil,:hidden=>:multiscale}
  ABILITY_SPECIES_SLOTS_V024[:lumineon] = {:primary=>:swift_swim,:secondary=>:storm_drain,:hidden=>:water_veil}
  ABILITY_SPECIES_SLOTS_V024[:lunatone] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:luvdisc] = {:primary=>:swift_swim,:secondary=>nil,:hidden=>:hydration}
  ABILITY_SPECIES_SLOTS_V024[:luxio] = {:primary=>:rivalry,:secondary=>:intimidate,:hidden=>:guts}
  ABILITY_SPECIES_SLOTS_V024[:luxray] = {:primary=>:rivalry,:secondary=>:intimidate,:hidden=>:guts}
  ABILITY_SPECIES_SLOTS_V024[:machamp] = {:primary=>:guts,:secondary=>:no_guard,:hidden=>:steadfast}
  ABILITY_SPECIES_SLOTS_V024[:machoke] = {:primary=>:guts,:secondary=>:no_guard,:hidden=>:steadfast}
  ABILITY_SPECIES_SLOTS_V024[:machop] = {:primary=>:guts,:secondary=>:no_guard,:hidden=>:steadfast}
  ABILITY_SPECIES_SLOTS_V024[:magby] = {:primary=>:flame_body,:secondary=>nil,:hidden=>:vital_spirit}
  ABILITY_SPECIES_SLOTS_V024[:magcargo] = {:primary=>:magma_armor,:secondary=>:flame_body,:hidden=>:weak_armor}
  ABILITY_SPECIES_SLOTS_V024[:magikarp] = {:primary=>:swift_swim,:secondary=>nil,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:magmar] = {:primary=>:flame_body,:secondary=>nil,:hidden=>:vital_spirit}
  ABILITY_SPECIES_SLOTS_V024[:magmortar] = {:primary=>:flame_body,:secondary=>nil,:hidden=>:vital_spirit}
  ABILITY_SPECIES_SLOTS_V024[:magnemite] = {:primary=>:magnet_pull,:secondary=>:sturdy,:hidden=>:analytic}
  ABILITY_SPECIES_SLOTS_V024[:magneton] = {:primary=>:magnet_pull,:secondary=>:sturdy,:hidden=>:analytic}
  ABILITY_SPECIES_SLOTS_V024[:magnezone] = {:primary=>:magnet_pull,:secondary=>:sturdy,:hidden=>:analytic}
  ABILITY_SPECIES_SLOTS_V024[:makuhita] = {:primary=>:thick_fat,:secondary=>:guts,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:mamoswine] = {:primary=>:oblivious,:secondary=>:snow_cloak,:hidden=>:thick_fat}
  ABILITY_SPECIES_SLOTS_V024[:manaphy] = {:primary=>:hydration,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:manectric] = {:primary=>:static,:secondary=>:lightning_rod,:hidden=>:minus}
  ABILITY_SPECIES_SLOTS_V024[:mankey] = {:primary=>:vital_spirit,:secondary=>:anger_point,:hidden=>:defiant}
  ABILITY_SPECIES_SLOTS_V024[:mantine] = {:primary=>:swift_swim,:secondary=>:water_absorb,:hidden=>:water_veil}
  ABILITY_SPECIES_SLOTS_V024[:mantyke] = {:primary=>:swift_swim,:secondary=>:water_absorb,:hidden=>:water_veil}
  ABILITY_SPECIES_SLOTS_V024[:mareep] = {:primary=>:static,:secondary=>nil,:hidden=>:plus}
  ABILITY_SPECIES_SLOTS_V024[:marill] = {:primary=>:thick_fat,:secondary=>:huge_power,:hidden=>:sap_sipper}
  ABILITY_SPECIES_SLOTS_V024[:marowak] = {:primary=>:rock_head,:secondary=>:lightning_rod,:hidden=>:battle_armor}
  ABILITY_SPECIES_SLOTS_V024[:marshtomp] = {:primary=>:torrent,:secondary=>nil,:hidden=>:damp}
  ABILITY_SPECIES_SLOTS_V024[:masquerain] = {:primary=>:intimidate,:secondary=>nil,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:mawile] = {:primary=>:hyper_cutter,:secondary=>:intimidate,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:medicham] = {:primary=>:pure_power,:secondary=>nil,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:meditite] = {:primary=>:pure_power,:secondary=>nil,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:meganium] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:leaf_guard}
  ABILITY_SPECIES_SLOTS_V024[:meowth] = {:primary=>:pickup,:secondary=>:technician,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:mesprit] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:metagross] = {:primary=>:clear_body,:secondary=>nil,:hidden=>:light_metal}
  ABILITY_SPECIES_SLOTS_V024[:metang] = {:primary=>:clear_body,:secondary=>nil,:hidden=>:light_metal}
  ABILITY_SPECIES_SLOTS_V024[:metapod] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:mew] = {:primary=>:synchronize,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:mewtwo] = {:primary=>:pressure,:secondary=>nil,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:mightyena] = {:primary=>:intimidate,:secondary=>:quick_feet,:hidden=>:moxie}
  ABILITY_SPECIES_SLOTS_V024[:milotic] = {:primary=>:marvel_scale,:secondary=>nil,:hidden=>:cute_charm}
  ABILITY_SPECIES_SLOTS_V024[:miltank] = {:primary=>:thick_fat,:secondary=>:scrappy,:hidden=>:sap_sipper}
  ABILITY_SPECIES_SLOTS_V024[:mime_jr] = {:primary=>:soundproof,:secondary=>:filter,:hidden=>:technician}
  ABILITY_SPECIES_SLOTS_V024[:minun] = {:primary=>:minus,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:misdreavus] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:mismagius] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:moltres] = {:primary=>:pressure,:secondary=>nil,:hidden=>:flame_body}
  ABILITY_SPECIES_SLOTS_V024[:monferno] = {:primary=>:blaze,:secondary=>nil,:hidden=>:iron_fist}
  ABILITY_SPECIES_SLOTS_V024[:mothim] = {:primary=>:swarm,:secondary=>nil,:hidden=>:tinted_lens}
  ABILITY_SPECIES_SLOTS_V024[:mr_mime] = {:primary=>:soundproof,:secondary=>:filter,:hidden=>:technician}
  ABILITY_SPECIES_SLOTS_V024[:mudkip] = {:primary=>:torrent,:secondary=>nil,:hidden=>:damp}
  ABILITY_SPECIES_SLOTS_V024[:muk] = {:primary=>:stench,:secondary=>:sticky_hold,:hidden=>:poison_touch}
  ABILITY_SPECIES_SLOTS_V024[:munchlax] = {:primary=>:pickup,:secondary=>:thick_fat,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:murkrow] = {:primary=>:insomnia,:secondary=>:super_luck,:hidden=>:prankster}
  ABILITY_SPECIES_SLOTS_V024[:natu] = {:primary=>:synchronize,:secondary=>:early_bird,:hidden=>:magic_bounce}
  ABILITY_SPECIES_SLOTS_V024[:nidoking] = {:primary=>:poison_point,:secondary=>:rivalry,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:nidoqueen] = {:primary=>:poison_point,:secondary=>:rivalry,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:nidoran_f] = {:primary=>:poison_point,:secondary=>:rivalry,:hidden=>:hustle}
  ABILITY_SPECIES_SLOTS_V024[:nidoran_m] = {:primary=>:poison_point,:secondary=>:rivalry,:hidden=>:hustle}
  ABILITY_SPECIES_SLOTS_V024[:nidorina] = {:primary=>:poison_point,:secondary=>:rivalry,:hidden=>:hustle}
  ABILITY_SPECIES_SLOTS_V024[:nidorino] = {:primary=>:poison_point,:secondary=>:rivalry,:hidden=>:hustle}
  ABILITY_SPECIES_SLOTS_V024[:nincada] = {:primary=>:compound_eyes,:secondary=>nil,:hidden=>:run_away}
  ABILITY_SPECIES_SLOTS_V024[:ninetales] = {:primary=>:flash_fire,:secondary=>nil,:hidden=>:drought}
  ABILITY_SPECIES_SLOTS_V024[:ninjask] = {:primary=>:speed_boost,:secondary=>nil,:hidden=>:infiltrator}
  ABILITY_SPECIES_SLOTS_V024[:noctowl] = {:primary=>:insomnia,:secondary=>:keen_eye,:hidden=>:tinted_lens}
  ABILITY_SPECIES_SLOTS_V024[:nosepass] = {:primary=>:sturdy,:secondary=>:magnet_pull,:hidden=>:sand_force}
  ABILITY_SPECIES_SLOTS_V024[:numel] = {:primary=>:oblivious,:secondary=>:simple,:hidden=>:own_tempo}
  ABILITY_SPECIES_SLOTS_V024[:nuzleaf] = {:primary=>:chlorophyll,:secondary=>:early_bird,:hidden=>:pickpocket}
  ABILITY_SPECIES_SLOTS_V024[:octillery] = {:primary=>:suction_cups,:secondary=>:sniper,:hidden=>:moody}
  ABILITY_SPECIES_SLOTS_V024[:oddish] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:run_away}
  ABILITY_SPECIES_SLOTS_V024[:omanyte] = {:primary=>:swift_swim,:secondary=>:shell_armor,:hidden=>:weak_armor}
  ABILITY_SPECIES_SLOTS_V024[:omastar] = {:primary=>:swift_swim,:secondary=>:shell_armor,:hidden=>:weak_armor}
  ABILITY_SPECIES_SLOTS_V024[:onix] = {:primary=>:rock_head,:secondary=>:sturdy,:hidden=>:weak_armor}
  ABILITY_SPECIES_SLOTS_V024[:pachirisu] = {:primary=>:run_away,:secondary=>:pickup,:hidden=>:volt_absorb}
  ABILITY_SPECIES_SLOTS_V024[:palkia] = {:primary=>:pressure,:secondary=>nil,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:paras] = {:primary=>:effect_spore,:secondary=>:dry_skin,:hidden=>:damp}
  ABILITY_SPECIES_SLOTS_V024[:parasect] = {:primary=>:effect_spore,:secondary=>:dry_skin,:hidden=>:damp}
  ABILITY_SPECIES_SLOTS_V024[:pelipper] = {:primary=>:keen_eye,:secondary=>nil,:hidden=>:rain_dish}
  ABILITY_SPECIES_SLOTS_V024[:persian] = {:primary=>:limber,:secondary=>:technician,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:phanpy] = {:primary=>:pickup,:secondary=>nil,:hidden=>:sand_veil}
  ABILITY_SPECIES_SLOTS_V024[:phione] = {:primary=>:hydration,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:pichu] = {:primary=>:static,:secondary=>nil,:hidden=>:lightning_rod}
  ABILITY_SPECIES_SLOTS_V024[:pidgeot] = {:primary=>:keen_eye,:secondary=>:tangled_feet,:hidden=>:big_pecks}
  ABILITY_SPECIES_SLOTS_V024[:pidgeotto] = {:primary=>:keen_eye,:secondary=>:tangled_feet,:hidden=>:big_pecks}
  ABILITY_SPECIES_SLOTS_V024[:pidgey] = {:primary=>:keen_eye,:secondary=>:tangled_feet,:hidden=>:big_pecks}
  ABILITY_SPECIES_SLOTS_V024[:pikachu] = {:primary=>:static,:secondary=>nil,:hidden=>:lightning_rod}
  ABILITY_SPECIES_SLOTS_V024[:piloswine] = {:primary=>:oblivious,:secondary=>:snow_cloak,:hidden=>:thick_fat}
  ABILITY_SPECIES_SLOTS_V024[:pineco] = {:primary=>:sturdy,:secondary=>nil,:hidden=>:overcoat}
  ABILITY_SPECIES_SLOTS_V024[:pinsir] = {:primary=>:hyper_cutter,:secondary=>:mold_breaker,:hidden=>:moxie}
  ABILITY_SPECIES_SLOTS_V024[:piplup] = {:primary=>:torrent,:secondary=>nil,:hidden=>:defiant}
  ABILITY_SPECIES_SLOTS_V024[:plusle] = {:primary=>:plus,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:politoed] = {:primary=>:water_absorb,:secondary=>:damp,:hidden=>:drizzle}
  ABILITY_SPECIES_SLOTS_V024[:poliwag] = {:primary=>:water_absorb,:secondary=>:damp,:hidden=>:swift_swim}
  ABILITY_SPECIES_SLOTS_V024[:poliwhirl] = {:primary=>:water_absorb,:secondary=>:damp,:hidden=>:swift_swim}
  ABILITY_SPECIES_SLOTS_V024[:poliwrath] = {:primary=>:water_absorb,:secondary=>:damp,:hidden=>:swift_swim}
  ABILITY_SPECIES_SLOTS_V024[:ponyta] = {:primary=>:run_away,:secondary=>:flash_fire,:hidden=>:flame_body}
  ABILITY_SPECIES_SLOTS_V024[:poochyena] = {:primary=>:run_away,:secondary=>:quick_feet,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:porygon] = {:primary=>:trace,:secondary=>:download,:hidden=>:analytic}
  ABILITY_SPECIES_SLOTS_V024[:porygon2] = {:primary=>:trace,:secondary=>:download,:hidden=>:analytic}
  ABILITY_SPECIES_SLOTS_V024[:porygon_z] = {:primary=>:adaptability,:secondary=>:download,:hidden=>:analytic}
  ABILITY_SPECIES_SLOTS_V024[:primeape] = {:primary=>:vital_spirit,:secondary=>:anger_point,:hidden=>:defiant}
  ABILITY_SPECIES_SLOTS_V024[:prinplup] = {:primary=>:torrent,:secondary=>nil,:hidden=>:defiant}
  ABILITY_SPECIES_SLOTS_V024[:probopass] = {:primary=>:sturdy,:secondary=>:magnet_pull,:hidden=>:sand_force}
  ABILITY_SPECIES_SLOTS_V024[:psyduck] = {:primary=>:damp,:secondary=>:cloud_nine,:hidden=>:swift_swim}
  ABILITY_SPECIES_SLOTS_V024[:pupitar] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:purugly] = {:primary=>:thick_fat,:secondary=>:own_tempo,:hidden=>:defiant}
  ABILITY_SPECIES_SLOTS_V024[:quagsire] = {:primary=>:damp,:secondary=>:water_absorb,:hidden=>:unaware}
  ABILITY_SPECIES_SLOTS_V024[:quilava] = {:primary=>:blaze,:secondary=>nil,:hidden=>:flash_fire}
  ABILITY_SPECIES_SLOTS_V024[:qwilfish] = {:primary=>:poison_point,:secondary=>:swift_swim,:hidden=>:intimidate}
  ABILITY_SPECIES_SLOTS_V024[:raichu] = {:primary=>:static,:secondary=>nil,:hidden=>:lightning_rod}
  ABILITY_SPECIES_SLOTS_V024[:raikou] = {:primary=>:pressure,:secondary=>nil,:hidden=>:volt_absorb}
  ABILITY_SPECIES_SLOTS_V024[:ralts] = {:primary=>:synchronize,:secondary=>:trace,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:rampardos] = {:primary=>:mold_breaker,:secondary=>nil,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:rapidash] = {:primary=>:run_away,:secondary=>:flash_fire,:hidden=>:flame_body}
  ABILITY_SPECIES_SLOTS_V024[:raticate] = {:primary=>:run_away,:secondary=>:guts,:hidden=>:hustle}
  ABILITY_SPECIES_SLOTS_V024[:rattata] = {:primary=>:run_away,:secondary=>:guts,:hidden=>:hustle}
  ABILITY_SPECIES_SLOTS_V024[:rayquaza] = {:primary=>:air_lock,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:regice] = {:primary=>:clear_body,:secondary=>nil,:hidden=>:ice_body}
  ABILITY_SPECIES_SLOTS_V024[:regigigas] = {:primary=>:slow_start,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:regirock] = {:primary=>:clear_body,:secondary=>nil,:hidden=>:sturdy}
  ABILITY_SPECIES_SLOTS_V024[:registeel] = {:primary=>:clear_body,:secondary=>nil,:hidden=>:light_metal}
  ABILITY_SPECIES_SLOTS_V024[:relicanth] = {:primary=>:swift_swim,:secondary=>:rock_head,:hidden=>:sturdy}
  ABILITY_SPECIES_SLOTS_V024[:remoraid] = {:primary=>:hustle,:secondary=>:sniper,:hidden=>:moody}
  ABILITY_SPECIES_SLOTS_V024[:rhydon] = {:primary=>:lightning_rod,:secondary=>:rock_head,:hidden=>:reckless}
  ABILITY_SPECIES_SLOTS_V024[:rhyhorn] = {:primary=>:lightning_rod,:secondary=>:rock_head,:hidden=>:reckless}
  ABILITY_SPECIES_SLOTS_V024[:rhyperior] = {:primary=>:lightning_rod,:secondary=>:solid_rock,:hidden=>:reckless}
  ABILITY_SPECIES_SLOTS_V024[:riolu] = {:primary=>:steadfast,:secondary=>:inner_focus,:hidden=>:prankster}
  ABILITY_SPECIES_SLOTS_V024[:roselia] = {:primary=>:natural_cure,:secondary=>:poison_point,:hidden=>:leaf_guard}
  ABILITY_SPECIES_SLOTS_V024[:roserade] = {:primary=>:natural_cure,:secondary=>:poison_point,:hidden=>:technician}
  ABILITY_SPECIES_SLOTS_V024[:rotom] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:sableye] = {:primary=>:keen_eye,:secondary=>:stall,:hidden=>:prankster}
  ABILITY_SPECIES_SLOTS_V024[:salamence] = {:primary=>:intimidate,:secondary=>nil,:hidden=>:moxie}
  ABILITY_SPECIES_SLOTS_V024[:sandshrew] = {:primary=>:sand_veil,:secondary=>nil,:hidden=>:sand_rush}
  ABILITY_SPECIES_SLOTS_V024[:sandslash] = {:primary=>:sand_veil,:secondary=>nil,:hidden=>:sand_rush}
  ABILITY_SPECIES_SLOTS_V024[:sceptile] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:unburden}
  ABILITY_SPECIES_SLOTS_V024[:scizor] = {:primary=>:swarm,:secondary=>:technician,:hidden=>:light_metal}
  ABILITY_SPECIES_SLOTS_V024[:scyther] = {:primary=>:swarm,:secondary=>:technician,:hidden=>:steadfast}
  ABILITY_SPECIES_SLOTS_V024[:seadra] = {:primary=>:poison_point,:secondary=>:sniper,:hidden=>:damp}
  ABILITY_SPECIES_SLOTS_V024[:seaking] = {:primary=>:swift_swim,:secondary=>:water_veil,:hidden=>:lightning_rod}
  ABILITY_SPECIES_SLOTS_V024[:sealeo] = {:primary=>:thick_fat,:secondary=>:ice_body,:hidden=>:oblivious}
  ABILITY_SPECIES_SLOTS_V024[:seedot] = {:primary=>:chlorophyll,:secondary=>:early_bird,:hidden=>:pickpocket}
  ABILITY_SPECIES_SLOTS_V024[:seel] = {:primary=>:thick_fat,:secondary=>:hydration,:hidden=>:ice_body}
  ABILITY_SPECIES_SLOTS_V024[:sentret] = {:primary=>:run_away,:secondary=>:keen_eye,:hidden=>:frisk}
  ABILITY_SPECIES_SLOTS_V024[:seviper] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>:infiltrator}
  ABILITY_SPECIES_SLOTS_V024[:sharpedo] = {:primary=>:rough_skin,:secondary=>nil,:hidden=>:speed_boost}
  ABILITY_SPECIES_SLOTS_V024[:shaymin] = {:primary=>:natural_cure,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:shedinja] = {:primary=>:wonder_guard,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:shelgon] = {:primary=>:rock_head,:secondary=>nil,:hidden=>:overcoat}
  ABILITY_SPECIES_SLOTS_V024[:shellder] = {:primary=>:shell_armor,:secondary=>:skill_link,:hidden=>:overcoat}
  ABILITY_SPECIES_SLOTS_V024[:shellos] = {:primary=>:sticky_hold,:secondary=>:storm_drain,:hidden=>:sand_force}
  ABILITY_SPECIES_SLOTS_V024[:shieldon] = {:primary=>:sturdy,:secondary=>nil,:hidden=>:soundproof}
  ABILITY_SPECIES_SLOTS_V024[:shiftry] = {:primary=>:chlorophyll,:secondary=>:early_bird,:hidden=>:pickpocket}
  ABILITY_SPECIES_SLOTS_V024[:shinx] = {:primary=>:rivalry,:secondary=>:intimidate,:hidden=>:guts}
  ABILITY_SPECIES_SLOTS_V024[:shroomish] = {:primary=>:effect_spore,:secondary=>:poison_heal,:hidden=>:quick_feet}
  ABILITY_SPECIES_SLOTS_V024[:shuckle] = {:primary=>:sturdy,:secondary=>:gluttony,:hidden=>:contrary}
  ABILITY_SPECIES_SLOTS_V024[:shuppet] = {:primary=>:insomnia,:secondary=>:frisk,:hidden=>:cursed_body}
  ABILITY_SPECIES_SLOTS_V024[:silcoon] = {:primary=>:shed_skin,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:skarmory] = {:primary=>:keen_eye,:secondary=>:sturdy,:hidden=>:weak_armor}
  ABILITY_SPECIES_SLOTS_V024[:skiploom] = {:primary=>:chlorophyll,:secondary=>:leaf_guard,:hidden=>:infiltrator}
  ABILITY_SPECIES_SLOTS_V024[:skitty] = {:primary=>:cute_charm,:secondary=>:normalize,:hidden=>:wonder_skin}
  ABILITY_SPECIES_SLOTS_V024[:skorupi] = {:primary=>:battle_armor,:secondary=>:sniper,:hidden=>:keen_eye}
  ABILITY_SPECIES_SLOTS_V024[:skuntank] = {:primary=>:stench,:secondary=>:aftermath,:hidden=>:keen_eye}
  ABILITY_SPECIES_SLOTS_V024[:slaking] = {:primary=>:truant,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:slakoth] = {:primary=>:truant,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:slowbro] = {:primary=>:oblivious,:secondary=>:own_tempo,:hidden=>:regenerator}
  ABILITY_SPECIES_SLOTS_V024[:slowking] = {:primary=>:oblivious,:secondary=>:own_tempo,:hidden=>:regenerator}
  ABILITY_SPECIES_SLOTS_V024[:slowpoke] = {:primary=>:oblivious,:secondary=>:own_tempo,:hidden=>:regenerator}
  ABILITY_SPECIES_SLOTS_V024[:slugma] = {:primary=>:magma_armor,:secondary=>:flame_body,:hidden=>:weak_armor}
  ABILITY_SPECIES_SLOTS_V024[:smeargle] = {:primary=>:own_tempo,:secondary=>:technician,:hidden=>:moody}
  ABILITY_SPECIES_SLOTS_V024[:smoochum] = {:primary=>:oblivious,:secondary=>:forewarn,:hidden=>:hydration}
  ABILITY_SPECIES_SLOTS_V024[:sneasel] = {:primary=>:inner_focus,:secondary=>:keen_eye,:hidden=>:pickpocket}
  ABILITY_SPECIES_SLOTS_V024[:snorlax] = {:primary=>:immunity,:secondary=>:thick_fat,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:snorunt] = {:primary=>:inner_focus,:secondary=>:ice_body,:hidden=>:moody}
  ABILITY_SPECIES_SLOTS_V024[:snover] = {:primary=>:snow_warning,:secondary=>nil,:hidden=>:soundproof}
  ABILITY_SPECIES_SLOTS_V024[:snubbull] = {:primary=>:intimidate,:secondary=>:run_away,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:solrock] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:spearow] = {:primary=>:keen_eye,:secondary=>nil,:hidden=>:sniper}
  ABILITY_SPECIES_SLOTS_V024[:spheal] = {:primary=>:thick_fat,:secondary=>:ice_body,:hidden=>:oblivious}
  ABILITY_SPECIES_SLOTS_V024[:spinarak] = {:primary=>:swarm,:secondary=>:insomnia,:hidden=>:sniper}
  ABILITY_SPECIES_SLOTS_V024[:spinda] = {:primary=>:own_tempo,:secondary=>:tangled_feet,:hidden=>:contrary}
  ABILITY_SPECIES_SLOTS_V024[:spiritomb] = {:primary=>:pressure,:secondary=>nil,:hidden=>:infiltrator}
  ABILITY_SPECIES_SLOTS_V024[:spoink] = {:primary=>:thick_fat,:secondary=>:own_tempo,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:squirtle] = {:primary=>:torrent,:secondary=>nil,:hidden=>:rain_dish}
  ABILITY_SPECIES_SLOTS_V024[:stantler] = {:primary=>:intimidate,:secondary=>:frisk,:hidden=>:sap_sipper}
  ABILITY_SPECIES_SLOTS_V024[:staraptor] = {:primary=>:intimidate,:secondary=>nil,:hidden=>:reckless}
  ABILITY_SPECIES_SLOTS_V024[:staravia] = {:primary=>:intimidate,:secondary=>nil,:hidden=>:reckless}
  ABILITY_SPECIES_SLOTS_V024[:starly] = {:primary=>:keen_eye,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:starmie] = {:primary=>:illuminate,:secondary=>:natural_cure,:hidden=>:analytic}
  ABILITY_SPECIES_SLOTS_V024[:staryu] = {:primary=>:illuminate,:secondary=>:natural_cure,:hidden=>:analytic}
  ABILITY_SPECIES_SLOTS_V024[:steelix] = {:primary=>:rock_head,:secondary=>:sturdy,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:stunky] = {:primary=>:stench,:secondary=>:aftermath,:hidden=>:keen_eye}
  ABILITY_SPECIES_SLOTS_V024[:sudowoodo] = {:primary=>:sturdy,:secondary=>:rock_head,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:suicune] = {:primary=>:pressure,:secondary=>nil,:hidden=>:water_absorb}
  ABILITY_SPECIES_SLOTS_V024[:sunflora] = {:primary=>:chlorophyll,:secondary=>:solar_power,:hidden=>:early_bird}
  ABILITY_SPECIES_SLOTS_V024[:sunkern] = {:primary=>:chlorophyll,:secondary=>:solar_power,:hidden=>:early_bird}
  ABILITY_SPECIES_SLOTS_V024[:surskit] = {:primary=>:swift_swim,:secondary=>nil,:hidden=>:rain_dish}
  ABILITY_SPECIES_SLOTS_V024[:swablu] = {:primary=>:natural_cure,:secondary=>nil,:hidden=>:cloud_nine}
  ABILITY_SPECIES_SLOTS_V024[:swalot] = {:primary=>:liquid_ooze,:secondary=>:sticky_hold,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:swampert] = {:primary=>:torrent,:secondary=>nil,:hidden=>:damp}
  ABILITY_SPECIES_SLOTS_V024[:swellow] = {:primary=>:guts,:secondary=>nil,:hidden=>:scrappy}
  ABILITY_SPECIES_SLOTS_V024[:swinub] = {:primary=>:oblivious,:secondary=>:snow_cloak,:hidden=>:thick_fat}
  ABILITY_SPECIES_SLOTS_V024[:taillow] = {:primary=>:guts,:secondary=>nil,:hidden=>:scrappy}
  ABILITY_SPECIES_SLOTS_V024[:tangela] = {:primary=>:chlorophyll,:secondary=>:leaf_guard,:hidden=>:regenerator}
  ABILITY_SPECIES_SLOTS_V024[:tangrowth] = {:primary=>:chlorophyll,:secondary=>:leaf_guard,:hidden=>:regenerator}
  ABILITY_SPECIES_SLOTS_V024[:tauros] = {:primary=>:intimidate,:secondary=>:anger_point,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:teddiursa] = {:primary=>:pickup,:secondary=>:quick_feet,:hidden=>:honey_gather}
  ABILITY_SPECIES_SLOTS_V024[:tentacool] = {:primary=>:clear_body,:secondary=>:liquid_ooze,:hidden=>:rain_dish}
  ABILITY_SPECIES_SLOTS_V024[:tentacruel] = {:primary=>:clear_body,:secondary=>:liquid_ooze,:hidden=>:rain_dish}
  ABILITY_SPECIES_SLOTS_V024[:togekiss] = {:primary=>:hustle,:secondary=>:serene_grace,:hidden=>:super_luck}
  ABILITY_SPECIES_SLOTS_V024[:togepi] = {:primary=>:hustle,:secondary=>:serene_grace,:hidden=>:super_luck}
  ABILITY_SPECIES_SLOTS_V024[:togetic] = {:primary=>:hustle,:secondary=>:serene_grace,:hidden=>:super_luck}
  ABILITY_SPECIES_SLOTS_V024[:torchic] = {:primary=>:blaze,:secondary=>nil,:hidden=>:speed_boost}
  ABILITY_SPECIES_SLOTS_V024[:torkoal] = {:primary=>:white_smoke,:secondary=>nil,:hidden=>:shell_armor}
  ABILITY_SPECIES_SLOTS_V024[:torterra] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:shell_armor}
  ABILITY_SPECIES_SLOTS_V024[:totodile] = {:primary=>:torrent,:secondary=>nil,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:toxicroak] = {:primary=>:anticipation,:secondary=>:dry_skin,:hidden=>:poison_touch}
  ABILITY_SPECIES_SLOTS_V024[:trapinch] = {:primary=>:hyper_cutter,:secondary=>:arena_trap,:hidden=>:sheer_force}
  ABILITY_SPECIES_SLOTS_V024[:treecko] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:unburden}
  ABILITY_SPECIES_SLOTS_V024[:tropius] = {:primary=>:chlorophyll,:secondary=>:solar_power,:hidden=>:harvest}
  ABILITY_SPECIES_SLOTS_V024[:turtwig] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:shell_armor}
  ABILITY_SPECIES_SLOTS_V024[:typhlosion] = {:primary=>:blaze,:secondary=>nil,:hidden=>:flash_fire}
  ABILITY_SPECIES_SLOTS_V024[:tyranitar] = {:primary=>:sand_stream,:secondary=>nil,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:tyrogue] = {:primary=>:guts,:secondary=>:steadfast,:hidden=>:vital_spirit}
  ABILITY_SPECIES_SLOTS_V024[:umbreon] = {:primary=>:synchronize,:secondary=>nil,:hidden=>:inner_focus}
  ABILITY_SPECIES_SLOTS_V024[:unown] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:ursaring] = {:primary=>:guts,:secondary=>:quick_feet,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:uxie] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:vaporeon] = {:primary=>:water_absorb,:secondary=>nil,:hidden=>:hydration}
  ABILITY_SPECIES_SLOTS_V024[:venomoth] = {:primary=>:shield_dust,:secondary=>:tinted_lens,:hidden=>:wonder_skin}
  ABILITY_SPECIES_SLOTS_V024[:venonat] = {:primary=>:compound_eyes,:secondary=>:tinted_lens,:hidden=>:run_away}
  ABILITY_SPECIES_SLOTS_V024[:venusaur] = {:primary=>:overgrow,:secondary=>nil,:hidden=>:chlorophyll}
  ABILITY_SPECIES_SLOTS_V024[:vespiquen] = {:primary=>:pressure,:secondary=>nil,:hidden=>:unnerve}
  ABILITY_SPECIES_SLOTS_V024[:vibrava] = {:primary=>:levitate,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:victini] = {:primary=>:victory_star,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:victreebel] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:vigoroth] = {:primary=>:vital_spirit,:secondary=>nil,:hidden=>nil}
  ABILITY_SPECIES_SLOTS_V024[:vileplume] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:effect_spore}
  ABILITY_SPECIES_SLOTS_V024[:volbeat] = {:primary=>:illuminate,:secondary=>:swarm,:hidden=>:prankster}
  ABILITY_SPECIES_SLOTS_V024[:voltorb] = {:primary=>:soundproof,:secondary=>:static,:hidden=>:aftermath}
  ABILITY_SPECIES_SLOTS_V024[:vulpix] = {:primary=>:flash_fire,:secondary=>nil,:hidden=>:drought}
  ABILITY_SPECIES_SLOTS_V024[:wailmer] = {:primary=>:water_veil,:secondary=>:oblivious,:hidden=>:pressure}
  ABILITY_SPECIES_SLOTS_V024[:wailord] = {:primary=>:water_veil,:secondary=>:oblivious,:hidden=>:pressure}
  ABILITY_SPECIES_SLOTS_V024[:walrein] = {:primary=>:thick_fat,:secondary=>:ice_body,:hidden=>:oblivious}
  ABILITY_SPECIES_SLOTS_V024[:wartortle] = {:primary=>:torrent,:secondary=>nil,:hidden=>:rain_dish}
  ABILITY_SPECIES_SLOTS_V024[:weavile] = {:primary=>:pressure,:secondary=>nil,:hidden=>:pickpocket}
  ABILITY_SPECIES_SLOTS_V024[:weedle] = {:primary=>:shield_dust,:secondary=>nil,:hidden=>:run_away}
  ABILITY_SPECIES_SLOTS_V024[:weepinbell] = {:primary=>:chlorophyll,:secondary=>nil,:hidden=>:gluttony}
  ABILITY_SPECIES_SLOTS_V024[:weezing] = {:primary=>:levitate,:secondary=>nil,:hidden=>:stench}
  ABILITY_SPECIES_SLOTS_V024[:whiscash] = {:primary=>:oblivious,:secondary=>:anticipation,:hidden=>:hydration}
  ABILITY_SPECIES_SLOTS_V024[:whismur] = {:primary=>:soundproof,:secondary=>nil,:hidden=>:rattled}
  ABILITY_SPECIES_SLOTS_V024[:wigglytuff] = {:primary=>:cute_charm,:secondary=>nil,:hidden=>:frisk}
  ABILITY_SPECIES_SLOTS_V024[:wingull] = {:primary=>:keen_eye,:secondary=>nil,:hidden=>:rain_dish}
  ABILITY_SPECIES_SLOTS_V024[:wobbuffet] = {:primary=>:shadow_tag,:secondary=>nil,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:wooper] = {:primary=>:damp,:secondary=>:water_absorb,:hidden=>:unaware}
  ABILITY_SPECIES_SLOTS_V024[:wormadam] = {:primary=>:anticipation,:secondary=>nil,:hidden=>:overcoat}
  ABILITY_SPECIES_SLOTS_V024[:wurmple] = {:primary=>:shield_dust,:secondary=>nil,:hidden=>:run_away}
  ABILITY_SPECIES_SLOTS_V024[:wynaut] = {:primary=>:shadow_tag,:secondary=>nil,:hidden=>:telepathy}
  ABILITY_SPECIES_SLOTS_V024[:xatu] = {:primary=>:synchronize,:secondary=>:early_bird,:hidden=>:magic_bounce}
  ABILITY_SPECIES_SLOTS_V024[:yanma] = {:primary=>:speed_boost,:secondary=>:compound_eyes,:hidden=>:frisk}
  ABILITY_SPECIES_SLOTS_V024[:yanmega] = {:primary=>:speed_boost,:secondary=>:tinted_lens,:hidden=>:frisk}
  ABILITY_SPECIES_SLOTS_V024[:zangoose] = {:primary=>:immunity,:secondary=>nil,:hidden=>:toxic_boost}
  ABILITY_SPECIES_SLOTS_V024[:zapdos] = {:primary=>:pressure,:secondary=>nil,:hidden=>:lightning_rod}
  ABILITY_SPECIES_SLOTS_V024[:zigzagoon] = {:primary=>:pickup,:secondary=>:gluttony,:hidden=>:quick_feet}
  ABILITY_SPECIES_SLOTS_V024[:zubat] = {:primary=>:inner_focus,:secondary=>nil,:hidden=>:infiltrator}
end
