#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Accuracy Evasion Data v0.27
# 分類：命中／狀態
#
# 【用途／機制】
# 處理命中率、閃避、能力階級、持續效果、次要效果、速度／行動狀態。
#
# 【怎麼調整】
# 新增狀態時要同時處理附加、免疫、AI 判斷、Popup／戰鬥文字與清除時機。
#
# 【本腳本主要設定常數／資料表】
# - ACCURACY_EVASION_MANIFEST_V027 / ACCURACY_EVASION_MOVE_V027 / ACCURACY_EVASION_ABILITY_V027
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#==============================================================================
# ■ PMD AutoChess Accuracy / Evasion Data v0.27 - GENERATED
#==============================================================================
module PMD_AC
  ACCURACY_EVASION_MANIFEST_V027 = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:previous_mapped_move_count=>201,:new_mapped_move_count=>15,:cumulative_mapped_move_count=>216,:learnset_reference_total=>7005,:new_reference_covered=>216,:cumulative_reference_covered=>3648,:cumulative_coverage_percent=>52.08,:previous_ability_behavior_count=>73,:new_ability_behavior_count=>7,:cumulative_ability_behavior_count=>80,:new_implemented_slot_count=>59,:implemented_slot_count=>673,:total_slot_count=>1193,:implemented_slot_coverage_percent=>56.41,:species_with_any_implemented_ability=>406,:species_coverage_percent=>82.19,:runtime_checksum32=>274332946,:runtime_file=>"Data/PMD_AutoChess_AccuracyEvasion_v027_000.rvdata",:source_commit=>"fb1605aac09064bb34a12a8b790c2b800b4d0550",:historical_overrides=>{:sweet_scent_evasion_stage=>-1,:minimize=>:deferred_gen5_special_damage_semantics,:defog=>:deferred_field_clear_semantics},:notes=>["Canonical accuracy/evasion stages use the Generation V 3-based stage multipliers.","Accuracy checks are applied at canonical move effect resolution after projectile/geometry contact; legacy custom skills remain unchanged.","All non-normal verification modes default canonical accuracy rolls to zero unless the accuracy/evasion verifier supplies explicit boundary rolls.","Never-miss canonical moves and No Guard force perfect projectile tracking where a projectile exists.","Minimize and Defog remain deferred because their Generation V semantics exceed a simple stage change."]}
  ACCURACY_EVASION_MOVE_V027 = {}
  ACCURACY_EVASION_MOVE_V027[:coil] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:coil,:runtime_skill_key=>:mv_coil,:name=>"盤蜷",:name_en=>"Coil",:type=>:poison,:category=>:status,:canonical_power=>0,:accuracy=>nil,:target=>:user,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:vfx_style=>:poison,:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>1},{:type=>:stat_stage,:stat=>:def,:stages=>1},{:type=>:stat_stage,:stat=>:accuracy,:stages=>1}],:secondary_effects=>[],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:global_range=>true}
  ACCURACY_EVASION_MOVE_V027[:double_team] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:double_team,:runtime_skill_key=>:mv_double_team,:name=>"影子分身",:name_en=>"Double Team",:type=>:normal,:category=>:status,:canonical_power=>0,:accuracy=>nil,:target=>:user,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:vfx_style=>:impact,:effects=>[{:type=>:stat_stage,:stat=>:evasion,:stages=>1}],:secondary_effects=>[],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:global_range=>true}
  ACCURACY_EVASION_MOVE_V027[:flash] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:flash,:runtime_skill_key=>:mv_flash,:name=>"閃光",:name_en=>"Flash",:type=>:normal,:category=>:status,:canonical_power=>0,:accuracy=>100,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect,:reflectable],:vfx_style=>:impact,:effects=>[{:type=>:stat_stage,:stat=>:accuracy,:stages=>-1}],:secondary_effects=>[],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:hone_claws] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:hone_claws,:runtime_skill_key=>:mv_hone_claws,:name=>"磨爪",:name_en=>"Hone Claws",:type=>:dark,:category=>:status,:canonical_power=>0,:accuracy=>nil,:target=>:user,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:vfx_style=>:dark,:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>1},{:type=>:stat_stage,:stat=>:accuracy,:stages=>1}],:secondary_effects=>[],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:global_range=>true}
  ACCURACY_EVASION_MOVE_V027[:kinesis] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:kinesis,:runtime_skill_key=>:mv_kinesis,:name=>"折彎湯匙",:name_en=>"Kinesis",:type=>:psychic,:category=>:status,:canonical_power=>0,:accuracy=>80,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect,:reflectable],:vfx_style=>:light,:effects=>[{:type=>:stat_stage,:stat=>:accuracy,:stages=>-1}],:secondary_effects=>[],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:leaf_tornado] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:leaf_tornado,:runtime_skill_key=>:mv_leaf_tornado,:name=>"青草攪拌器",:name_en=>"Leaf Tornado",:type=>:grass,:category=>:special,:canonical_power=>65,:accuracy=>90,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:seed,:effects=>[{:type=>:damage,:power=>65}],:secondary_effects=>[{:group=>0,:type=>:stat_stage,:stat=>:accuracy,:stages=>-1,:chance=>50,:receiver=>:target}],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:mirror_shot] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:mirror_shot,:runtime_skill_key=>:mv_mirror_shot,:name=>"鏡光射擊",:name_en=>"Mirror Shot",:type=>:steel,:category=>:special,:canonical_power=>65,:accuracy=>85,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:light,:effects=>[{:type=>:damage,:power=>65}],:secondary_effects=>[{:group=>0,:type=>:stat_stage,:stat=>:accuracy,:stages=>-1,:chance=>30,:receiver=>:target}],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:mud_bomb] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:mud_bomb,:runtime_skill_key=>:mv_mud_bomb,:name=>"泥巴炸彈",:name_en=>"Mud Bomb",:type=>:ground,:category=>:special,:canonical_power=>65,:accuracy=>85,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:ballistics,:mirror,:protect],:vfx_style=>:impact,:effects=>[{:type=>:damage,:power=>65}],:secondary_effects=>[{:group=>0,:type=>:stat_stage,:stat=>:accuracy,:stages=>-1,:chance=>30,:receiver=>:target}],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:mud_slap] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:mud_slap,:runtime_skill_key=>:mv_mud_slap,:name=>"擲泥",:name_en=>"Mud-Slap",:type=>:ground,:category=>:special,:canonical_power=>20,:accuracy=>100,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>30,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:impact,:effects=>[{:type=>:damage,:power=>20}],:secondary_effects=>[{:group=>0,:type=>:stat_stage,:stat=>:accuracy,:stages=>-1,:chance=>100,:receiver=>:target}],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:muddy_water] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:muddy_water,:runtime_skill_key=>:mv_muddy_water,:name=>"濁流",:name_en=>"Muddy Water",:type=>:water,:category=>:special,:canonical_power=>95,:accuracy=>85,:target=>:all_opponents,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>55,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:non_sky_battle,:protect],:vfx_style=>:water,:effects=>[{:type=>:damage,:power=>95}],:secondary_effects=>[{:group=>0,:type=>:stat_stage,:stat=>:accuracy,:stages=>-1,:chance=>30,:receiver=>:target}],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>260,:radius=>999,:global_direct=>true}
  ACCURACY_EVASION_MOVE_V027[:night_daze] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:night_daze,:runtime_skill_key=>:mv_night_daze,:name=>"暗黑爆破",:name_en=>"Night Daze",:type=>:dark,:category=>:special,:canonical_power=>85,:accuracy=>95,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect],:vfx_style=>:dark,:effects=>[{:type=>:damage,:power=>85}],:secondary_effects=>[{:group=>0,:type=>:stat_stage,:stat=>:accuracy,:stages=>-1,:chance=>40,:receiver=>:target}],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:octazooka] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:octazooka,:runtime_skill_key=>:mv_octazooka,:name=>"章魚桶炮",:name_en=>"Octazooka",:type=>:water,:category=>:special,:canonical_power=>65,:accuracy=>85,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>45,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:ballistics,:mirror,:protect],:vfx_style=>:water,:effects=>[{:type=>:damage,:power=>65}],:secondary_effects=>[{:group=>0,:type=>:stat_stage,:stat=>:accuracy,:stages=>-1,:chance=>50,:receiver=>:target}],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:sand_attack] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:sand_attack,:runtime_skill_key=>:mv_sand_attack,:name=>"潑沙",:name_en=>"Sand Attack",:type=>:ground,:category=>:status,:canonical_power=>0,:accuracy=>100,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect,:reflectable],:vfx_style=>:impact,:effects=>[{:type=>:stat_stage,:stat=>:accuracy,:stages=>-1}],:secondary_effects=>[],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:smokescreen] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:smokescreen,:runtime_skill_key=>:mv_smokescreen,:name=>"煙幕",:name_en=>"Smokescreen",:type=>:normal,:category=>:status,:canonical_power=>0,:accuracy=>100,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect,:reflectable],:vfx_style=>:impact,:effects=>[{:type=>:stat_stage,:stat=>:accuracy,:stages=>-1}],:secondary_effects=>[],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:projectile_tracking=>:strong}
  ACCURACY_EVASION_MOVE_V027[:sweet_scent] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:sweet_scent,:runtime_skill_key=>:mv_sweet_scent,:name=>"甜甜香氣",:name_en=>"Sweet Scent",:type=>:normal,:category=>:status,:canonical_power=>0,:accuracy=>100,:target=>:all_opponents,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:mirror,:protect,:reflectable],:vfx_style=>:impact,:effects=>[{:type=>:stat_stage,:stat=>:evasion,:stages=>-1}],:secondary_effects=>[],:behavior_status=>:implemented_accuracy_evasion_v027,:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>260,:radius=>999,:global_direct=>true}
  ACCURACY_EVASION_ABILITY_V027 = {}
  ACCURACY_EVASION_ABILITY_V027[:compound_eyes] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:compound_eyes,:behavior_status=>:implemented_accuracy_evasion_v027,:kind=>:accuracy_multiplier,:num=>13,:den=>10}
  ACCURACY_EVASION_ABILITY_V027[:hustle] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:hustle,:behavior_status=>:implemented_accuracy_evasion_v027,:kind=>:hustle,:atk_num=>3,:atk_den=>2,:accuracy_num=>4,:accuracy_den=>5,:physical_only=>true}
  ACCURACY_EVASION_ABILITY_V027[:keen_eye] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:keen_eye,:behavior_status=>:implemented_accuracy_evasion_v027,:kind=>:stat_drop_immunity,:stats=>[:accuracy]}
  ACCURACY_EVASION_ABILITY_V027[:moody] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:moody,:behavior_status=>:implemented_accuracy_evasion_v027,:kind=>:turn_end_random_stages,:up_stages=>2,:down_stages=>-1,:stats=>[:atk,:def,:spatk,:spdef,:speed,:accuracy,:evasion]}
  ACCURACY_EVASION_ABILITY_V027[:no_guard] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:no_guard,:behavior_status=>:implemented_accuracy_evasion_v027,:kind=>:no_guard}
  ACCURACY_EVASION_ABILITY_V027[:tangled_feet] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:tangled_feet,:behavior_status=>:implemented_accuracy_evasion_v027,:kind=>:confused_evasion_multiplier,:num=>2,:den=>1}
  ACCURACY_EVASION_ABILITY_V027[:victory_star] = {:schema_version=>"1.0",:content_version=>"0.27.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:victory_star,:behavior_status=>:implemented_accuracy_evasion_v027,:kind=>:team_accuracy_multiplier,:num=>11,:den=>10}
end
