#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Weather Data v0.28
# 分類：天氣
#
# 【用途／機制】
# 定義雨、晴、沙暴、冰雹等天氣的戰鬥效果與／或視覺呈現。
#
# 【怎麼調整】
# 機制天氣使用 v0.28；Rain 視覺目前走 VX Spriteset_Weather，晴天與沙暴保留 overlay/fog。
#
# 【本腳本主要設定常數／資料表】
# - WEATHER_MANIFEST_V028 / WEATHER_MOVE_V028 / WEATHER_ABILITY_V028
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#==============================================================================
# ■ PMD AutoChess Weather Data v0.28 - GENERATED
#==============================================================================
module PMD_AC
  WEATHER_MANIFEST_V028 = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:previous_mapped_move_count=>216,:new_mapped_move_count=>6,:cumulative_mapped_move_count=>222,:learnset_reference_total=>7005,:new_reference_covered=>106,:cumulative_reference_covered=>3754,:cumulative_coverage_percent=>53.59,:previous_ability_behavior_count=>80,:new_ability_behavior_count=>19,:cumulative_ability_behavior_count=>99,:new_implemented_slot_count=>167,:implemented_slot_count=>840,:total_slot_count=>1193,:implemented_slot_coverage_percent=>70.41,:species_with_any_implemented_ability=>451,:species_coverage_percent=>91.3,:runtime_checksum32=>926552623,:runtime_file=>"Data/PMD_AutoChess_Weather_v028_000.rvdata",:weather_turn_frames=>60,:move_weather_turns=>5,:ability_weather_permanent=>true,:source_commit=>"fb1605aac09064bb34a12a8b790c2b800b4d0550",:deferred=>["solar_beam_charge_semantics","forecast_form_change","flower_gift_form_and_partner_buff","weather_rocks_item_extension"]}
  WEATHER_MOVE_V028 = {}
  WEATHER_MOVE_V028[:growth] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:growth,:runtime_skill_key=>:mv_growth,:name=>"生長",:name_en=>"Growth",:type=>:normal,:category=>:status,:canonical_power=>0,:accuracy=>nil,:target=>:user,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:snatch],:vfx_style=>:impact,:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>1},{:type=>:stat_stage,:stat=>:spatk,:stages=>1}],:secondary_effects=>[],:behavior_status=>:implemented_weather_v028,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:sun_stages=>2,:global_range=>true}
  WEATHER_MOVE_V028[:hail] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:hail,:runtime_skill_key=>:mv_hail,:name=>"冰雹",:name_en=>"Hail",:type=>:ice,:category=>:status,:canonical_power=>0,:accuracy=>nil,:target=>:entire_field,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[],:vfx_style=>:light,:effects=>[{:type=>:set_weather,:weather=>:hail,:turns=>5}],:secondary_effects=>[],:behavior_status=>:implemented_weather_v028,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:global_range=>true}
  WEATHER_MOVE_V028[:rain_dance] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:rain_dance,:runtime_skill_key=>:mv_rain_dance,:name=>"求雨",:name_en=>"Rain Dance",:type=>:water,:category=>:status,:canonical_power=>0,:accuracy=>nil,:target=>:entire_field,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[],:vfx_style=>:water,:effects=>[{:type=>:set_weather,:weather=>:rain,:turns=>5}],:secondary_effects=>[],:behavior_status=>:implemented_weather_v028,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:global_range=>true}
  WEATHER_MOVE_V028[:sandstorm] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:sandstorm,:runtime_skill_key=>:mv_sandstorm,:name=>"沙暴",:name_en=>"Sandstorm",:type=>:rock,:category=>:status,:canonical_power=>0,:accuracy=>nil,:target=>:entire_field,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[],:vfx_style=>:impact,:effects=>[{:type=>:set_weather,:weather=>:sandstorm,:turns=>5}],:secondary_effects=>[],:behavior_status=>:implemented_weather_v028,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:global_range=>true}
  WEATHER_MOVE_V028[:sunny_day] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:sunny_day,:runtime_skill_key=>:mv_sunny_day,:name=>"大晴天",:name_en=>"Sunny Day",:type=>:fire,:category=>:status,:canonical_power=>0,:accuracy=>nil,:target=>:entire_field,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>50,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[],:vfx_style=>:fire,:effects=>[{:type=>:set_weather,:weather=>:sun,:turns=>5}],:secondary_effects=>[],:behavior_status=>:implemented_weather_v028,:target_type=>:self,:policy=>:current_target,:delivery=>:instant,:range_px=>0,:global_range=>true}
  WEATHER_MOVE_V028[:weather_ball] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:move_key=>:weather_ball,:runtime_skill_key=>:mv_weather_ball,:name=>"氣象球",:name_en=>"Weather Ball",:type=>:normal,:category=>:special,:canonical_power=>50,:accuracy=>100,:target=>:selected_pokemon,:contact=>false,:pulse=>false,:sound=>false,:energy_cost_hint=>40,:energy_runtime_mode=>:full_bar_v015,:source_move_flags=>[:ballistics,:mirror,:protect],:vfx_style=>:impact,:effects=>[{:type=>:damage,:power=>50}],:secondary_effects=>[],:behavior_status=>:implemented_weather_v028,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230,:dynamic_weather_ball=>true,:projectile_tracking=>:strong}
  WEATHER_ABILITY_V028 = {}
  WEATHER_ABILITY_V028[:air_lock] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:air_lock,:behavior_status=>:implemented_weather_v028,:kind=>:weather_suppression}
  WEATHER_ABILITY_V028[:chlorophyll] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:chlorophyll,:behavior_status=>:implemented_weather_v028,:kind=>:weather_speed,:weather=>:sun,:num=>2,:den=>1}
  WEATHER_ABILITY_V028[:cloud_nine] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:cloud_nine,:behavior_status=>:implemented_weather_v028,:kind=>:weather_suppression}
  WEATHER_ABILITY_V028[:drizzle] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:drizzle,:behavior_status=>:implemented_weather_v028,:kind=>:entry_weather,:weather=>:rain,:permanent=>true}
  WEATHER_ABILITY_V028[:drought] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:drought,:behavior_status=>:implemented_weather_v028,:kind=>:entry_weather,:weather=>:sun,:permanent=>true}
  WEATHER_ABILITY_V028[:dry_skin] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:dry_skin,:behavior_status=>:implemented_weather_v028,:kind=>:dry_skin,:water_heal_num=>1,:water_heal_den=>4,:fire_num=>5,:fire_den=>4,:rain_heal_num=>1,:rain_heal_den=>8,:sun_damage_num=>1,:sun_damage_den=>8}
  WEATHER_ABILITY_V028[:hydration] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:hydration,:behavior_status=>:implemented_weather_v028,:kind=>:weather_status_cure,:weather=>:rain}
  WEATHER_ABILITY_V028[:ice_body] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:ice_body,:behavior_status=>:implemented_weather_v028,:kind=>:weather_turn_heal,:weather=>:hail,:num=>1,:den=>16}
  WEATHER_ABILITY_V028[:leaf_guard] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:leaf_guard,:behavior_status=>:implemented_weather_v028,:kind=>:weather_status_immunity,:weather=>:sun,:statuses=>[:burn,:poison,:paralysis,:sleep,:freeze]}
  WEATHER_ABILITY_V028[:overcoat] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:overcoat,:behavior_status=>:implemented_weather_v028,:kind=>:weather_damage_immunity}
  WEATHER_ABILITY_V028[:rain_dish] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:rain_dish,:behavior_status=>:implemented_weather_v028,:kind=>:weather_turn_heal,:weather=>:rain,:num=>1,:den=>16}
  WEATHER_ABILITY_V028[:sand_force] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:sand_force,:behavior_status=>:implemented_weather_v028,:kind=>:weather_move_power,:weather=>:sandstorm,:types=>[:rock,:ground,:steel],:num=>13,:den=>10}
  WEATHER_ABILITY_V028[:sand_rush] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:sand_rush,:behavior_status=>:implemented_weather_v028,:kind=>:weather_speed,:weather=>:sandstorm,:num=>2,:den=>1}
  WEATHER_ABILITY_V028[:sand_stream] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:sand_stream,:behavior_status=>:implemented_weather_v028,:kind=>:entry_weather,:weather=>:sandstorm,:permanent=>true}
  WEATHER_ABILITY_V028[:sand_veil] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:sand_veil,:behavior_status=>:implemented_weather_v028,:kind=>:weather_evasion,:weather=>:sandstorm,:accuracy_num=>4,:accuracy_den=>5}
  WEATHER_ABILITY_V028[:snow_cloak] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:snow_cloak,:behavior_status=>:implemented_weather_v028,:kind=>:weather_evasion,:weather=>:hail,:accuracy_num=>4,:accuracy_den=>5}
  WEATHER_ABILITY_V028[:snow_warning] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:snow_warning,:behavior_status=>:implemented_weather_v028,:kind=>:entry_weather,:weather=>:hail,:permanent=>true}
  WEATHER_ABILITY_V028[:solar_power] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:solar_power,:behavior_status=>:implemented_weather_v028,:kind=>:weather_spatk_and_damage,:weather=>:sun,:spatk_num=>3,:spatk_den=>2,:damage_num=>1,:damage_den=>8}
  WEATHER_ABILITY_V028[:swift_swim] = {:schema_version=>"1.0",:content_version=>"0.28.0",:canon_snapshot=>"2026-08-08",:ruleset=>"black_white",:ability_key=>:swift_swim,:behavior_status=>:implemented_weather_v028,:kind=>:weather_speed,:weather=>:rain,:num=>2,:den=>1}
end
