#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Skill Audio Data v0.32
# 分類：音效
#
# 【用途／機制】
# 定義技能音效、Organic Combat SFX 與普攻命中聲。
#
# 【怎麼調整】
# 物理接觸起手通常保持安靜，聲音主要放在飛行／命中；避免 Tone/UI/Energy/Magic 類電子音。
#
# 【本腳本主要設定常數／資料表】
# - SKILL_AUDIO_CATEGORY_POOLS_V032 / SKILL_AUDIO_TYPE_V032 / SKILL_AUDIO_MOVE_V032 / SKILL_AUDIO_SPECIALS_V032
# - SKILL_FX_CLEANUP_V032 / SKILL_AUDIO_MANIFEST_V032
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#==============================================================================
# ■ PMD AutoChess Skill Audio Data v0.32
#    Pokemon DS SFX Library integration + cleaned SkillFX manifest
#==============================================================================
module PMD_AC
  SKILL_AUDIO_CATEGORY_POOLS_V032 = {
    :ambient_stream => ["PMD_SFX_Library/Pokemon_Ranger/Ambient_Stream/RGR_Ambient_Stream_001","PMD_SFX_Library/Pokemon_Ranger/Ambient_Stream/RGR_Ambient_Stream_002"],
    :crackle_burst => ["PMD_SFX_Library/Pokemon_Ranger/Crackle_Burst/RGR_Crackle_Burst_001","PMD_SFX_Library/Pokemon_Ranger/Crackle_Burst/RGR_Crackle_Burst_003","PMD_SFX_Library/Pokemon_Ranger/Crackle_Burst/RGR_Crackle_Burst_004"],
    :electric_crackle => ["PMD_SFX_Library/Pokemon_Ranger/Electric_Crackle/RGR_Electric_Crackle_008","PMD_SFX_Library/Pokemon_Ranger/Electric_Crackle/RGR_Electric_Crackle_009","PMD_SFX_Library/Pokemon_Ranger/Electric_Crackle/RGR_Electric_Crackle_002"],
    :electric_sweep => ["PMD_SFX_Library/Pokemon_Ranger/Electric_Sweep/RGR_Electric_Sweep_001","PMD_SFX_Library/Pokemon_Ranger/Electric_Sweep/RGR_Electric_Sweep_003","PMD_SFX_Library/Pokemon_Ranger/Electric_Sweep/RGR_Electric_Sweep_002"],
    :electric_zap => ["PMD_SFX_Library/PMD_Blue_Rescue_Team/Electric_Zap/PMD_Electric_Zap_003","PMD_SFX_Library/PMD_Blue_Rescue_Team/Electric_Zap/PMD_Electric_Zap_002","PMD_SFX_Library/PMD_Blue_Rescue_Team/Electric_Zap/PMD_Electric_Zap_001"],
    :energy_beam => ["PMD_SFX_Library/Pokemon_Ranger/Energy_Beam/RGR_Energy_Beam_004","PMD_SFX_Library/Pokemon_Ranger/Energy_Beam/RGR_Energy_Beam_001","PMD_SFX_Library/Pokemon_Ranger/Energy_Beam/RGR_Energy_Beam_005"],
    :energy_charge => ["PMD_SFX_Library/Pokemon_Ranger/Energy_Charge/RGR_Energy_Charge_007","PMD_SFX_Library/Pokemon_Ranger/Energy_Charge/RGR_Energy_Charge_003","PMD_SFX_Library/Pokemon_Ranger/Energy_Charge/RGR_Energy_Charge_001"],
    :energy_rise => ["PMD_SFX_Library/Pokemon_Ranger/Energy_Rise/RGR_Energy_Rise_002","PMD_SFX_Library/Pokemon_Ranger/Energy_Rise/RGR_Energy_Rise_001","PMD_SFX_Library/Pokemon_Ranger/Energy_Rise/RGR_Energy_Rise_004"],
    :explosion_burst => ["PMD_SFX_Library/Pokemon_Ranger/Explosion_Burst/RGR_Explosion_Burst_001","PMD_SFX_Library/Pokemon_Ranger/Explosion_Burst/RGR_Explosion_Burst_006","PMD_SFX_Library/Pokemon_Ranger/Explosion_Burst/RGR_Explosion_Burst_005"],
    :explosion_sharp => ["PMD_SFX_Library/Pokemon_Ranger/Explosion_Sharp/RGR_Explosion_Sharp_007","PMD_SFX_Library/Pokemon_Ranger/Explosion_Sharp/RGR_Explosion_Sharp_003","PMD_SFX_Library/Pokemon_Ranger/Explosion_Sharp/RGR_Explosion_Sharp_001"],
    :impact_burst => ["PMD_SFX_Library/Pokemon_Ranger/Impact_Burst/RGR_Impact_Burst_006","PMD_SFX_Library/Pokemon_Ranger/Impact_Burst/RGR_Impact_Burst_003","PMD_SFX_Library/Pokemon_Ranger/Impact_Burst/RGR_Impact_Burst_008"],
    :impact_heavy => ["PMD_SFX_Library/Pokemon_Ranger/Impact_Heavy/RGR_Impact_Heavy_001","PMD_SFX_Library/Pokemon_Ranger/Impact_Heavy/RGR_Impact_Heavy_003","PMD_SFX_Library/Pokemon_Ranger/Impact_Heavy/RGR_Impact_Heavy_005"],
    :impact_mid => ["PMD_SFX_Library/Pokemon_Ranger/Impact_Mid/RGR_Impact_Mid_003","PMD_SFX_Library/Pokemon_Ranger/Impact_Mid/RGR_Impact_Mid_007","PMD_SFX_Library/Pokemon_Ranger/Impact_Mid/RGR_Impact_Mid_004"],
    :impact_sharp => ["PMD_SFX_Library/Pokemon_Ranger/Impact_Sharp/RGR_Impact_Sharp_010","PMD_SFX_Library/Pokemon_Ranger/Impact_Sharp/RGR_Impact_Sharp_012","PMD_SFX_Library/Pokemon_Ranger/Impact_Sharp/RGR_Impact_Sharp_013"],
    :long_burst => ["PMD_SFX_Library/Pokemon_Ranger/Long_Burst/RGR_Long_Burst_004","PMD_SFX_Library/Pokemon_Ranger/Long_Burst/RGR_Long_Burst_006","PMD_SFX_Library/Pokemon_Ranger/Long_Burst/RGR_Long_Burst_003"],
    :low_impact => ["PMD_SFX_Library/Pokemon_Ranger/Low_Impact/RGR_Low_Impact_002","PMD_SFX_Library/Pokemon_Ranger/Low_Impact/RGR_Low_Impact_004","PMD_SFX_Library/Pokemon_Ranger/Low_Impact/RGR_Low_Impact_001"],
    :low_rumble => ["PMD_SFX_Library/Pokemon_Ranger/Low_Rumble/RGR_Low_Rumble_003","PMD_SFX_Library/Pokemon_Ranger/Low_Rumble/RGR_Low_Rumble_005","PMD_SFX_Library/Pokemon_Ranger/Low_Rumble/RGR_Low_Rumble_002"],
    :low_thump => ["PMD_SFX_Library/Pokemon_Ranger/Low_Thump/RGR_Low_Thump_002","PMD_SFX_Library/Pokemon_Ranger/Low_Thump/RGR_Low_Thump_001"],
    :magic_chime => ["PMD_SFX_Library/Pokemon_Ranger/Magic_Chime/RGR_Magic_Chime_003","PMD_SFX_Library/Pokemon_Ranger/Magic_Chime/RGR_Magic_Chime_002","PMD_SFX_Library/Pokemon_Ranger/Magic_Chime/RGR_Magic_Chime_004"],
    :magic_sustain => ["PMD_SFX_Library/PMD_Blue_Rescue_Team/Magic_Sustain/PMD_Magic_Sustain_001"],
    :noise_hiss => ["PMD_SFX_Library/Pokemon_Ranger/Noise_Hiss/RGR_Noise_Hiss_001","PMD_SFX_Library/Pokemon_Ranger/Noise_Hiss/RGR_Noise_Hiss_003","PMD_SFX_Library/Pokemon_Ranger/Noise_Hiss/RGR_Noise_Hiss_002"],
    :rumble_impact => ["PMD_SFX_Library/Pokemon_Ranger/Rumble_Impact/RGR_Rumble_Impact_003","PMD_SFX_Library/Pokemon_Ranger/Rumble_Impact/RGR_Rumble_Impact_008","PMD_SFX_Library/Pokemon_Ranger/Rumble_Impact/RGR_Rumble_Impact_005"],
    :slash_swish => ["PMD_SFX_Library/Pokemon_Ranger/Slash_Swish/RGR_Slash_Swish_002","PMD_SFX_Library/Pokemon_Ranger/Slash_Swish/RGR_Slash_Swish_003","PMD_SFX_Library/Pokemon_Ranger/Slash_Swish/RGR_Slash_Swish_004"],
    :splash_noise => ["PMD_SFX_Library/Pokemon_Ranger/Splash_Noise/RGR_Splash_Noise_010","PMD_SFX_Library/Pokemon_Ranger/Splash_Noise/RGR_Splash_Noise_013","PMD_SFX_Library/Pokemon_Ranger/Splash_Noise/RGR_Splash_Noise_011"],
    :tone_high_sustain => ["PMD_SFX_Library/PMD_Blue_Rescue_Team/Tone_High_Sustain/PMD_Tone_High_Sustain_001"],
    :tone_low_hum => ["PMD_SFX_Library/Pokemon_Ranger/Tone_Low_Hum/RGR_Tone_Low_Hum_002","PMD_SFX_Library/Pokemon_Ranger/Tone_Low_Hum/RGR_Tone_Low_Hum_003","PMD_SFX_Library/Pokemon_Ranger/Tone_Low_Hum/RGR_Tone_Low_Hum_004"],
    :tone_mid_beep => ["PMD_SFX_Library/Pokemon_Ranger/Tone_Mid_Beep/RGR_Tone_Mid_Beep_003","PMD_SFX_Library/Pokemon_Ranger/Tone_Mid_Beep/RGR_Tone_Mid_Beep_004","PMD_SFX_Library/Pokemon_Ranger/Tone_Mid_Beep/RGR_Tone_Mid_Beep_001"],
    :tone_sustain => ["PMD_SFX_Library/Pokemon_Ranger/Tone_Sustain/RGR_Tone_Sustain_010","PMD_SFX_Library/Pokemon_Ranger/Tone_Sustain/RGR_Tone_Sustain_005","PMD_SFX_Library/Pokemon_Ranger/Tone_Sustain/RGR_Tone_Sustain_001"],
    :water_splash => ["PMD_SFX_Library/Pokemon_Ranger/Water_Splash/RGR_Water_Splash_007","PMD_SFX_Library/Pokemon_Ranger/Water_Splash/RGR_Water_Splash_005","PMD_SFX_Library/Pokemon_Ranger/Water_Splash/RGR_Water_Splash_003"],
    :wind_hiss => ["PMD_SFX_Library/Pokemon_Ranger/Wind_Hiss/RGR_Wind_Hiss_002","PMD_SFX_Library/Pokemon_Ranger/Wind_Hiss/RGR_Wind_Hiss_003","PMD_SFX_Library/Pokemon_Ranger/Wind_Hiss/RGR_Wind_Hiss_004"],
    :wind_whoosh => ["PMD_SFX_Library/Pokemon_Ranger/Wind_Whoosh/RGR_Wind_Whoosh_001","PMD_SFX_Library/Pokemon_Ranger/Wind_Whoosh/RGR_Wind_Whoosh_002","PMD_SFX_Library/PMD_Blue_Rescue_Team/Wind_Whoosh/PMD_Wind_Whoosh_001"],
  }
  SKILL_AUDIO_TYPE_V032 = {
    :normal => {:cast=>:tone_mid_beep,:launch=>:wind_whoosh,:hit=>:impact_mid},
    :fire => {:cast=>:crackle_burst,:launch=>:long_burst,:hit=>:explosion_burst},
    :water => {:cast=>:ambient_stream,:launch=>:splash_noise,:hit=>:water_splash},
    :electric => {:cast=>:energy_charge,:launch=>:electric_sweep,:hit=>:electric_zap},
    :grass => {:cast=>:energy_rise,:launch=>:wind_whoosh,:hit=>:impact_mid},
    :ice => {:cast=>:magic_chime,:launch=>:wind_hiss,:hit=>:impact_sharp},
    :fighting => {:cast=>:low_thump,:launch=>:slash_swish,:hit=>:impact_heavy},
    :poison => {:cast=>:noise_hiss,:launch=>:noise_hiss,:hit=>:impact_mid},
    :ground => {:cast=>:low_rumble,:launch=>:rumble_impact,:hit=>:low_impact},
    :flying => {:cast=>:wind_whoosh,:launch=>:wind_hiss,:hit=>:slash_swish},
    :psychic => {:cast=>:magic_chime,:launch=>:energy_beam,:hit=>:tone_sustain},
    :bug => {:cast=>:noise_hiss,:launch=>:slash_swish,:hit=>:impact_sharp},
    :rock => {:cast=>:low_rumble,:launch=>:rumble_impact,:hit=>:impact_heavy},
    :ghost => {:cast=>:magic_sustain,:launch=>:tone_sustain,:hit=>:impact_burst},
    :dragon => {:cast=>:energy_charge,:launch=>:energy_beam,:hit=>:impact_burst},
    :dark => {:cast=>:tone_low_hum,:launch=>:noise_hiss,:hit=>:impact_heavy},
    :steel => {:cast=>:energy_charge,:launch=>:slash_swish,:hit=>:impact_sharp},
    :fairy => {:cast=>:magic_chime,:launch=>:tone_sustain,:hit=>:magic_chime},
    :sound => {:cast=>:tone_high_sustain,:launch=>:tone_sustain,:hit=>:impact_burst},
  }
  SKILL_AUDIO_MOVE_V032 = {
    :absorb => {:type=>:grass,:category=>:special,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :acid => {:type=>:poison,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:poison,:cast_cat=>:noise_hiss,:launch_cat=>:noise_hiss,:hit_cat=>:impact_mid,:special=>false},
    :acid_armor => {:type=>:poison,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:poison,:cast_cat=>:noise_hiss,:launch_cat=>nil,:hit_cat=>:noise_hiss,:special=>false},
    :acid_spray => {:type=>:poison,:category=>:special,:visual_kind=>:projectile,:audio_style=>:poison,:cast_cat=>:noise_hiss,:launch_cat=>:noise_hiss,:hit_cat=>:impact_mid,:special=>false},
    :aerial_ace => {:type=>:flying,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:flying,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:slash_swish,:special=>false},
    :agility => {:type=>:psychic,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:magic_chime,:special=>false},
    :air_slash => {:type=>:flying,:category=>:special,:visual_kind=>:projectile,:audio_style=>:flying,:cast_cat=>:wind_whoosh,:launch_cat=>:wind_hiss,:hit_cat=>:slash_swish,:special=>false},
    :amnesia => {:type=>:psychic,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:magic_chime,:special=>false},
    :ancient_power => {:type=>:rock,:category=>:special,:visual_kind=>:projectile,:audio_style=>:rock,:cast_cat=>:low_rumble,:launch_cat=>:rumble_impact,:hit_cat=>:impact_heavy,:special=>false},
    :aqua_tail => {:type=>:water,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:water,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:water_splash,:special=>false},
    :astonish => {:type=>:ghost,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:ghost,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_burst,:special=>false},
    :aura_sphere => {:type=>:fighting,:category=>:special,:visual_kind=>:projectile,:audio_style=>:fighting,:cast_cat=>:low_thump,:launch_cat=>:slash_swish,:hit_cat=>:impact_heavy,:special=>false},
    :aurora_beam => {:type=>:ice,:category=>:special,:visual_kind=>:beam,:audio_style=>:ice,:cast_cat=>:magic_chime,:launch_cat=>:wind_hiss,:hit_cat=>:impact_sharp,:special=>false},
    :autotomize => {:type=>:steel,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:steel,:cast_cat=>:energy_charge,:launch_cat=>nil,:hit_cat=>:energy_charge,:special=>false},
    :barrier => {:type=>:psychic,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:magic_chime,:special=>false},
    :bite => {:type=>:dark,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:dark,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :blizzard => {:type=>:ice,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:ice,:cast_cat=>:magic_chime,:launch_cat=>:wind_hiss,:hit_cat=>:impact_sharp,:special=>false},
    :blue_flare => {:type=>:fire,:category=>:special,:visual_kind=>:projectile,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>:long_burst,:hit_cat=>:explosion_burst,:special=>false},
    :body_slam => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :bolt_strike => {:type=>:electric,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:electric,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:electric_zap,:special=>false},
    :bone_club => {:type=>:ground,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:ground,:cast_cat=>nil,:launch_cat=>:rumble_impact,:hit_cat=>:low_impact,:special=>false},
    :brave_bird => {:type=>:flying,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:flying,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:slash_swish,:special=>false},
    :bubble => {:type=>:water,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:water,:cast_cat=>:ambient_stream,:launch_cat=>:splash_noise,:hit_cat=>:water_splash,:special=>false},
    :bubble_beam => {:type=>:water,:category=>:special,:visual_kind=>:projectile,:audio_style=>:water,:cast_cat=>:ambient_stream,:launch_cat=>:splash_noise,:hit_cat=>:water_splash,:special=>false},
    :bulk_up => {:type=>:fighting,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:fighting,:cast_cat=>:low_thump,:launch_cat=>nil,:hit_cat=>:low_thump,:special=>false},
    :calm_mind => {:type=>:psychic,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:magic_chime,:special=>false},
    :charge_beam => {:type=>:electric,:category=>:special,:visual_kind=>:beam,:audio_style=>:electric,:cast_cat=>:energy_charge,:launch_cat=>:electric_sweep,:hit_cat=>:electric_zap,:special=>false},
    :close_combat => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :coil => {:type=>:poison,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:poison,:cast_cat=>:noise_hiss,:launch_cat=>nil,:hit_cat=>:noise_hiss,:special=>false},
    :confuse_ray => {:type=>:ghost,:category=>:status,:visual_kind=>:projectile,:audio_style=>:ghost,:cast_cat=>:magic_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :confusion => {:type=>:psychic,:category=>:special,:visual_kind=>:projectile,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>:energy_beam,:hit_cat=>:tone_sustain,:special=>false},
    :constrict => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :cotton_spore => {:type=>:grass,:category=>:status,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :crunch => {:type=>:dark,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:dark,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :crush_claw => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :dark_pulse => {:type=>:dark,:category=>:special,:visual_kind=>:projectile,:audio_style=>:dark,:cast_cat=>:tone_low_hum,:launch_cat=>:noise_hiss,:hit_cat=>:impact_heavy,:special=>false},
    :dark_void => {:type=>:dark,:category=>:status,:visual_kind=>:area_hit,:audio_style=>:dark,:cast_cat=>:tone_low_hum,:launch_cat=>:noise_hiss,:hit_cat=>:impact_heavy,:special=>false},
    :defense_curl => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :dizzy_punch => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :double_edge => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :double_team => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :draco_meteor => {:type=>:dragon,:category=>:special,:visual_kind=>:projectile,:audio_style=>:dragon,:cast_cat=>:energy_charge,:launch_cat=>:energy_beam,:hit_cat=>:impact_burst,:special=>false},
    :dragon_breath => {:type=>:dragon,:category=>:special,:visual_kind=>:projectile,:audio_style=>:dragon,:cast_cat=>:energy_charge,:launch_cat=>:energy_beam,:hit_cat=>:impact_burst,:special=>false},
    :dragon_claw => {:type=>:dragon,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:dragon,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_burst,:special=>false},
    :dragon_dance => {:type=>:dragon,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:dragon,:cast_cat=>:energy_charge,:launch_cat=>nil,:hit_cat=>:energy_charge,:special=>false},
    :dragon_pulse => {:type=>:dragon,:category=>:special,:visual_kind=>:projectile,:audio_style=>:dragon,:cast_cat=>:energy_charge,:launch_cat=>:energy_beam,:hit_cat=>:impact_burst,:special=>false},
    :dragon_rush => {:type=>:dragon,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:dragon,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_burst,:special=>false},
    :drill_peck => {:type=>:flying,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:flying,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:slash_swish,:special=>false},
    :dynamic_punch => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :earth_power => {:type=>:ground,:category=>:special,:visual_kind=>:projectile,:audio_style=>:ground,:cast_cat=>:low_rumble,:launch_cat=>:rumble_impact,:hit_cat=>:low_impact,:special=>false},
    :egg_bomb => {:type=>:normal,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :electroweb => {:type=>:electric,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:electric,:cast_cat=>:energy_charge,:launch_cat=>:electric_sweep,:hit_cat=>:electric_zap,:special=>false},
    :ember => {:type=>:fire,:category=>:special,:visual_kind=>:projectile,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>:long_burst,:hit_cat=>:explosion_burst,:special=>false},
    :energy_ball => {:type=>:grass,:category=>:special,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :extrasensory => {:type=>:psychic,:category=>:special,:visual_kind=>:projectile,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>:energy_beam,:hit_cat=>:tone_sustain,:special=>false},
    :feint_attack => {:type=>:dark,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:dark,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :fiery_dance => {:type=>:fire,:category=>:special,:visual_kind=>:projectile,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>:long_burst,:hit_cat=>:explosion_burst,:special=>false},
    :fire_blast => {:type=>:fire,:category=>:special,:visual_kind=>:projectile,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>:long_burst,:hit_cat=>:explosion_burst,:special=>false},
    :fire_fang => {:type=>:fire,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fire,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:explosion_burst,:special=>false},
    :fire_punch => {:type=>:fire,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fire,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:explosion_burst,:special=>false},
    :flame_charge => {:type=>:fire,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fire,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:explosion_burst,:special=>false},
    :flamethrower => {:type=>:fire,:category=>:special,:visual_kind=>:beam,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>:long_burst,:hit_cat=>:explosion_burst,:special=>true},
    :flash => {:type=>:normal,:category=>:status,:visual_kind=>:target_hit,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :flash_cannon => {:type=>:steel,:category=>:special,:visual_kind=>:beam,:audio_style=>:steel,:cast_cat=>:energy_charge,:launch_cat=>:slash_swish,:hit_cat=>:impact_sharp,:special=>false},
    :flatter => {:type=>:dark,:category=>:status,:visual_kind=>:projectile,:audio_style=>:dark,:cast_cat=>:tone_low_hum,:launch_cat=>:noise_hiss,:hit_cat=>:impact_heavy,:special=>false},
    :focus_blast => {:type=>:fighting,:category=>:special,:visual_kind=>:projectile,:audio_style=>:fighting,:cast_cat=>:low_thump,:launch_cat=>:slash_swish,:hit_cat=>:impact_heavy,:special=>false},
    :force_palm => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :giga_drain => {:type=>:grass,:category=>:special,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :glaciate => {:type=>:ice,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:ice,:cast_cat=>:magic_chime,:launch_cat=>:wind_hiss,:hit_cat=>:impact_sharp,:special=>false},
    :glare => {:type=>:normal,:category=>:status,:visual_kind=>:target_hit,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :grass_whistle => {:type=>:grass,:category=>:status,:visual_kind=>:projectile,:audio_style=>:sound,:cast_cat=>:tone_high_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :growl => {:type=>:normal,:category=>:status,:visual_kind=>:area_hit,:audio_style=>:sound,:cast_cat=>:tone_high_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :growth => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :gunk_shot => {:type=>:poison,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:poison,:cast_cat=>nil,:launch_cat=>:noise_hiss,:hit_cat=>:impact_mid,:special=>false},
    :gust => {:type=>:flying,:category=>:special,:visual_kind=>:projectile,:audio_style=>:flying,:cast_cat=>:wind_whoosh,:launch_cat=>:wind_hiss,:hit_cat=>:slash_swish,:special=>false},
    :hail => {:type=>:ice,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:ice,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:magic_chime,:special=>false},
    :hammer_arm => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :harden => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :head_smash => {:type=>:rock,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:rock,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :headbutt => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :heal_order => {:type=>:bug,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:bug,:cast_cat=>:noise_hiss,:launch_cat=>nil,:hit_cat=>:noise_hiss,:special=>false},
    :heart_stamp => {:type=>:psychic,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:psychic,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:tone_sustain,:special=>false},
    :heat_wave => {:type=>:fire,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>:long_burst,:hit_cat=>:explosion_burst,:special=>false},
    :hone_claws => {:type=>:dark,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:dark,:cast_cat=>:tone_low_hum,:launch_cat=>nil,:hit_cat=>:tone_low_hum,:special=>false},
    :horn_attack => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :howl => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:sound,:cast_cat=>:tone_high_sustain,:launch_cat=>nil,:hit_cat=>:tone_high_sustain,:special=>false},
    :hurricane => {:type=>:flying,:category=>:special,:visual_kind=>:projectile,:audio_style=>:flying,:cast_cat=>:wind_whoosh,:launch_cat=>:wind_hiss,:hit_cat=>:slash_swish,:special=>false},
    :hydro_pump => {:type=>:water,:category=>:special,:visual_kind=>:beam,:audio_style=>:water,:cast_cat=>:ambient_stream,:launch_cat=>:ambient_stream,:hit_cat=>:water_splash,:special=>true},
    :hyper_fang => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :hyper_voice => {:type=>:normal,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:sound,:cast_cat=>:tone_high_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :hypnosis => {:type=>:psychic,:category=>:status,:visual_kind=>:target_hit,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:tone_sustain,:special=>false},
    :ice_beam => {:type=>:ice,:category=>:special,:visual_kind=>:beam,:audio_style=>:ice,:cast_cat=>:magic_chime,:launch_cat=>:energy_beam,:hit_cat=>:impact_sharp,:special=>true},
    :ice_fang => {:type=>:ice,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:ice,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :ice_punch => {:type=>:ice,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:ice,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :icicle_crash => {:type=>:ice,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:ice,:cast_cat=>nil,:launch_cat=>:wind_hiss,:hit_cat=>:impact_sharp,:special=>false},
    :icy_wind => {:type=>:ice,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:ice,:cast_cat=>:magic_chime,:launch_cat=>:wind_hiss,:hit_cat=>:impact_sharp,:special=>false},
    :inferno => {:type=>:fire,:category=>:special,:visual_kind=>:projectile,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>:long_burst,:hit_cat=>:explosion_burst,:special=>false},
    :iron_defense => {:type=>:steel,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:steel,:cast_cat=>:energy_charge,:launch_cat=>nil,:hit_cat=>:energy_charge,:special=>false},
    :iron_head => {:type=>:steel,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:steel,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :iron_tail => {:type=>:steel,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:steel,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :kinesis => {:type=>:psychic,:category=>:status,:visual_kind=>:target_hit,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:tone_sustain,:special=>false},
    :leaf_storm => {:type=>:grass,:category=>:special,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :leaf_tornado => {:type=>:grass,:category=>:special,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :leech_life => {:type=>:bug,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:bug,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :leer => {:type=>:normal,:category=>:status,:visual_kind=>:area_hit,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :lick => {:type=>:ghost,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:ghost,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_burst,:special=>false},
    :lovely_kiss => {:type=>:normal,:category=>:status,:visual_kind=>:projectile,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :low_sweep => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :luster_purge => {:type=>:psychic,:category=>:special,:visual_kind=>:projectile,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>:energy_beam,:hit_cat=>:tone_sustain,:special=>false},
    :magical_leaf => {:type=>:grass,:category=>:special,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :magnet_bomb => {:type=>:steel,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:steel,:cast_cat=>nil,:launch_cat=>:slash_swish,:hit_cat=>:impact_sharp,:special=>false},
    :meditate => {:type=>:psychic,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:magic_chime,:special=>false},
    :mega_drain => {:type=>:grass,:category=>:special,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :mega_kick => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :mega_punch => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :megahorn => {:type=>:bug,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:bug,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :metal_claw => {:type=>:steel,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:steel,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :meteor_mash => {:type=>:steel,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:steel,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :milk_drink => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :mirror_shot => {:type=>:steel,:category=>:special,:visual_kind=>:projectile,:audio_style=>:steel,:cast_cat=>:energy_charge,:launch_cat=>:slash_swish,:hit_cat=>:impact_sharp,:special=>false},
    :mist_ball => {:type=>:psychic,:category=>:special,:visual_kind=>:projectile,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>:energy_beam,:hit_cat=>:tone_sustain,:special=>false},
    :moonlight => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :morning_sun => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :mud_bomb => {:type=>:ground,:category=>:special,:visual_kind=>:projectile,:audio_style=>:ground,:cast_cat=>:low_rumble,:launch_cat=>:rumble_impact,:hit_cat=>:low_impact,:special=>false},
    :mud_shot => {:type=>:ground,:category=>:special,:visual_kind=>:projectile,:audio_style=>:ground,:cast_cat=>:low_rumble,:launch_cat=>:rumble_impact,:hit_cat=>:low_impact,:special=>false},
    :mud_slap => {:type=>:ground,:category=>:special,:visual_kind=>:projectile,:audio_style=>:ground,:cast_cat=>:low_rumble,:launch_cat=>:rumble_impact,:hit_cat=>:low_impact,:special=>false},
    :muddy_water => {:type=>:water,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:water,:cast_cat=>:ambient_stream,:launch_cat=>:splash_noise,:hit_cat=>:water_splash,:special=>false},
    :nasty_plot => {:type=>:dark,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:dark,:cast_cat=>:tone_low_hum,:launch_cat=>nil,:hit_cat=>:tone_low_hum,:special=>false},
    :needle_arm => {:type=>:grass,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:grass,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :night_daze => {:type=>:dark,:category=>:special,:visual_kind=>:projectile,:audio_style=>:dark,:cast_cat=>:tone_low_hum,:launch_cat=>:noise_hiss,:hit_cat=>:impact_heavy,:special=>false},
    :octazooka => {:type=>:water,:category=>:special,:visual_kind=>:projectile,:audio_style=>:water,:cast_cat=>:ambient_stream,:launch_cat=>:splash_noise,:hit_cat=>:water_splash,:special=>false},
    :ominous_wind => {:type=>:ghost,:category=>:special,:visual_kind=>:projectile,:audio_style=>:ghost,:cast_cat=>:magic_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :overheat => {:type=>:fire,:category=>:special,:visual_kind=>:projectile,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>:long_burst,:hit_cat=>:explosion_burst,:special=>false},
    :peck => {:type=>:flying,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:flying,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:slash_swish,:special=>false},
    :poison_fang => {:type=>:poison,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:poison,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :poison_jab => {:type=>:poison,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:poison,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :poison_sting => {:type=>:poison,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:poison,:cast_cat=>nil,:launch_cat=>:noise_hiss,:hit_cat=>:impact_mid,:special=>false},
    :pound => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :powder_snow => {:type=>:ice,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:ice,:cast_cat=>:magic_chime,:launch_cat=>:wind_hiss,:hit_cat=>:impact_sharp,:special=>false},
    :power_gem => {:type=>:rock,:category=>:special,:visual_kind=>:projectile,:audio_style=>:rock,:cast_cat=>:low_rumble,:launch_cat=>:rumble_impact,:hit_cat=>:impact_heavy,:special=>false},
    :power_whip => {:type=>:grass,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:grass,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :psybeam => {:type=>:psychic,:category=>:special,:visual_kind=>:beam,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>:energy_beam,:hit_cat=>:tone_sustain,:special=>false},
    :psychic => {:type=>:psychic,:category=>:special,:visual_kind=>:projectile,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>:energy_beam,:hit_cat=>:tone_sustain,:special=>false},
    :psycho_boost => {:type=>:psychic,:category=>:special,:visual_kind=>:projectile,:audio_style=>:psychic,:cast_cat=>:magic_chime,:launch_cat=>:energy_beam,:hit_cat=>:tone_sustain,:special=>false},
    :quiver_dance => {:type=>:bug,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:bug,:cast_cat=>:noise_hiss,:launch_cat=>nil,:hit_cat=>:noise_hiss,:special=>false},
    :rain_dance => {:type=>:water,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:water,:cast_cat=>:ambient_stream,:launch_cat=>nil,:hit_cat=>:ambient_stream,:special=>false},
    :razor_shell => {:type=>:water,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:water,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:water_splash,:special=>false},
    :recover => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:magic_chime,:launch_cat=>nil,:hit_cat=>:tone_sustain,:special=>true},
    :rock_climb => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :rock_polish => {:type=>:rock,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:rock,:cast_cat=>:low_rumble,:launch_cat=>nil,:hit_cat=>:low_rumble,:special=>false},
    :rock_slide => {:type=>:rock,:category=>:physical,:visual_kind=>:area_hit,:audio_style=>:rock,:cast_cat=>nil,:launch_cat=>:rumble_impact,:hit_cat=>:impact_heavy,:special=>false},
    :rock_smash => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :rock_throw => {:type=>:rock,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:rock,:cast_cat=>nil,:launch_cat=>:wind_whoosh,:hit_cat=>:rumble_impact,:special=>true},
    :rock_tomb => {:type=>:rock,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:rock,:cast_cat=>nil,:launch_cat=>:rumble_impact,:hit_cat=>:impact_heavy,:special=>false},
    :rolling_kick => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :sand_attack => {:type=>:ground,:category=>:status,:visual_kind=>:projectile,:audio_style=>:ground,:cast_cat=>:low_rumble,:launch_cat=>:rumble_impact,:hit_cat=>:low_impact,:special=>false},
    :sandstorm => {:type=>:rock,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:rock,:cast_cat=>:low_rumble,:launch_cat=>nil,:hit_cat=>:low_rumble,:special=>false},
    :scary_face => {:type=>:normal,:category=>:status,:visual_kind=>:projectile,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :scratch => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :screech => {:type=>:normal,:category=>:status,:visual_kind=>:target_hit,:audio_style=>:sound,:cast_cat=>:tone_high_sustain,:launch_cat=>nil,:hit_cat=>:tone_high_sustain,:special=>true},
    :seed_bomb => {:type=>:grass,:category=>:physical,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>nil,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :seed_flare => {:type=>:grass,:category=>:special,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :shadow_ball => {:type=>:ghost,:category=>:special,:visual_kind=>:projectile,:audio_style=>:ghost,:cast_cat=>:magic_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :shadow_punch => {:type=>:ghost,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:ghost,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_burst,:special=>false},
    :shell_smash => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :shift_gear => {:type=>:steel,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:steel,:cast_cat=>:energy_charge,:launch_cat=>nil,:hit_cat=>:energy_charge,:special=>false},
    :shock_wave => {:type=>:electric,:category=>:special,:visual_kind=>:beam,:audio_style=>:electric,:cast_cat=>:energy_charge,:launch_cat=>:electric_sweep,:hit_cat=>:electric_zap,:special=>false},
    :signal_beam => {:type=>:bug,:category=>:special,:visual_kind=>:beam,:audio_style=>:bug,:cast_cat=>:noise_hiss,:launch_cat=>:slash_swish,:hit_cat=>:impact_sharp,:special=>false},
    :silver_wind => {:type=>:bug,:category=>:special,:visual_kind=>:projectile,:audio_style=>:bug,:cast_cat=>:noise_hiss,:launch_cat=>:slash_swish,:hit_cat=>:impact_sharp,:special=>false},
    :sing => {:type=>:normal,:category=>:status,:visual_kind=>:projectile,:audio_style=>:sound,:cast_cat=>:tone_high_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :slack_off => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :slam => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :sleep_powder => {:type=>:grass,:category=>:status,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :sludge => {:type=>:poison,:category=>:special,:visual_kind=>:projectile,:audio_style=>:poison,:cast_cat=>:noise_hiss,:launch_cat=>:noise_hiss,:hit_cat=>:impact_mid,:special=>false},
    :sludge_bomb => {:type=>:poison,:category=>:special,:visual_kind=>:projectile,:audio_style=>:poison,:cast_cat=>:noise_hiss,:launch_cat=>:noise_hiss,:hit_cat=>:impact_mid,:special=>false},
    :smog => {:type=>:poison,:category=>:special,:visual_kind=>:projectile,:audio_style=>:poison,:cast_cat=>:noise_hiss,:launch_cat=>:noise_hiss,:hit_cat=>:impact_mid,:special=>false},
    :smokescreen => {:type=>:normal,:category=>:status,:visual_kind=>:projectile,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :snarl => {:type=>:dark,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:sound,:cast_cat=>:tone_high_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :soft_boiled => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :spark => {:type=>:electric,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:electric,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:electric_zap,:special=>false},
    :spore => {:type=>:grass,:category=>:status,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :steamroller => {:type=>:bug,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:bug,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :steel_wing => {:type=>:steel,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:steel,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :stomp => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :string_shot => {:type=>:bug,:category=>:status,:visual_kind=>:area_hit,:audio_style=>:bug,:cast_cat=>:noise_hiss,:launch_cat=>:slash_swish,:hit_cat=>:impact_sharp,:special=>false},
    :struggle_bug => {:type=>:bug,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:bug,:cast_cat=>:noise_hiss,:launch_cat=>:slash_swish,:hit_cat=>:impact_sharp,:special=>false},
    :stun_spore => {:type=>:grass,:category=>:status,:visual_kind=>:projectile,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :submission => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :substitute => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>nil,:hit_cat=>:tone_mid_beep,:special=>false},
    :sunny_day => {:type=>:fire,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:fire,:cast_cat=>:crackle_burst,:launch_cat=>nil,:hit_cat=>:crackle_burst,:special=>false},
    :superpower => {:type=>:fighting,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fighting,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_heavy,:special=>false},
    :supersonic => {:type=>:normal,:category=>:status,:visual_kind=>:projectile,:audio_style=>:sound,:cast_cat=>:tone_high_sustain,:launch_cat=>:tone_sustain,:hit_cat=>:impact_burst,:special=>false},
    :swagger => {:type=>:normal,:category=>:status,:visual_kind=>:projectile,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :sweet_kiss => {:type=>:normal,:category=>:status,:visual_kind=>:projectile,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :sweet_scent => {:type=>:normal,:category=>:status,:visual_kind=>:area_hit,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :swift => {:type=>:normal,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :swords_dance => {:type=>:normal,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:normal,:cast_cat=>:slash_swish,:launch_cat=>nil,:hit_cat=>:slash_swish,:special=>true},
    :synthesis => {:type=>:grass,:category=>:status,:visual_kind=>:self_fx,:audio_style=>:grass,:cast_cat=>:energy_rise,:launch_cat=>nil,:hit_cat=>:energy_rise,:special=>false},
    :tackle => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :tail_whip => {:type=>:normal,:category=>:status,:visual_kind=>:area_hit,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :take_down => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :thunder => {:type=>:electric,:category=>:special,:visual_kind=>:target_hit,:audio_style=>:electric,:cast_cat=>:energy_charge,:launch_cat=>nil,:hit_cat=>:electric_crackle,:special=>true},
    :thunder_fang => {:type=>:electric,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:electric,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:electric_zap,:special=>false},
    :thunder_punch => {:type=>:electric,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:electric,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:electric_zap,:special=>false},
    :thunder_shock => {:type=>:electric,:category=>:special,:visual_kind=>:projectile,:audio_style=>:electric,:cast_cat=>:energy_charge,:launch_cat=>:electric_sweep,:hit_cat=>:electric_zap,:special=>false},
    :thunder_wave => {:type=>:electric,:category=>:status,:visual_kind=>:projectile,:audio_style=>:electric,:cast_cat=>:energy_charge,:launch_cat=>:electric_sweep,:hit_cat=>:electric_zap,:special=>false},
    :thunderbolt => {:type=>:electric,:category=>:special,:visual_kind=>:beam,:audio_style=>:electric,:cast_cat=>:energy_charge,:launch_cat=>:energy_beam,:hit_cat=>:electric_zap,:special=>true},
    :twister => {:type=>:dragon,:category=>:special,:visual_kind=>:area_hit,:audio_style=>:dragon,:cast_cat=>:energy_charge,:launch_cat=>:energy_beam,:hit_cat=>:impact_burst,:special=>false},
    :v_create => {:type=>:fire,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:fire,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:explosion_burst,:special=>false},
    :vice_grip => {:type=>:normal,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:normal,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :vine_whip => {:type=>:grass,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:grass,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :volt_tackle => {:type=>:electric,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:electric,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:electric_zap,:special=>false},
    :water_gun => {:type=>:water,:category=>:special,:visual_kind=>:beam,:audio_style=>:water,:cast_cat=>nil,:launch_cat=>:splash_noise,:hit_cat=>:water_splash,:special=>true},
    :water_pulse => {:type=>:water,:category=>:special,:visual_kind=>:projectile,:audio_style=>:water,:cast_cat=>:ambient_stream,:launch_cat=>:splash_noise,:hit_cat=>:water_splash,:special=>false},
    :waterfall => {:type=>:water,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:water,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:water_splash,:special=>false},
    :weather_ball => {:type=>:normal,:category=>:special,:visual_kind=>:projectile,:audio_style=>:normal,:cast_cat=>:tone_mid_beep,:launch_cat=>:wind_whoosh,:hit_cat=>:impact_mid,:special=>false},
    :wild_charge => {:type=>:electric,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:electric,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:electric_zap,:special=>false},
    :wing_attack => {:type=>:flying,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:flying,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:slash_swish,:special=>false},
    :wood_hammer => {:type=>:grass,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:grass,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_mid,:special=>false},
    :x_scissor => {:type=>:bug,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:bug,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:impact_sharp,:special=>false},
    :zap_cannon => {:type=>:electric,:category=>:special,:visual_kind=>:projectile,:audio_style=>:electric,:cast_cat=>:energy_charge,:launch_cat=>:electric_sweep,:hit_cat=>:electric_zap,:special=>false},
    :zen_headbutt => {:type=>:psychic,:category=>:physical,:visual_kind=>:contact_hit,:audio_style=>:psychic,:cast_cat=>nil,:launch_cat=>nil,:hit_cat=>:tone_sustain,:special=>false},
  }
  SKILL_AUDIO_SPECIALS_V032 = [:flamethrower,:hydro_pump,:ice_beam,:recover,:rock_throw,:screech,:swords_dance,:thunder,:thunderbolt,:water_gun]
  SKILL_FX_CLEANUP_V032 = {
    :ranger_063 => {:removed=>12,:remaining=>0},
    :ranger_090 => {:removed=>72,:remaining=>0},
    :ranger_097 => {:removed=>48,:remaining=>0},
    :ranger_098 => {:removed=>84,:remaining=>0},
    :ranger_100 => {:removed=>24,:remaining=>0},
    :ranger_101 => {:removed=>36,:remaining=>0},
    :ranger_102 => {:removed=>48,:remaining=>0},
    :ranger_105 => {:removed=>48,:remaining=>0},
    :ranger_107 => {:removed=>48,:remaining=>0},
    :ranger_109 => {:removed=>48,:remaining=>0},
    :ranger_112 => {:removed=>24,:remaining=>0},
    :ranger_113 => {:removed=>48,:remaining=>0},
    :ranger_147 => {:removed=>48,:remaining=>0},
    :ranger_149 => {:removed=>12,:remaining=>0},
    :ranger_153 => {:removed=>96,:remaining=>0},
    :ranger_156 => {:removed=>12,:remaining=>0},
    :ranger_158 => {:removed=>48,:remaining=>0},
    :ranger_160 => {:removed=>48,:remaining=>0},
    :ranger_161 => {:removed=>84,:remaining=>0},
    :ranger_169 => {:removed=>12,:remaining=>0},
    :ranger_170 => {:removed=>12,:remaining=>0},
    :ranger_172 => {:removed=>36,:remaining=>0},
    :ranger_173 => {:removed=>36,:remaining=>0},
    :ranger_174 => {:removed=>48,:remaining=>0},
    :ranger_184 => {:removed=>12,:remaining=>0},
    :ranger_186 => {:removed=>48,:remaining=>0},
    :ranger_189 => {:removed=>60,:remaining=>0},
    :ranger_190 => {:removed=>48,:remaining=>0},
    :ranger_192 => {:removed=>12,:remaining=>0},
    :ranger_193 => {:removed=>12,:remaining=>0},
    :ranger_197 => {:removed=>48,:remaining=>0},
    :ranger_199 => {:removed=>48,:remaining=>0},
    :ranger_201 => {:removed=>48,:remaining=>0},
    :ranger_202 => {:removed=>48,:remaining=>0},
    :ranger_206 => {:removed=>12,:remaining=>0},
    :ranger_208 => {:removed=>36,:remaining=>0},
    :ranger_215 => {:removed=>48,:remaining=>0},
    :ranger_221 => {:removed=>48,:remaining=>0},
    :ranger_222 => {:removed=>48,:remaining=>0},
    :ranger_237 => {:removed=>12,:remaining=>0},
    :ranger_238 => {:removed=>12,:remaining=>0},
    :ranger_239 => {:removed=>12,:remaining=>0},
    :ranger_240 => {:removed=>12,:remaining=>0},
    :ranger_245 => {:removed=>36,:remaining=>0},
  }
  SKILL_AUDIO_MANIFEST_V032 = {
    :schema_version=>"1.0",
    :content_version=>"0.32.0",
    :source=>"Pokemon_DS_SFX_Unique_Library_v1",
    :library_wav_count=>489,
    :skill_sfx_wav_count=>261,
    :creature_cry_wav_count=>228,
    :library_category_count=>39,
    :used_category_pool_count=>31,
    :type_audio_profile_count=>19,
    :runtime_move_total=>222,
    :mapped_move_audio_count=>222,
    :runtime_audio_coverage_percent=>100.0,
    :special_move_profile_count=>10,
    :fx_cleaned_count=>44,
    :fx_removed_magenta_pixels=>1692,
    :fx_remaining_opaque_magenta=>0,
    :runtime_checksum32=>344858530,
  }
end
