#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Move Runtime Coverage Data v0.53
# 分類：技能資料／效果覆蓋
#
# 【用途／機制】
# 定義 MoveDB、招式 Runtime 行為與 7005/7005 learnset reference 覆蓋。
#
# 【怎麼調整】
# 新增招式效果優先放在資料表與共用 foundation；不要為每招複製一份傷害流程。
#
# 【本腳本主要設定常數／資料表】
# - MOVE_COVERAGE_V_MANIFEST_V053 / MOVE_COVERAGE_V_CHECKSUM_TEXT_V053 / MOVE_COVERAGE_V_MOVE_V053 / MOVE_PRESENTATION_V053
# - ITEM_ATTACK_PROFILE_V053 / MOVE_COVERAGE_V_VISUAL_V053 / MOVE_COVERAGE_V_AUDIO_V053
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#===============================================================================
# ■ PMD AutoChess Move Runtime Coverage Data v0.53
#    Expansion V + Functional Presentation Profiles III
#-------------------------------------------------------------------------------
# Additive data over verified v0.52.1. 29 new canonical move keys.
# B/W mechanics are preserved where the current realtime architecture can
# express them exactly. Explicit AutoChess adaptations are tagged in
# :behavior_status rather than silently pretending to be cartridge-exact.
#===============================================================================
module PMD_AC
  MOVE_COVERAGE_V_MANIFEST_V053 = {:schema_version=>"1.0",:content_version=>"0.53.0",:base_version=>"0.52.1",:feature=>"move_runtime_coverage_expansion_v_and_functional_presentation_iii",:new_mapped_move_count=>29,:cumulative_mapped_move_count=>376,:new_reference_covered=>459,:cumulative_reference_covered=>6308,:learnset_reference_total=>7005,:cumulative_coverage_percent=>90.05,:new_move_keys=>[:encore,:baton_pass,:natural_gift,:curse,:uproar,:thrash,:odor_sleuth,:last_resort,:bug_bite,:fling,:stockpile,:mean_look,:heavy_slam,:bide,:worry_seed,:teleport,:swallow,:spit_up,:copycat,:wake_up_slap,:toxic_spikes,:destiny_bond,:spite,:low_kick,:lock_on,:healing_wish,:perish_song,:imprison,:embargo],:presentation_profiles=>29,:timing_profiles=>29,:audio_profiles=>29,:rgss2_compat_scan=>true,:runtime_checksum32=>177831792}
  MOVE_COVERAGE_V_CHECKSUM_TEXT_V053 = "v053|encore|baton_pass|natural_gift|curse|uproar|thrash|odor_sleuth|last_resort|bug_bite|fling|stockpile|mean_look|heavy_slam|bide|worry_seed|teleport|swallow|spit_up|copycat|wake_up_slap|toxic_spikes|destiny_bond|spite|low_kick|lock_on|healing_wish|perish_song|imprison|embargo|459|6308|90.05|presentation29|rgss2_safe|item8|mass_proxy|hazard|repeat|stockpile|copycat|imprison"
  MOVE_COVERAGE_V_MOVE_V053 = {
    :encore=>{:name=>"再來一次",:name_en=>"Encore",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:encore_v053,:duration=>180}],:behavior_status=>:implemented_realtime_v053,:move_key=>:encore,:canonical_move_key=>:encore,:runtime_skill_key=>"mv_encore",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :baton_pass=>{:name=>"接棒",:name_en=>"Baton Pass",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:ally,:policy=>:protect_ally,:delivery=>:instant,:range_px=>180.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:baton_pass_v053}],:behavior_status=>:adapted_field_handoff_v053,:move_key=>:baton_pass,:canonical_move_key=>:baton_pass,:runtime_skill_key=>"mv_baton_pass",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :natural_gift=>{:name=>"自然之恩",:name_en=>"Natural Gift",:type=>:normal,:category=>:physical,:canonical_power=>1,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:grass,:dynamic_power_v053=>:natural_gift,:item_attack_v053=>:natural_gift,:effects=>[{:type=>:damage,:power=>1}],:behavior_status=>:adapted_current_item_set_v053,:move_key=>:natural_gift,:canonical_move_key=>:natural_gift,:runtime_skill_key=>"mv_natural_gift",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :curse=>{:name=>"詛咒",:name_en=>"Curse",:type=>:ghost,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:ghost,:effects=>[{:type=>:curse_v053}],:behavior_status=>:implemented_branch_v053,:move_key=>:curse,:canonical_move_key=>:curse,:runtime_skill_key=>"mv_curse",:move_type=>:ghost,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :uproar=>{:name=>"吵鬧",:name_en=>"Uproar",:type=>:normal,:category=>:special,:canonical_power=>90,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:aoe,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:damage,:power=>90},{:type=>:repeat_move_v053,:turns=>3,:interval=>60,:power=>90,:kind=>:uproar}],:behavior_status=>:implemented_realtime_v053,:move_key=>:uproar,:canonical_move_key=>:uproar,:runtime_skill_key=>"mv_uproar",:move_type=>:normal,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :thrash=>{:name=>"大鬧一番",:name_en=>"Thrash",:type=>:normal,:category=>:physical,:canonical_power=>120,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:force_contact_range=>true,:contact=>true,:effects=>[{:type=>:damage,:power=>120},{:type=>:repeat_move_v053,:turns=>3,:interval=>60,:power=>120,:kind=>:thrash}],:behavior_status=>:implemented_realtime_v053,:move_key=>:thrash,:canonical_move_key=>:thrash,:runtime_skill_key=>"mv_thrash",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :odor_sleuth=>{:name=>"氣味偵測",:name_en=>"Odor Sleuth",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:odor_sleuth_v053,:duration=>180}],:behavior_status=>:implemented_foresight_bridge_v053,:move_key=>:odor_sleuth,:canonical_move_key=>:odor_sleuth,:runtime_skill_key=>"mv_odor_sleuth",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :last_resort=>{:name=>"珍藏",:name_en=>"Last Resort",:type=>:normal,:category=>:physical,:canonical_power=>140,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:force_contact_range=>true,:contact=>true,:effects=>[{:type=>:damage,:power=>140}],:last_resort_v053=>true,:behavior_status=>:implemented_loadout_gate_v053,:move_key=>:last_resort,:canonical_move_key=>:last_resort,:runtime_skill_key=>"mv_last_resort",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :bug_bite=>{:name=>"蟲咬",:name_en=>"Bug Bite",:type=>:bug,:category=>:physical,:canonical_power=>60,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:bug,:force_contact_range=>true,:contact=>true,:effects=>[{:type=>:damage,:power=>60},{:type=>:bug_bite_item_v053}],:behavior_status=>:adapted_current_item_set_v053,:move_key=>:bug_bite,:canonical_move_key=>:bug_bite,:runtime_skill_key=>"mv_bug_bite",:move_type=>:bug,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :fling=>{:name=>"投擲",:name_en=>"Fling",:type=>:dark,:category=>:physical,:canonical_power=>1,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:dark,:dynamic_power_v053=>:fling,:item_attack_v053=>:fling,:effects=>[{:type=>:damage,:power=>1}],:behavior_status=>:adapted_current_item_set_v053,:move_key=>:fling,:canonical_move_key=>:fling,:runtime_skill_key=>"mv_fling",:move_type=>:dark,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :stockpile=>{:name=>"蓄力",:name_en=>"Stockpile",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self_targeted,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:stockpile_v053}],:behavior_status=>:implemented_exact_v053,:move_key=>:stockpile,:canonical_move_key=>:stockpile,:runtime_skill_key=>"mv_stockpile",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :mean_look=>{:name=>"黑色目光",:name_en=>"Mean Look",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:ghost,:effects=>[{:type=>:mean_look_v053,:duration=>300}],:behavior_status=>:implemented_switch_lock_foundation_v053,:move_key=>:mean_look,:canonical_move_key=>:mean_look,:runtime_skill_key=>"mv_mean_look",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :heavy_slam=>{:name=>"重磅衝撞",:name_en=>"Heavy Slam",:type=>:steel,:category=>:physical,:canonical_power=>40,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:steel,:force_contact_range=>true,:contact=>true,:dynamic_power_v053=>:heavy_slam,:effects=>[{:type=>:damage,:power=>40}],:behavior_status=>:adapted_species_mass_proxy_v053,:move_key=>:heavy_slam,:canonical_move_key=>:heavy_slam,:runtime_skill_key=>"mv_heavy_slam",:move_type=>:steel,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :bide=>{:name=>"忍耐",:name_en=>"Bide",:type=>:normal,:category=>:physical,:canonical_power=>nil,:accuracy=>nil,:priority=>1,:target_type=>:self_targeted,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:bide_v053,:duration=>120}],:behavior_status=>:implemented_realtime_v053,:move_key=>:bide,:canonical_move_key=>:bide,:runtime_skill_key=>"mv_bide",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :worry_seed=>{:name=>"煩惱種子",:name_en=>"Worry Seed",:type=>:grass,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:grass,:effects=>[{:type=>:worry_seed_v053,:duration=>300}],:behavior_status=>:implemented_ability_override_v053,:move_key=>:worry_seed,:canonical_move_key=>:worry_seed,:runtime_skill_key=>"mv_worry_seed",:move_type=>:grass,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :teleport=>{:name=>"瞬間移動",:name_en=>"Teleport",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self_targeted,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:psychic,:effects=>[{:type=>:teleport_v053}],:behavior_status=>:adapted_backline_blink_v053,:move_key=>:teleport,:canonical_move_key=>:teleport,:runtime_skill_key=>"mv_teleport",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :swallow=>{:name=>"吞下",:name_en=>"Swallow",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self_targeted,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:swallow_v053}],:behavior_status=>:implemented_stockpile_v053,:move_key=>:swallow,:canonical_move_key=>:swallow,:runtime_skill_key=>"mv_swallow",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :spit_up=>{:name=>"噴出",:name_en=>"Spit Up",:type=>:normal,:category=>:special,:canonical_power=>100,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:normal,:dynamic_power_v053=>:spit_up,:effects=>[{:type=>:damage,:power=>100},{:type=>:spit_up_consume_v053}],:behavior_status=>:implemented_stockpile_v053,:move_key=>:spit_up,:canonical_move_key=>:spit_up,:runtime_skill_key=>"mv_spit_up",:move_type=>:normal,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :copycat=>{:name=>"仿效",:name_en=>"Copycat",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:copycat_marker_v053}],:copycat_v053=>true,:behavior_status=>:implemented_safe_replay_v053,:move_key=>:copycat,:canonical_move_key=>:copycat,:runtime_skill_key=>"mv_copycat",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :wake_up_slap=>{:name=>"喚醒巴掌",:name_en=>"Wake-Up Slap",:type=>:fighting,:category=>:physical,:canonical_power=>60,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fighting,:force_contact_range=>true,:contact=>true,:dynamic_power_v053=>:wake_up_slap,:effects=>[{:type=>:damage,:power=>60},{:type=>:wake_sleep_v053}],:behavior_status=>:implemented_exact_v053,:move_key=>:wake_up_slap,:canonical_move_key=>:wake_up_slap,:runtime_skill_key=>"mv_wake_up_slap",:move_type=>:fighting,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :toxic_spikes=>{:name=>"毒菱",:name_en=>"Toxic Spikes",:type=>:poison,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self_targeted,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:field_disc,:visual_style=>:poison,:effects=>[{:type=>:toxic_spikes_v053,:duration=>600}],:behavior_status=>:adapted_realtime_side_hazard_v053,:move_key=>:toxic_spikes,:canonical_move_key=>:toxic_spikes,:runtime_skill_key=>"mv_toxic_spikes",:move_type=>:poison,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :destiny_bond=>{:name=>"同命",:name_en=>"Destiny Bond",:type=>:ghost,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self_targeted,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:ghost,:effects=>[{:type=>:destiny_bond_v053,:duration=>60}],:behavior_status=>:implemented_realtime_v053,:move_key=>:destiny_bond,:canonical_move_key=>:destiny_bond,:runtime_skill_key=>"mv_destiny_bond",:move_type=>:ghost,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :spite=>{:name=>"怨恨",:name_en=>"Spite",:type=>:ghost,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:ghost,:effects=>[{:type=>:spite_v053,:energy=>40,:disable=>60}],:behavior_status=>:adapted_energy_runtime_v053,:move_key=>:spite,:canonical_move_key=>:spite,:runtime_skill_key=>"mv_spite",:move_type=>:ghost,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :low_kick=>{:name=>"踢倒",:name_en=>"Low Kick",:type=>:fighting,:category=>:physical,:canonical_power=>20,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fighting,:force_contact_range=>true,:contact=>true,:dynamic_power_v053=>:low_kick,:effects=>[{:type=>:damage,:power=>20}],:behavior_status=>:adapted_species_mass_proxy_v053,:move_key=>:low_kick,:canonical_move_key=>:low_kick,:runtime_skill_key=>"mv_low_kick",:move_type=>:fighting,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :lock_on=>{:name=>"鎖定",:name_en=>"Lock-On",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:lock_on_v053,:duration=>180}],:behavior_status=>:implemented_next_hit_v053,:move_key=>:lock_on,:canonical_move_key=>:lock_on,:runtime_skill_key=>"mv_lock_on",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :healing_wish=>{:name=>"治癒之願",:name_en=>"Healing Wish",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:ally,:policy=>:protect_ally,:delivery=>:instant,:range_px=>180.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:healing_wish_v053}],:behavior_status=>:adapted_immediate_ally_transfer_v053,:move_key=>:healing_wish,:canonical_move_key=>:healing_wish,:runtime_skill_key=>"mv_healing_wish",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :perish_song=>{:name=>"滅亡之歌",:name_en=>"Perish Song",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self_targeted,:policy=>:self,:delivery=>:aoe,:range_px=>0.0,:visual_kind=>:field_disc,:visual_style=>:ghost,:effects=>[{:type=>:perish_song_v053,:duration=>180}],:behavior_status=>:implemented_realtime_v053,:move_key=>:perish_song,:canonical_move_key=>:perish_song,:runtime_skill_key=>"mv_perish_song",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :imprison=>{:name=>"封印",:name_en=>"Imprison",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self_targeted,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:psychic,:effects=>[{:type=>:imprison_v053,:duration=>300}],:behavior_status=>:implemented_active_loadout_v053,:move_key=>:imprison,:canonical_move_key=>:imprison,:runtime_skill_key=>"mv_imprison",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :embargo=>{:name=>"查封",:name_en=>"Embargo",:type=>:dark,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:dark,:effects=>[{:type=>:embargo_v053,:duration=>300}],:behavior_status=>:implemented_held_item_suppress_v053,:move_key=>:embargo,:canonical_move_key=>:embargo,:runtime_skill_key=>"mv_embargo",:move_type=>:dark,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
  }
  MOVE_PRESENTATION_V053 = {
    :encore=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:encore_mark,:timing=>:lock_last_move180,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:soft_chime},
    :baton_pass=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:handoff_trail,:timing=>:transfer_stages_then_swap,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:swap},
    :natural_gift=>{:cast_visual=>:grass,:visual_kind=>:projectile,:projectile_visual=>:grass,:impact_visual=>:grass,:persistent_visual=>:item_glint,:timing=>:item_type_projectile,:user_motion=>:shoot,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:projectile},
    :curse=>{:cast_visual=>:ghost,:visual_kind=>:target_hit,:projectile_visual=>:ghost,:impact_visual=>:ghost,:persistent_visual=>:curse_aura,:timing=>:ghost_branch_or_self_buff,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:darken,:sfx_profile=>:ghost_hit},
    :uproar=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:sound_wave,:timing=>:three_pulses60,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:roar},
    :thrash=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:rage_trail,:timing=>:three_hits60_then_confuse,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:impact_heavy},
    :odor_sleuth=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:exposed_marker,:timing=>:foresight180,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:scan},
    :last_resort=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:ready_flash,:timing=>:loadout_gate_then_hit,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:impact_heavy},
    :bug_bite=>{:cast_visual=>:bug,:visual_kind=>:contact_hit,:projectile_visual=>:bug,:impact_visual=>:bug,:persistent_visual=>:item_pop,:timing=>:damage_then_consume_item,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:bite},
    :fling=>{:cast_visual=>:dark,:visual_kind=>:projectile,:projectile_visual=>:dark,:impact_visual=>:dark,:persistent_visual=>:item_trail,:timing=>:item_power_projectile,:user_motion=>:shoot,:target_motion=>:hurt,:screen_effect=>:darken,:sfx_profile=>:projectile},
    :stockpile=>{:cast_visual=>:normal,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:stockpile_orb,:timing=>:stack1_to3,:user_motion=>:charge,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:soft_chime},
    :mean_look=>{:cast_visual=>:ghost,:visual_kind=>:target_hit,:projectile_visual=>:ghost,:impact_visual=>:ghost,:persistent_visual=>:trap_eye,:timing=>:switch_lock300,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:psychic_lock},
    :heavy_slam=>{:cast_visual=>:steel,:visual_kind=>:contact_hit,:projectile_visual=>:steel,:impact_visual=>:steel,:persistent_visual=>:weight_flash,:timing=>:mass_ratio_hit,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:impact_heavy},
    :bide=>{:cast_visual=>:normal,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:bide_aura,:timing=>:store120_then_return2x,:user_motion=>:guard,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:guard},
    :worry_seed=>{:cast_visual=>:grass,:visual_kind=>:projectile,:projectile_visual=>:grass,:impact_visual=>:grass,:persistent_visual=>:insomnia_seed,:timing=>:ability_override300,:user_motion=>:shoot,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:seed},
    :teleport=>{:cast_visual=>:psychic,:visual_kind=>:self_fx,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:warp_ring,:timing=>:blink_backline,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:psychic_copy},
    :swallow=>{:cast_visual=>:normal,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:stockpile_absorb,:timing=>:heal_by_stockpile,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:heal},
    :spit_up=>{:cast_visual=>:normal,:visual_kind=>:projectile,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:stockpile_burst,:timing=>:power100xstack,:user_motion=>:shoot,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:projectile},
    :copycat=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:copy_flash,:timing=>:safe_last_move_replay,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:copy},
    :wake_up_slap=>{:cast_visual=>:fighting,:visual_kind=>:contact_hit,:projectile_visual=>:fighting,:impact_visual=>:fighting,:persistent_visual=>:wake_flash,:timing=>:sleep_double_then_cure,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:fighting_hit},
    :toxic_spikes=>{:cast_visual=>:poison,:visual_kind=>:field_disc,:projectile_visual=>:poison,:impact_visual=>:poison,:persistent_visual=>:toxic_spike_field,:timing=>:side_hazard600,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:fade,:sfx_profile=>:poison},
    :destiny_bond=>{:cast_visual=>:ghost,:visual_kind=>:self_fx,:projectile_visual=>:ghost,:impact_visual=>:ghost,:persistent_visual=>:bond_aura,:timing=>:ko_window60,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:ghost_hit},
    :spite=>{:cast_visual=>:ghost,:visual_kind=>:target_hit,:projectile_visual=>:ghost,:impact_visual=>:ghost,:persistent_visual=>:spite_mark,:timing=>:energy40_disable60,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:ghost_hit},
    :low_kick=>{:cast_visual=>:fighting,:visual_kind=>:contact_hit,:projectile_visual=>:fighting,:impact_visual=>:fighting,:persistent_visual=>:weight_flash,:timing=>:mass_proxy_hit,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:fighting_hit},
    :lock_on=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:lock_reticle,:timing=>:guarantee_next_hit180,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:scan},
    :healing_wish=>{:cast_visual=>:psychic,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:wish_aura,:timing=>:fullheal_cure_then_selfko,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:heal},
    :perish_song=>{:cast_visual=>:ghost,:visual_kind=>:field_disc,:projectile_visual=>:ghost,:impact_visual=>:ghost,:persistent_visual=>:perish_note,:timing=>:all_units180,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:roar},
    :imprison=>{:cast_visual=>:psychic,:visual_kind=>:self_fx,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:imprison_aura,:timing=>:shared_active_moves_block300,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:psychic_lock},
    :embargo=>{:cast_visual=>:dark,:visual_kind=>:target_hit,:projectile_visual=>:dark,:impact_visual=>:dark,:persistent_visual=>:embargo_mark,:timing=>:held_item_off300,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:dark_hit},
  }
  ITEM_ATTACK_PROFILE_V053 = {
    :leftovers=>{:natural_type=>:grass,:natural_power=>60,:fling_power=>10},
    :life_orb=>{:natural_type=>:psychic,:natural_power=>80,:fling_power=>30},
    :focus_sash=>{:natural_type=>:fighting,:natural_power=>80,:fling_power=>10},
    :air_balloon=>{:natural_type=>:flying,:natural_power=>80,:fling_power=>10},
    :eviolite=>{:natural_type=>:rock,:natural_power=>80,:fling_power=>40},
    :muscle_band=>{:natural_type=>:fighting,:natural_power=>70,:fling_power=>10},
    :wise_glasses=>{:natural_type=>:psychic,:natural_power=>70,:fling_power=>10},
    :expert_belt=>{:natural_type=>:fighting,:natural_power=>70,:fling_power=>10}
  }
  MOVE_COVERAGE_V_VISUAL_V053 = {}
  MOVE_COVERAGE_V_AUDIO_V053 = {}
  MOVE_COVERAGE_V_MOVE_V053.each do |k,d|
    p=MOVE_PRESENTATION_V053[k]||{}
    MOVE_COVERAGE_V_VISUAL_V053[k]={:visual_kind=>p[:visual_kind]||d[:visual_kind],:style=>p[:projectile_visual]||d[:visual_style],:hide_logical_projectile=>false,:timing=>p[:timing],:persistent_visual=>p[:persistent_visual]}
    MOVE_COVERAGE_V_AUDIO_V053[k]={:type=>d[:type],:category=>d[:category],:visual_kind=>d[:visual_kind],:audio_style=>d[:visual_style],:cast_cat=>(d[:category]==:status ? :magic_chime : :snap_click),:launch_cat=>([:projectile,:aoe,:beam].include?(d[:delivery]) ? :wind_hiss : nil),:hit_cat=>(d[:category]==:status ? :tone_soft : :impact_mid),:special=>true,:presentation_sfx=>p[:sfx_profile]}
  end
end
