#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Move Runtime Coverage Data v0.54
# 分類：技能資料／效果覆蓋
#
# 【用途／機制】
# 定義 MoveDB、招式 Runtime 行為與 7005/7005 learnset reference 覆蓋。
#
# 【怎麼調整】
# 新增招式效果優先放在資料表與共用 foundation；不要為每招複製一份傷害流程。
#
# 【本腳本主要設定常數／資料表】
# - MOVE_COVERAGE_VI_MANIFEST_V054 / MOVE_COVERAGE_VI_CHECKSUM_TEXT_V054 / MOVE_COVERAGE_VI_MOVE_V054 / MOVE_PRESENTATION_V054
# - HIDDEN_POWER_TYPES_V054 / MOVE_COVERAGE_VI_VISUAL_V054 / MOVE_COVERAGE_VI_AUDIO_V054
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#===============================================================================
# ■ PMD AutoChess Move Runtime Coverage Data v0.54
#    Expansion VI + Functional Presentation Profiles IV + Visual Showcase I
#===============================================================================
module PMD_AC
  MOVE_COVERAGE_VI_MANIFEST_V054 = {:schema_version=>"1.0",:content_version=>"0.54.0",:base_version=>"0.53",:feature=>"move_runtime_coverage_expansion_vi_and_visual_showcase_i",:new_mapped_move_count=>24,:cumulative_mapped_move_count=>400,:new_reference_covered=>233,:cumulative_reference_covered=>6541,:learnset_reference_total=>7005,:cumulative_coverage_percent=>93.38,:new_move_keys=>[:captivate,:me_first,:false_swipe,:sheer_cold,:dream_eater,:synchronoise,:psywave,:sketch,:mirror_move,:gastro_acid,:bestow,:fissure,:soak,:covet,:flame_wheel,:mind_reader,:block,:u_turn,:hidden_power,:heal_block,:petal_dance,:stored_power,:aromatherapy,:punishment],:presentation_profiles=>24,:timing_profiles=>24,:audio_profiles=>24,:visual_showcase_moves=>24,:rgss2_compat_scan=>true,:runtime_checksum32=>1411988110}
  MOVE_COVERAGE_VI_CHECKSUM_TEXT_V054 = "v054|captivate|me_first|false_swipe|sheer_cold|dream_eater|synchronoise|psywave|sketch|mirror_move|gastro_acid|bestow|fissure|soak|covet|flame_wheel|mind_reader|block|u_turn|hidden_power|heal_block|petal_dance|stored_power|aromatherapy|punishment|233|6541|93.38|presentation24|showcase24|rgss2_safe|ohko|replay|type_override|heal_block"
  MOVE_COVERAGE_VI_MOVE_V054 = {
    :captivate=>{:name=>"誘惑",:name_en=>"Captivate",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_area,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:captivate_v054,:spatk=>-2}],:behavior_status=>:adapted_no_gender_runtime_v054,:move_key=>:captivate,:canonical_move_key=>:captivate,:runtime_skill_key=>"mv_captivate",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :me_first=>{:name=>"搶先一步",:name_en=>"Me First",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:me_first_v054}],:behavior_status=>:adapted_realtime_forecast_v054,:move_key=>:me_first,:canonical_move_key=>:me_first,:runtime_skill_key=>"mv_me_first",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :false_swipe=>{:name=>"點到為止",:name_en=>"False Swipe",:type=>:normal,:category=>:physical,:canonical_power=>40,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:force_contact_range=>true,:contact=>true,:false_swipe_v054=>true,:effects=>[{:type=>:damage,:power=>40}],:behavior_status=>:implemented_exact_hp_floor_v054,:move_key=>:false_swipe,:canonical_move_key=>:false_swipe,:runtime_skill_key=>"mv_false_swipe",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :sheer_cold=>{:name=>"絕對零度",:name_en=>"Sheer Cold",:type=>:ice,:category=>:special,:canonical_power=>nil,:accuracy=>30,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:beam,:range_px=>230.0,:visual_kind=>:beam,:visual_style=>:ice,:ohko_v054=>:sheer_cold,:effects=>[{:type=>:ohko_v054,:kind=>:sheer_cold}],:behavior_status=>:implemented_ohko_level_gate_v054,:move_key=>:sheer_cold,:canonical_move_key=>:sheer_cold,:runtime_skill_key=>"mv_sheer_cold",:move_type=>:ice,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :dream_eater=>{:name=>"食夢",:name_en=>"Dream Eater",:type=>:psychic,:category=>:special,:canonical_power=>100,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:beam,:range_px=>230.0,:visual_kind=>:beam,:visual_style=>:psychic,:effects=>[{:type=>:damage,:power=>100},{:type=>:dream_eater_v054,:drain=>0.50}],:behavior_status=>:implemented_sleep_gate_drain_v054,:move_key=>:dream_eater,:canonical_move_key=>:dream_eater,:runtime_skill_key=>"mv_dream_eater",:move_type=>:psychic,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :synchronoise=>{:name=>"同步干擾",:name_en=>"Synchronoise",:type=>:psychic,:category=>:special,:canonical_power=>70,:accuracy=>100,:priority=>0,:target_type=>:area_all_other,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:synchronoise_v054,:power=>70}],:behavior_status=>:adapted_realtime_shared_type_area_v054,:move_key=>:synchronoise,:canonical_move_key=>:synchronoise,:runtime_skill_key=>"mv_synchronoise",:move_type=>:psychic,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :psywave=>{:name=>"精神波",:name_en=>"Psywave",:type=>:psychic,:category=>:special,:canonical_power=>nil,:accuracy=>80,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:psychic,:effects=>[{:type=>:psywave_v054}],:behavior_status=>:implemented_level_random_fixed_v054,:move_key=>:psywave,:canonical_move_key=>:psywave,:runtime_skill_key=>"mv_psywave",:move_type=>:psychic,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :sketch=>{:name=>"寫生",:name_en=>"Sketch",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:sketch_v054}],:behavior_status=>:implemented_instance_move_library_v054,:move_key=>:sketch,:canonical_move_key=>:sketch,:runtime_skill_key=>"mv_sketch",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :mirror_move=>{:name=>"鸚鵡學舌",:name_en=>"Mirror Move",:type=>:flying,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:flying,:effects=>[{:type=>:mirror_move_v054}],:behavior_status=>:adapted_target_last_move_replay_v054,:move_key=>:mirror_move,:canonical_move_key=>:mirror_move,:runtime_skill_key=>"mv_mirror_move",:move_type=>:flying,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :gastro_acid=>{:name=>"胃液",:name_en=>"Gastro Acid",:type=>:poison,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:poison,:effects=>[{:type=>:gastro_acid_v054,:duration=>300}],:behavior_status=>:implemented_ability_suppression_v054,:move_key=>:gastro_acid,:canonical_move_key=>:gastro_acid,:runtime_skill_key=>"mv_gastro_acid",:move_type=>:poison,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :bestow=>{:name=>"傳遞禮物",:name_en=>"Bestow",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:normal,:effects=>[{:type=>:bestow_v054}],:behavior_status=>:implemented_current_item_transfer_v054,:move_key=>:bestow,:canonical_move_key=>:bestow,:runtime_skill_key=>"mv_bestow",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :fissure=>{:name=>"地裂",:name_en=>"Fissure",:type=>:ground,:category=>:physical,:canonical_power=>nil,:accuracy=>30,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:aoe,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:ground,:ohko_v054=>:fissure,:effects=>[{:type=>:ohko_v054,:kind=>:fissure}],:behavior_status=>:implemented_ohko_grounded_gate_v054,:move_key=>:fissure,:canonical_move_key=>:fissure,:runtime_skill_key=>"mv_fissure",:move_type=>:ground,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :soak=>{:name=>"浸水",:name_en=>"Soak",:type=>:water,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:water,:effects=>[{:type=>:soak_v054}],:behavior_status=>:implemented_battle_type_override_v054,:move_key=>:soak,:canonical_move_key=>:soak,:runtime_skill_key=>"mv_soak",:move_type=>:water,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :covet=>{:name=>"渴望",:name_en=>"Covet",:type=>:normal,:category=>:physical,:canonical_power=>60,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:force_contact_range=>true,:contact=>true,:effects=>[{:type=>:damage,:power=>60},{:type=>:covet_v054}],:behavior_status=>:implemented_current_item_steal_v054,:move_key=>:covet,:canonical_move_key=>:covet,:runtime_skill_key=>"mv_covet",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :flame_wheel=>{:name=>"火焰輪",:name_en=>"Flame Wheel",:type=>:fire,:category=>:physical,:canonical_power=>60,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fire,:force_contact_range=>true,:contact=>true,:effects=>[{:type=>:damage,:power=>60},{:type=>:flame_wheel_v054,:burn_chance=>10}],:behavior_status=>:implemented_thaw_secondary_v054,:move_key=>:flame_wheel,:canonical_move_key=>:flame_wheel,:runtime_skill_key=>"mv_flame_wheel",:move_type=>:fire,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :mind_reader=>{:name=>"心之眼",:name_en=>"Mind Reader",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:mind_reader_v054,:duration=>180}],:behavior_status=>:implemented_lock_on_bridge_v054,:move_key=>:mind_reader,:canonical_move_key=>:mind_reader,:runtime_skill_key=>"mv_mind_reader",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :block=>{:name=>"擋路",:name_en=>"Block",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:block_v054,:duration=>300}],:behavior_status=>:implemented_switch_lock_bridge_v054,:move_key=>:block,:canonical_move_key=>:block,:runtime_skill_key=>"mv_block",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :u_turn=>{:name=>"急速折返",:name_en=>"U-turn",:type=>:bug,:category=>:physical,:canonical_power=>70,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:bug,:force_contact_range=>true,:contact=>true,:effects=>[{:type=>:damage,:power=>70},{:type=>:u_turn_v054}],:behavior_status=>:adapted_active_ally_pixel_swap_v054,:move_key=>:u_turn,:canonical_move_key=>:u_turn,:runtime_skill_key=>"mv_u_turn",:move_type=>:bug,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :hidden_power=>{:name=>"覺醒力量",:name_en=>"Hidden Power",:type=>:normal,:category=>:special,:canonical_power=>70,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:normal,:dynamic_power_v054=>:hidden_power,:effects=>[{:type=>:damage,:power=>70}],:behavior_status=>:adapted_uid_type_fixed70_v054,:move_key=>:hidden_power,:canonical_move_key=>:hidden_power,:runtime_skill_key=>"mv_hidden_power",:move_type=>:normal,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :heal_block=>{:name=>"回復封鎖",:name_en=>"Heal Block",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_area,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:heal_block_v054,:duration=>300}],:behavior_status=>:implemented_realtime_heal_gate_v054,:move_key=>:heal_block,:canonical_move_key=>:heal_block,:runtime_skill_key=>"mv_heal_block",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :petal_dance=>{:name=>"花瓣舞",:name_en=>"Petal Dance",:type=>:grass,:category=>:special,:canonical_power=>120,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:aoe,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:grass,:effects=>[{:type=>:damage,:power=>120},{:type=>:repeat_move_v053,:turns=>3,:interval=>60,:power=>120,:kind=>:petal_dance}],:behavior_status=>:implemented_repeat_confuse_bridge_v054,:move_key=>:petal_dance,:canonical_move_key=>:petal_dance,:runtime_skill_key=>"mv_petal_dance",:move_type=>:grass,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :stored_power=>{:name=>"輔助力量",:name_en=>"Stored Power",:type=>:psychic,:category=>:special,:canonical_power=>20,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:beam,:range_px=>230.0,:visual_kind=>:beam,:visual_style=>:psychic,:dynamic_power_v054=>:stored_power,:effects=>[{:type=>:damage,:power=>20}],:behavior_status=>:implemented_positive_stage_power_v054,:move_key=>:stored_power,:canonical_move_key=>:stored_power,:runtime_skill_key=>"mv_stored_power",:move_type=>:psychic,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :aromatherapy=>{:name=>"芳香治療",:name_en=>"Aromatherapy",:type=>:grass,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:aoe,:range_px=>0.0,:visual_kind=>:field_disc,:visual_style=>:grass,:effects=>[{:type=>:aromatherapy_v054}],:behavior_status=>:implemented_team_major_cure_v054,:move_key=>:aromatherapy,:canonical_move_key=>:aromatherapy,:runtime_skill_key=>"mv_aromatherapy",:move_type=>:grass,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :punishment=>{:name=>"懲罰",:name_en=>"Punishment",:type=>:dark,:category=>:physical,:canonical_power=>60,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:dark,:force_contact_range=>true,:contact=>true,:dynamic_power_v054=>:punishment,:effects=>[{:type=>:damage,:power=>60}],:behavior_status=>:implemented_target_positive_stage_power_v054,:move_key=>:punishment,:canonical_move_key=>:punishment,:runtime_skill_key=>"mv_punishment",:move_type=>:dark,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
  }
  MOVE_PRESENTATION_V054 = {
    :captivate=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:heart_wave,:timing=>:enemy_area_spatk_down,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:soft_chime},
    :me_first=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:anticipate_flash,:timing=>:forecast_then_replay_x1_5,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:scan},
    :false_swipe=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:mercy_slash,:timing=>:damage_floor_one,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:slash},
    :sheer_cold=>{:cast_visual=>:ice,:visual_kind=>:beam,:projectile_visual=>:ice,:impact_visual=>:ice,:persistent_visual=>:freeze_zero,:timing=>:ohko_eligible_target,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:ice_hit},
    :dream_eater=>{:cast_visual=>:psychic,:visual_kind=>:beam,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:dream_orb,:timing=>:sleep_gate_damage_drain,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:darken,:sfx_profile=>:psychic_hit},
    :synchronoise=>{:cast_visual=>:psychic,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:sync_wave,:timing=>:shared_type_area,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:psychic_hit},
    :psywave=>{:cast_visual=>:psychic,:visual_kind=>:projectile,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:psy_wave,:timing=>:level_random_fixed,:user_motion=>:shoot,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:projectile},
    :sketch=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:sketch_glyph,:timing=>:instance_library_replace,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:copy},
    :mirror_move=>{:cast_visual=>:flying,:visual_kind=>:target_hit,:projectile_visual=>:flying,:impact_visual=>:flying,:persistent_visual=>:mirror_feather,:timing=>:target_last_move_replay,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:copy},
    :gastro_acid=>{:cast_visual=>:poison,:visual_kind=>:projectile,:projectile_visual=>:poison,:impact_visual=>:poison,:persistent_visual=>:acid_mark,:timing=>:ability_off300,:user_motion=>:shoot,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:poison},
    :bestow=>{:cast_visual=>:normal,:visual_kind=>:projectile,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:gift_orb,:timing=>:held_item_transfer,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:item},
    :fissure=>{:cast_visual=>:ground,:visual_kind=>:target_hit,:projectile_visual=>:ground,:impact_visual=>:ground,:persistent_visual=>:ground_crack,:timing=>:ohko_grounded,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:impact_heavy},
    :soak=>{:cast_visual=>:water,:visual_kind=>:projectile,:projectile_visual=>:water,:impact_visual=>:water,:persistent_visual=>:water_coat,:timing=>:type_water_battle,:user_motion=>:shoot,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:water_hit},
    :covet=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:item_pull,:timing=>:damage_then_steal,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:impact_mid},
    :flame_wheel=>{:cast_visual=>:fire,:visual_kind=>:contact_hit,:projectile_visual=>:fire,:impact_visual=>:fire,:persistent_visual=>:fire_ring,:timing=>:thaw_damage_burn10,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:fire_hit},
    :mind_reader=>{:cast_visual=>:psychic,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:lock_reticle,:timing=>:guarantee_next_hit180,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:scan},
    :block=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:block_wall,:timing=>:switch_lock300,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:guard},
    :u_turn=>{:cast_visual=>:bug,:visual_kind=>:contact_hit,:projectile_visual=>:bug,:impact_visual=>:bug,:persistent_visual=>:return_trail,:timing=>:damage_then_ally_swap,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:bug_hit},
    :hidden_power=>{:cast_visual=>:normal,:visual_kind=>:projectile,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:hidden_orb,:timing=>:uid_type_power70,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:projectile},
    :heal_block=>{:cast_visual=>:psychic,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:heal_lock,:timing=>:enemy_heal_off300,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:psychic_lock},
    :petal_dance=>{:cast_visual=>:grass,:visual_kind=>:target_hit,:projectile_visual=>:grass,:impact_visual=>:grass,:persistent_visual=>:petal_storm,:timing=>:three_hits60_then_confuse,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:grass_hit},
    :stored_power=>{:cast_visual=>:psychic,:visual_kind=>:beam,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:stored_aura,:timing=>:power_by_positive_stages,:user_motion=>:cast,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:psychic_hit},
    :aromatherapy=>{:cast_visual=>:grass,:visual_kind=>:field_disc,:projectile_visual=>:grass,:impact_visual=>:grass,:persistent_visual=>:aroma_field,:timing=>:team_major_cure,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:heal},
    :punishment=>{:cast_visual=>:dark,:visual_kind=>:contact_hit,:projectile_visual=>:dark,:impact_visual=>:dark,:persistent_visual=>:punish_mark,:timing=>:power_by_target_buffs,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:darken,:sfx_profile=>:dark_hit},
  }
  HIDDEN_POWER_TYPES_V054 = [:fighting,:flying,:poison,:ground,:rock,:bug,:ghost,:steel,:fire,:water,:grass,:electric,:psychic,:ice,:dragon,:dark]
  MOVE_COVERAGE_VI_VISUAL_V054 = {}
  MOVE_COVERAGE_VI_AUDIO_V054 = {}
  MOVE_COVERAGE_VI_MOVE_V054.each do |k,d|
    p=MOVE_PRESENTATION_V054[k]||{}
    MOVE_COVERAGE_VI_VISUAL_V054[k]={:visual_kind=>p[:visual_kind]||d[:visual_kind],:style=>p[:projectile_visual]||d[:visual_style],:hide_logical_projectile=>false,:timing=>p[:timing],:persistent_visual=>p[:persistent_visual]}
    MOVE_COVERAGE_VI_AUDIO_V054[k]={:type=>d[:type],:category=>d[:category],:visual_kind=>d[:visual_kind],:audio_style=>d[:visual_style],:cast_cat=>(d[:category]==:status ? :magic_chime : :snap_click),:launch_cat=>([:projectile,:aoe,:beam].include?(d[:delivery]) ? :wind_hiss : nil),:hit_cat=>(d[:category]==:status ? :tone_soft : :impact_mid),:special=>true,:presentation_sfx=>p[:sfx_profile]}
  end
end
