#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Move Runtime Coverage Data v0.56
# 分類：技能資料／效果覆蓋
#
# 【用途／機制】
# 定義 MoveDB、招式 Runtime 行為與 7005/7005 learnset reference 覆蓋。
#
# 【怎麼調整】
# 新增招式效果優先放在資料表與共用 foundation；不要為每招複製一份傷害流程。
#
# 【本腳本主要設定常數／資料表】
# - MOVE_COVERAGE_VII_MANIFEST_V056 / MOVE_COVERAGE_VII_CHECKSUM_TEXT_V056 / MOVE_COVERAGE_VII_MOVE_V056 / MOVE_PRESENTATION_V056
# - MELEE_CAST_SFX_CLEANUP_V056 / MOVE_COVERAGE_VII_VISUAL_V056 / MOVE_COVERAGE_VII_AUDIO_V056
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#===============================================================================
# ■ PMD AutoChess Move Runtime Coverage Data v0.56
#    Expansion VII + Presentation Profile V + Melee Cast SFX Cleanup
#===============================================================================
module PMD_AC
  MOVE_COVERAGE_VII_MANIFEST_V056 = {:schema_version=>"1.0",:content_version=>"0.56.0",:base_version=>"0.55.3",:feature=>"move_runtime_coverage_expansion_vii",:new_mapped_move_count=>30,:cumulative_mapped_move_count=>430,:new_reference_covered=>198,:cumulative_reference_covered=>6739,:learnset_reference_total=>7005,:cumulative_coverage_percent=>96.20,:new_move_keys=>[:snore,:bind,:wish,:tickle,:psycho_shift,:trick,:toxic,:spikes,:metronome,:karate_chop,:horn_drill,:guillotine,:giga_impact,:final_gambit,:belly_drum,:tri_attack,:sky_attack,:razor_wind,:power_swap,:outrage,:mimic,:magic_coat,:guard_swap,:eruption,:acupressure,:venoshock,:super_fang,:stealth_rock,:smack_down,:cotton_guard],:presentation_profiles=>30,:timing_profiles=>30,:audio_profiles=>30,:runtime_checksum32=>952605130}
  MOVE_COVERAGE_VII_CHECKSUM_TEXT_V056 = "v056|snore|bind|wish|tickle|psycho_shift|trick|toxic|spikes|metronome|karate_chop|horn_drill|guillotine|giga_impact|final_gambit|belly_drum|tri_attack|sky_attack|razor_wind|power_swap|outrage|mimic|magic_coat|guard_swap|eruption|acupressure|venoshock|super_fang|stealth_rock|smack_down|cotton_guard|198|6739|96.20|presentation30|melee_cast_cleanup|wish|toxic|hazards|charge|swap|replay"
  MOVE_COVERAGE_VII_MOVE_V056 = {
    :snore=>{:name=>"打鼾",:name_en=>"Snore",:type=>:normal,:category=>:special,:canonical_power=>40,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:beam,:range_px=>210.0,:visual_kind=>:beam,:visual_style=>:normal,:sound=>true,:source_move_flags=>[:sound,:protect],:effects=>[{:type=>:damage,:power=>40},{:type=>:snore_flinch_v056,:chance=>30}],:behavior_status=>:implemented_sleep_only_sound_v056,:move_key=>:snore,:canonical_move_key=>:snore,:runtime_skill_key=>"mv_snore",:move_type=>:normal,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :bind=>{:name=>"綁緊",:name_en=>"Bind",:type=>:normal,:category=>:physical,:canonical_power=>15,:accuracy=>85,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:contact=>true,:force_contact_range=>true,:source_move_flags=>[:contact,:mirror,:protect],:effects=>[{:type=>:damage,:power=>15},{:type=>:bound_v052,:duration=>300,:interval=>60,:ratio=>0.0625,:style=>:normal}],:behavior_status=>:implemented_bound_bridge_v056,:move_key=>:bind,:canonical_move_key=>:bind,:runtime_skill_key=>"mv_bind",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :wish=>{:name=>"祈願",:name_en=>"Wish",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:light,:effects=>[{:type=>:wish_v056,:delay=>120,:heal_ratio=>0.50}],:behavior_status=>:adapted_active_unit_delayed_heal_v056,:move_key=>:wish,:canonical_move_key=>:wish,:runtime_skill_key=>"mv_wish",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :tickle=>{:name=>"搔癢",:name_en=>"Tickle",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>210.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>-1},{:type=>:stat_stage,:stat=>:def,:stages=>-1}],:behavior_status=>:implemented_stat_stage_v056,:move_key=>:tickle,:canonical_move_key=>:tickle,:runtime_skill_key=>"mv_tickle",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :psycho_shift=>{:name=>"精神轉移",:name_en=>"Psycho Shift",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>220.0,:visual_kind=>:projectile,:visual_style=>:psychic,:effects=>[{:type=>:psycho_shift_v056}],:behavior_status=>:implemented_major_status_transfer_v056,:move_key=>:psycho_shift,:canonical_move_key=>:psycho_shift,:runtime_skill_key=>"mv_psycho_shift",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :trick=>{:name=>"戲法",:name_en=>"Trick",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:trick_v056}],:behavior_status=>:implemented_held_item_swap_v056,:move_key=>:trick,:canonical_move_key=>:trick,:runtime_skill_key=>"mv_trick",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :toxic=>{:name=>"劇毒",:name_en=>"Toxic",:type=>:poison,:category=>:status,:canonical_power=>nil,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>220.0,:visual_kind=>:projectile,:visual_style=>:poison,:effects=>[{:type=>:toxic_v056,:duration=>300,:interval=>60}],:behavior_status=>:adapted_realtime_escalating_poison_v056,:move_key=>:toxic,:canonical_move_key=>:toxic,:runtime_skill_key=>"mv_toxic",:move_type=>:poison,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :spikes=>{:name=>"撒菱",:name_en=>"Spikes",:type=>:ground,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:field_disc,:visual_style=>:ground,:effects=>[{:type=>:spikes_v056,:duration=>600}],:behavior_status=>:adapted_realtime_side_hazard_v056,:move_key=>:spikes,:canonical_move_key=>:spikes,:runtime_skill_key=>"mv_spikes",:move_type=>:ground,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :metronome=>{:name=>"揮指",:name_en=>"Metronome",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:metronome_v056}],:behavior_status=>:adapted_safe_random_executable_replay_v056,:move_key=>:metronome,:canonical_move_key=>:metronome,:runtime_skill_key=>"mv_metronome",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :karate_chop=>{:name=>"空手劈",:name_en=>"Karate Chop",:type=>:fighting,:category=>:physical,:canonical_power=>50,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fighting,:contact=>true,:force_contact_range=>true,:source_move_flags=>[:contact,:mirror,:protect],:effects=>[{:type=>:damage,:power=>50,:crit_bonus=>0.075}],:behavior_status=>:implemented_high_crit_v056,:move_key=>:karate_chop,:canonical_move_key=>:karate_chop,:runtime_skill_key=>"mv_karate_chop",:move_type=>:fighting,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :horn_drill=>{:name=>"角鑽",:name_en=>"Horn Drill",:type=>:normal,:category=>:physical,:canonical_power=>nil,:accuracy=>30,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:contact=>true,:force_contact_range=>true,:source_move_flags=>[:contact,:mirror,:protect],:effects=>[{:type=>:ohko_v056,:kind=>:horn_drill}],:behavior_status=>:implemented_ohko_level_gate_v056,:move_key=>:horn_drill,:canonical_move_key=>:horn_drill,:runtime_skill_key=>"mv_horn_drill",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :guillotine=>{:name=>"斷頭鉗",:name_en=>"Guillotine",:type=>:normal,:category=>:physical,:canonical_power=>nil,:accuracy=>30,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:contact=>true,:force_contact_range=>true,:source_move_flags=>[:contact,:mirror,:protect],:effects=>[{:type=>:ohko_v056,:kind=>:guillotine}],:behavior_status=>:implemented_ohko_level_gate_v056,:move_key=>:guillotine,:canonical_move_key=>:guillotine,:runtime_skill_key=>"mv_guillotine",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :giga_impact=>{:name=>"終極衝擊",:name_en=>"Giga Impact",:type=>:normal,:category=>:physical,:canonical_power=>150,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:contact=>true,:force_contact_range=>true,:source_move_flags=>[:contact,:mirror,:protect],:effects=>[{:type=>:damage,:power=>150},{:type=>:recharge_v051,:frames=>60}],:behavior_status=>:implemented_recharge_bridge_v056,:move_key=>:giga_impact,:canonical_move_key=>:giga_impact,:runtime_skill_key=>"mv_giga_impact",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :final_gambit=>{:name=>"搏命",:name_en=>"Final Gambit",:type=>:fighting,:category=>:special,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:beam,:range_px=>220.0,:visual_kind=>:beam,:visual_style=>:fighting,:effects=>[{:type=>:final_gambit_v056}],:behavior_status=>:implemented_current_hp_fixed_self_ko_v056,:move_key=>:final_gambit,:canonical_move_key=>:final_gambit,:runtime_skill_key=>"mv_final_gambit",:move_type=>:fighting,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :belly_drum=>{:name=>"腹鼓",:name_en=>"Belly Drum",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:belly_drum_v056}],:behavior_status=>:implemented_half_hp_atk_max_v056,:move_key=>:belly_drum,:canonical_move_key=>:belly_drum,:runtime_skill_key=>"mv_belly_drum",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :tri_attack=>{:name=>"三重攻擊",:name_en=>"Tri Attack",:type=>:normal,:category=>:special,:canonical_power=>80,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:light,:effects=>[{:type=>:damage,:power=>80},{:type=>:tri_attack_v056,:chance=>20}],:behavior_status=>:implemented_random_major_secondary_v056,:move_key=>:tri_attack,:canonical_move_key=>:tri_attack,:runtime_skill_key=>"mv_tri_attack",:move_type=>:normal,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :sky_attack=>{:name=>"神鳥猛擊",:name_en=>"Sky Attack",:type=>:flying,:category=>:physical,:canonical_power=>140,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:beam,:range_px=>230.0,:visual_kind=>:beam,:visual_style=>:flying,:effects=>[{:type=>:damage,:power=>140,:crit_bonus=>0.075},{:type=>:sky_attack_flinch_v056,:chance=>30}],:charge_v056=>60,:behavior_status=>:implemented_charge_release_v056,:move_key=>:sky_attack,:canonical_move_key=>:sky_attack,:runtime_skill_key=>"mv_sky_attack",:move_type=>:flying,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :razor_wind=>{:name=>"旋風刀",:name_en=>"Razor Wind",:type=>:normal,:category=>:special,:canonical_power=>80,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:best_cluster,:delivery=>:beam,:range_px=>240.0,:visual_kind=>:beam,:visual_style=>:normal,:effects=>[{:type=>:razor_wind_v056,:power=>80,:crit_bonus=>0.075}],:charge_v056=>60,:behavior_status=>:adapted_charge_enemy_side_aoe_v056,:move_key=>:razor_wind,:canonical_move_key=>:razor_wind,:runtime_skill_key=>"mv_razor_wind",:move_type=>:normal,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :power_swap=>{:name=>"力量互換",:name_en=>"Power Swap",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:stage_swap_v056,:stats=>[:atk,:spatk]}],:behavior_status=>:implemented_stage_swap_v056,:move_key=>:power_swap,:canonical_move_key=>:power_swap,:runtime_skill_key=>"mv_power_swap",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :outrage=>{:name=>"逆鱗",:name_en=>"Outrage",:type=>:dragon,:category=>:physical,:canonical_power=>120,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:dragon,:contact=>true,:force_contact_range=>true,:source_move_flags=>[:contact,:mirror,:protect],:effects=>[{:type=>:damage,:power=>120},{:type=>:repeat_move_v053,:turns=>3,:interval=>60,:power=>120,:kind=>:outrage}],:behavior_status=>:implemented_repeat_confuse_bridge_v056,:move_key=>:outrage,:canonical_move_key=>:outrage,:runtime_skill_key=>"mv_outrage",:move_type=>:dragon,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :mimic=>{:name=>"模仿",:name_en=>"Mimic",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>230.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:mimic_v056}],:behavior_status=>:adapted_battle_slot_copy_v056,:move_key=>:mimic,:canonical_move_key=>:mimic,:runtime_skill_key=>"mv_mimic",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :magic_coat=>{:name=>"魔法反射",:name_en=>"Magic Coat",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>4,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:psychic,:effects=>[{:type=>:magic_coat_v056,:duration=>90}],:behavior_status=>:implemented_single_target_status_reflect_v056,:move_key=>:magic_coat,:canonical_move_key=>:magic_coat,:runtime_skill_key=>"mv_magic_coat",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :guard_swap=>{:name=>"防守互換",:name_en=>"Guard Swap",:type=>:psychic,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:stage_swap_v056,:stats=>[:def,:spdef]}],:behavior_status=>:implemented_stage_swap_v056,:move_key=>:guard_swap,:canonical_move_key=>:guard_swap,:runtime_skill_key=>"mv_guard_swap",:move_type=>:psychic,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :eruption=>{:name=>"噴火",:name_en=>"Eruption",:type=>:fire,:category=>:special,:canonical_power=>150,:accuracy=>100,:priority=>0,:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>260.0,:visual_kind=>:area_hit,:visual_style=>:fire,:global_direct=>true,:radius=>999.0,:dynamic_power_v056=>:eruption,:effects=>[{:type=>:damage,:power=>150,:directional=>false}],:behavior_status=>:implemented_hp_scaled_area_v056,:move_key=>:eruption,:canonical_move_key=>:eruption,:runtime_skill_key=>"mv_eruption",:move_type=>:fire,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :acupressure=>{:name=>"點穴",:name_en=>"Acupressure",:type=>:normal,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:light,:effects=>[{:type=>:acupressure_v056}],:behavior_status=>:adapted_self_random_stat_plus2_v056,:move_key=>:acupressure,:canonical_move_key=>:acupressure,:runtime_skill_key=>"mv_acupressure",:move_type=>:normal,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :venoshock=>{:name=>"毒液衝擊",:name_en=>"Venoshock",:type=>:poison,:category=>:special,:canonical_power=>65,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:poison,:dynamic_power_v056=>:venoshock,:effects=>[{:type=>:damage,:power=>65}],:behavior_status=>:implemented_poison_double_power_v056,:move_key=>:venoshock,:canonical_move_key=>:venoshock,:runtime_skill_key=>"mv_venoshock",:move_type=>:poison,:damage_category=>:special,:energy_runtime_mode=>:full_bar_v015},
    :super_fang=>{:name=>"憤怒門牙",:name_en=>"Super Fang",:type=>:normal,:category=>:physical,:canonical_power=>nil,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:contact=>true,:force_contact_range=>true,:source_move_flags=>[:contact,:mirror,:protect],:effects=>[{:type=>:super_fang_v056}],:behavior_status=>:implemented_half_current_hp_v056,:move_key=>:super_fang,:canonical_move_key=>:super_fang,:runtime_skill_key=>"mv_super_fang",:move_type=>:normal,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :stealth_rock=>{:name=>"隱形岩",:name_en=>"Stealth Rock",:type=>:rock,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:field_disc,:visual_style=>:rock,:effects=>[{:type=>:stealth_rock_v056,:duration=>600}],:behavior_status=>:adapted_realtime_side_hazard_v056,:move_key=>:stealth_rock,:canonical_move_key=>:stealth_rock,:runtime_skill_key=>"mv_stealth_rock",:move_type=>:rock,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
    :smack_down=>{:name=>"擊落",:name_en=>"Smack Down",:type=>:rock,:category=>:physical,:canonical_power=>50,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:rock,:effects=>[{:type=>:damage,:power=>50},{:type=>:smack_down_v056,:duration=>300}],:behavior_status=>:implemented_force_grounded_v056,:move_key=>:smack_down,:canonical_move_key=>:smack_down,:runtime_skill_key=>"mv_smack_down",:move_type=>:rock,:damage_category=>:physical,:energy_runtime_mode=>:full_bar_v015},
    :cotton_guard=>{:name=>"棉花防守",:name_en=>"Cotton Guard",:type=>:grass,:category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:grass,:effects=>[{:type=>:stat_stage,:stat=>:def,:stages=>3}],:behavior_status=>:implemented_stat_stage_v056,:move_key=>:cotton_guard,:canonical_move_key=>:cotton_guard,:runtime_skill_key=>"mv_cotton_guard",:move_type=>:grass,:damage_category=>:status,:energy_runtime_mode=>:full_bar_v015},
  }
  MOVE_PRESENTATION_V056 = {
    :snore=>{:cast_visual=>:normal,:visual_kind=>:beam,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:sound_wave,:timing=>:sleep_only_sound_hit,:user_motion=>:shoot,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:sound_hit},
    :bind=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:bound,:timing=>:contact_then_bound,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:impact_mid},
    :wish=>{:cast_visual=>:light,:visual_kind=>:self_fx,:projectile_visual=>:light,:impact_visual=>:light,:persistent_visual=>:wish_marker,:timing=>:delay120_heal50,:user_motion=>:charge,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:heal},
    :tickle=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:debuff_mark,:timing=>:atk_def_down,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:soft_chime},
    :psycho_shift=>{:cast_visual=>:psychic,:visual_kind=>:projectile,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:status_transfer,:timing=>:major_status_transfer,:user_motion=>:shoot,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:psychic_hit},
    :trick=>{:cast_visual=>:psychic,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:item_swap,:timing=>:held_item_swap,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:item},
    :toxic=>{:cast_visual=>:poison,:visual_kind=>:projectile,:projectile_visual=>:poison,:impact_visual=>:poison,:persistent_visual=>:toxic_mark,:timing=>:escalate60x5,:user_motion=>:shoot,:target_motion=>:none,:screen_effect=>:darken,:sfx_profile=>:poison},
    :spikes=>{:cast_visual=>:ground,:visual_kind=>:field_disc,:projectile_visual=>:ground,:impact_visual=>:ground,:persistent_visual=>:spikes_field,:timing=>:layers3_tick120,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:shake,:sfx_profile=>:ground},
    :metronome=>{:cast_visual=>:normal,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:random_glyph,:timing=>:safe_random_replay,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:magic_chime},
    :karate_chop=>{:cast_visual=>:fighting,:visual_kind=>:contact_hit,:projectile_visual=>:fighting,:impact_visual=>:fighting,:persistent_visual=>:slash_mark,:timing=>:high_crit_contact,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:slash},
    :horn_drill=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:drill_mark,:timing=>:ohko_level_gate,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:impact_heavy},
    :guillotine=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:cut_mark,:timing=>:ohko_level_gate,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:slash},
    :giga_impact=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:impact_burst,:timing=>:damage_then_recharge60,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:impact_heavy},
    :final_gambit=>{:cast_visual=>:fighting,:visual_kind=>:beam,:projectile_visual=>:fighting,:impact_visual=>:fighting,:persistent_visual=>:life_burst,:timing=>:current_hp_damage_selfko,:user_motion=>:charge,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:impact_heavy},
    :belly_drum=>{:cast_visual=>:normal,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:drum_aura,:timing=>:half_hp_atk6,:user_motion=>:charge,:target_motion=>:none,:screen_effect=>:shake,:sfx_profile=>:low_thump},
    :tri_attack=>{:cast_visual=>:normal,:visual_kind=>:projectile,:projectile_visual=>:light,:impact_visual=>:light,:persistent_visual=>:tri_orb,:timing=>:damage_then20_random_status,:user_motion=>:shoot,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:projectile},
    :sky_attack=>{:cast_visual=>:flying,:visual_kind=>:beam,:projectile_visual=>:flying,:impact_visual=>:flying,:persistent_visual=>:sky_charge,:timing=>:charge60_hit_fl30,:user_motion=>:charge,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:wind_hit},
    :razor_wind=>{:cast_visual=>:normal,:visual_kind=>:beam,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:wind_charge,:timing=>:charge60_enemy_aoe,:user_motion=>:charge,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:wind_hit},
    :power_swap=>{:cast_visual=>:psychic,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:swap_arrows,:timing=>:swap_atk_spatk,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:psychic_hit},
    :outrage=>{:cast_visual=>:dragon,:visual_kind=>:contact_hit,:projectile_visual=>:dragon,:impact_visual=>:dragon,:persistent_visual=>:rage_trail,:timing=>:repeat3_hits60_confuse,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:impact_heavy},
    :mimic=>{:cast_visual=>:normal,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:copy_glyph,:timing=>:battle_slot_copy,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:copy},
    :magic_coat=>{:cast_visual=>:psychic,:visual_kind=>:self_fx,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:reflect_shell,:timing=>:reflect_status90,:user_motion=>:charge,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:guard},
    :guard_swap=>{:cast_visual=>:psychic,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:swap_arrows,:timing=>:swap_def_spdef,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:psychic_hit},
    :eruption=>{:cast_visual=>:fire,:visual_kind=>:area_hit,:projectile_visual=>:fire,:impact_visual=>:fire,:persistent_visual=>:eruption_field,:timing=>:hp_scaled_enemy_aoe,:user_motion=>:charge,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:fire_hit},
    :acupressure=>{:cast_visual=>:light,:visual_kind=>:self_fx,:projectile_visual=>:light,:impact_visual=>:light,:persistent_visual=>:stat_flash,:timing=>:random_stat_plus2,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:soft_chime},
    :venoshock=>{:cast_visual=>:poison,:visual_kind=>:projectile,:projectile_visual=>:poison,:impact_visual=>:poison,:persistent_visual=>:venom_burst,:timing=>:poison_target_x2,:user_motion=>:shoot,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:poison},
    :super_fang=>{:cast_visual=>:normal,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:fang_mark,:timing=>:half_current_hp,:user_motion=>:attack,:target_motion=>:hurt,:screen_effect=>:flash,:sfx_profile=>:impact_mid},
    :stealth_rock=>{:cast_visual=>:rock,:visual_kind=>:field_disc,:projectile_visual=>:rock,:impact_visual=>:rock,:persistent_visual=>:rock_field,:timing=>:rock_effectiveness_tick120,:user_motion=>:cast,:target_motion=>:none,:screen_effect=>:shake,:sfx_profile=>:rock},
    :smack_down=>{:cast_visual=>:rock,:visual_kind=>:projectile,:projectile_visual=>:rock,:impact_visual=>:rock,:persistent_visual=>:ground_mark,:timing=>:damage_ground300,:user_motion=>:shoot,:target_motion=>:hurt,:screen_effect=>:shake,:sfx_profile=>:rock},
    :cotton_guard=>{:cast_visual=>:grass,:visual_kind=>:self_fx,:projectile_visual=>:grass,:impact_visual=>:grass,:persistent_visual=>:cotton_aura,:timing=>:def_plus3,:user_motion=>:charge,:target_motion=>:none,:screen_effect=>:flash,:sfx_profile=>:guard},
  }

  # Replace the electronic Tone_Mid_Beep cast cue on common melee openers.
  # These remain user-editable through the existing Presentation authoring layer.
  MELEE_CAST_SFX_CLEANUP_V056 = {
    :tackle=>{:name=>"PMD_SFX_Library/Pokemon_Ranger/Low_Thump/RGR_Low_Thump_002",:volume=>58,:pitch=>106},
    :slash=>{:name=>"PMD_SFX_Library/Pokemon_Ranger/Slash_Swish/RGR_Slash_Swish_002",:volume=>58,:pitch=>108},
    :quick_attack=>{:name=>"PMD_SFX_Library/Pokemon_Ranger/Wind_Whoosh/RGR_Wind_Whoosh_001",:volume=>56,:pitch=>118},
    :false_swipe=>{:name=>"PMD_SFX_Library/Pokemon_Ranger/Slash_Swish/RGR_Slash_Swish_002",:volume=>56,:pitch=>110},
    :rapid_spin=>{:name=>"PMD_SFX_Library/Pokemon_Ranger/Wind_Whoosh/RGR_Wind_Whoosh_001",:volume=>56,:pitch=>112}
  }

  MOVE_COVERAGE_VII_VISUAL_V056 = {}
  MOVE_COVERAGE_VII_AUDIO_V056 = {}
  MOVE_COVERAGE_VII_MOVE_V056.each do |k,d|
    p=MOVE_PRESENTATION_V056[k]||{}
    MOVE_COVERAGE_VII_VISUAL_V056[k]={:visual_kind=>p[:visual_kind]||d[:visual_kind],:style=>p[:projectile_visual]||d[:visual_style],:hide_logical_projectile=>false,:timing=>p[:timing],:persistent_visual=>p[:persistent_visual]}
    MOVE_COVERAGE_VII_AUDIO_V056[k]={:type=>d[:type],:category=>d[:category],:visual_kind=>d[:visual_kind],:audio_style=>d[:visual_style],:cast_cat=>(d[:category]==:status ? :magic_chime : (d[:contact] ? :low_thump : :snap_click)),:launch_cat=>([:projectile,:aoe,:beam].include?(d[:delivery]) ? :wind_hiss : nil),:hit_cat=>(d[:category]==:status ? :tone_soft : :impact_mid),:special=>true,:presentation_sfx=>p[:sfx_profile]}
  end
end
