#==============================================================================
# 【PMD AutoChess 中文維護說明】
# 腳本：PMD AutoChess Move Runtime Coverage Data v0.57
# 分類：技能資料／效果覆蓋
#
# 【用途／機制】
# 定義 MoveDB、招式 Runtime 行為與 7005/7005 learnset reference 覆蓋。
#
# 【怎麼調整】
# 新增招式效果優先放在資料表與共用 foundation；不要為每招複製一份傷害流程。
#
# 【本腳本主要設定常數／資料表】
# - MOVE_COVERAGE_VIII_MANIFEST_V057 / MOVE_COVERAGE_VIII_CHECKSUM_TEXT_V057 / MOVE_COVERAGE_VIII_MOVE_V057 / MOVE_PRESENTATION_V057
# - MOVE_COVERAGE_VIII_VISUAL_V057 / MOVE_COVERAGE_VIII_AUDIO_V057
#
# 【維護規則】
# - RPG Maker VX / RGSS2 / Ruby 1.8 相容。
# - instance_uid 才是 Pokémon 個體身份；Actor ID 只是容器。
# - 新增行為優先沿用既有 helper／Data 表；避免破壞已 Freeze 的舊核心。
# - 本專案新腳本也必須保留同等級的中文說明與實際範例。
#==============================================================================
#===============================================================================
# ■ PMD AutoChess Move Runtime Coverage Data v0.57
#    Expansion VIII + Organic Presentation Bridge
#===============================================================================
module PMD_AC
  MOVE_COVERAGE_VIII_MANIFEST_V057 = {:schema_version=>"1.0",:content_version=>"0.57.0",:base_version=>"0.56.1",:feature=>"move_runtime_coverage_expansion_viii",:new_mapped_move_count=>48,:cumulative_mapped_move_count=>478,:new_reference_covered=>160,:cumulative_reference_covered=>6899,:learnset_reference_total=>7005,:cumulative_coverage_percent=>98.49,:new_move_keys=>[:metal_burst,:recycle,:psyshock,:pluck,:nightmare,:miracle_eye,:foul_play,:entrainment,:dragon_tail,:cross_chop,:comet_punch,:air_cutter,:torment,:sludge_wave,:sleep_talk,:sky_uppercut,:skull_bash,:shadow_claw,:role_play,:heal_bell,:feather_dance,:drill_run,:crabhammer,:water_spout,:switcheroo,:spike_cannon,:reflect_type,:ice_ball,:conversion,:brick_break,:bone_rush,:assist,:arm_thrust,:thief,:tail_glow,:spider_web,:smelling_salts,:dual_chop,:clear_smog,:clamp,:bonemerang,:blaze_kick,:barrage,:work_up,:twineedle,:spacial_rend,:sharpen,:searing_shot],:ref_counts=>{:metal_burst=>6,:recycle=>5,:psyshock=>5,:pluck=>5,:nightmare=>5,:miracle_eye=>5,:foul_play=>5,:entrainment=>5,:dragon_tail=>5,:cross_chop=>5,:comet_punch=>5,:air_cutter=>5,:torment=>4,:sludge_wave=>4,:sleep_talk=>4,:sky_uppercut=>4,:skull_bash=>4,:shadow_claw=>4,:role_play=>4,:heal_bell=>4,:feather_dance=>4,:drill_run=>4,:crabhammer=>4,:water_spout=>3,:switcheroo=>3,:spike_cannon=>3,:reflect_type=>3,:ice_ball=>3,:conversion=>3,:brick_break=>3,:bone_rush=>3,:assist=>3,:arm_thrust=>3,:thief=>2,:tail_glow=>2,:spider_web=>2,:smelling_salts=>2,:dual_chop=>2,:clear_smog=>2,:clamp=>2,:bonemerang=>2,:blaze_kick=>2,:barrage=>2,:work_up=>1,:twineedle=>1,:spacial_rend=>1,:sharpen=>1,:searing_shot=>1},:presentation_profiles=>48,:timing_profiles=>48,:audio_profiles=>48,:visual_showcase_moves=>48,:runtime_checksum32=>1569311894}
  MOVE_COVERAGE_VIII_CHECKSUM_TEXT_V057 = "v057|metal_burst|recycle|psyshock|pluck|nightmare|miracle_eye|foul_play|entrainment|dragon_tail|cross_chop|comet_punch|air_cutter|torment|sludge_wave|sleep_talk|sky_uppercut|skull_bash|shadow_claw|role_play|heal_bell|feather_dance|drill_run|crabhammer|water_spout|switcheroo|spike_cannon|reflect_type|ice_ball|conversion|brick_break|bone_rush|assist|arm_thrust|thief|tail_glow|spider_web|smelling_salts|dual_chop|clear_smog|clamp|bonemerang|blaze_kick|barrage|work_up|twineedle|spacial_rend|sharpen|searing_shot|160|6899|98.49|presentation48|organic_audio|reactive|items|type_override|multihit|charge"
  MOVE_COVERAGE_VIII_MOVE_V057 = {
    :metal_burst=>{:canonical_move_key=>:metal_burst,:move_key=>:metal_burst,:runtime_skill_key=>:mv_metal_burst,:name=>"金屬爆炸",:name_en=>"Metal Burst",:type=>:steel,:move_type=>:steel,:category=>:physical,:damage_category=>:physical,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:steel,:effects=>[{:type=>:metal_burst_v057,:ratio=>1.5}],:behavior_status=>:implemented_recent_damage_return_v057},
    :recycle=>{:canonical_move_key=>:recycle,:move_key=>:recycle,:runtime_skill_key=>:mv_recycle,:name=>"回收利用",:name_en=>"Recycle",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:recycle_v057}],:behavior_status=>:implemented_last_consumed_item_restore_v057},
    :psyshock=>{:canonical_move_key=>:psyshock,:move_key=>:psyshock,:runtime_skill_key=>:mv_psyshock,:name=>"精神衝擊",:name_en=>"Psyshock",:type=>:psychic,:move_type=>:psychic,:category=>:special,:damage_category=>:special,:canonical_power=>80,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:psychic,:damage_calc_v057=>:psyshock,:effects=>[{:type=>:damage,:power=>80}],:behavior_status=>:implemented_spatk_vs_def_v057},
    :pluck=>{:canonical_move_key=>:pluck,:move_key=>:pluck,:runtime_skill_key=>:mv_pluck,:name=>"啄食",:name_en=>"Pluck",:type=>:flying,:move_type=>:flying,:category=>:physical,:damage_category=>:physical,:canonical_power=>60,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:flying,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>60},{:type=>:pluck_item_v057}],:behavior_status=>:adapted_consumable_item_remove_no_berry_effect_v057},
    :nightmare=>{:canonical_move_key=>:nightmare,:move_key=>:nightmare,:runtime_skill_key=>:mv_nightmare,:name=>"惡夢",:name_en=>"Nightmare",:type=>:ghost,:move_type=>:ghost,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:ghost,:effects=>[{:type=>:nightmare_v057,:duration=>300,:interval=>60,:ratio=>0.25}],:behavior_status=>:implemented_sleep_bound_dot_v057},
    :miracle_eye=>{:canonical_move_key=>:miracle_eye,:move_key=>:miracle_eye,:runtime_skill_key=>:mv_miracle_eye,:name=>"奇跡之眼",:name_en=>"Miracle Eye",:type=>:psychic,:move_type=>:psychic,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:miracle_eye_v057,:duration=>180}],:behavior_status=>:implemented_evasion_ignore_psychic_dark_bypass_v057},
    :foul_play=>{:canonical_move_key=>:foul_play,:move_key=>:foul_play,:runtime_skill_key=>:mv_foul_play,:name=>"欺詐",:name_en=>"Foul Play",:type=>:dark,:move_type=>:dark,:category=>:physical,:damage_category=>:physical,:canonical_power=>95,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:dark,:contact=>true,:force_contact_range=>true,:damage_calc_v057=>:foul_play,:effects=>[{:type=>:damage,:power=>95}],:behavior_status=>:implemented_target_attack_damage_v057},
    :entrainment=>{:canonical_move_key=>:entrainment,:move_key=>:entrainment,:runtime_skill_key=>:mv_entrainment,:name=>"找夥伴",:name_en=>"Entrainment",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:entrainment_v057,:duration=>300}],:behavior_status=>:adapted_temporary_effective_ability_copy_v057},
    :dragon_tail=>{:canonical_move_key=>:dragon_tail,:move_key=>:dragon_tail,:runtime_skill_key=>:mv_dragon_tail,:name=>"龍尾",:name_en=>"Dragon Tail",:type=>:dragon,:move_type=>:dragon,:category=>:physical,:damage_category=>:physical,:canonical_power=>60,:accuracy=>90,:priority=>-6,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:dragon,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>60},{:type=>:force_back_v052,:distance=>126.0}],:behavior_status=>:adapted_damage_then_knockback_v057},
    :cross_chop=>{:canonical_move_key=>:cross_chop,:move_key=>:cross_chop,:runtime_skill_key=>:mv_cross_chop,:name=>"十字劈",:name_en=>"Cross Chop",:type=>:fighting,:move_type=>:fighting,:category=>:physical,:damage_category=>:physical,:canonical_power=>100,:accuracy=>80,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fighting,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>100,:crit_bonus=>0.075}],:behavior_status=>:implemented_high_crit_v057},
    :comet_punch=>{:canonical_move_key=>:comet_punch,:move_key=>:comet_punch,:runtime_skill_key=>:mv_comet_punch,:name=>"連續拳",:name_en=>"Comet Punch",:type=>:normal,:move_type=>:normal,:category=>:physical,:damage_category=>:physical,:canonical_power=>18,:accuracy=>85,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:contact=>true,:force_contact_range=>true,:multi_hit_v049=>true,:multi_hit_min=>2,:multi_hit_max=>5,:effects=>[{:type=>:damage,:power=>18}],:behavior_status=>:implemented_multi_hit_v057},
    :air_cutter=>{:canonical_move_key=>:air_cutter,:move_key=>:air_cutter,:runtime_skill_key=>:mv_air_cutter,:name=>"空氣利刃",:name_en=>"Air Cutter",:type=>:flying,:move_type=>:flying,:category=>:special,:damage_category=>:special,:canonical_power=>55,:accuracy=>95,:priority=>0,:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>260.0,:visual_kind=>:area_hit,:visual_style=>:flying,:radius=>999.0,:global_direct=>true,:effects=>[{:type=>:damage,:power=>55,:crit_bonus=>0.075,:directional=>false}],:behavior_status=>:adapted_enemy_side_aoe_high_crit_v057},
    :torment=>{:canonical_move_key=>:torment,:move_key=>:torment,:runtime_skill_key=>:mv_torment,:name=>"無理取鬧",:name_en=>"Torment",:type=>:dark,:move_type=>:dark,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:dark,:effects=>[{:type=>:torment_v057,:duration=>180}],:behavior_status=>:implemented_no_consecutive_same_move_v057},
    :sludge_wave=>{:canonical_move_key=>:sludge_wave,:move_key=>:sludge_wave,:runtime_skill_key=>:mv_sludge_wave,:name=>"污泥波",:name_en=>"Sludge Wave",:type=>:poison,:move_type=>:poison,:category=>:special,:damage_category=>:special,:canonical_power=>95,:accuracy=>100,:priority=>0,:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>260.0,:visual_kind=>:area_hit,:visual_style=>:poison,:radius=>999.0,:global_direct=>true,:effects=>[{:type=>:damage,:power=>95,:directional=>false}],:secondary_effects=>[{:group=>0,:type=>:ailment,:status=>:poison,:chance=>10,:receiver=>:target,:duration=>180,:interval=>30,:tick_maxhp_ratio=>0.015}],:behavior_status=>:adapted_enemy_side_aoe_v057},
    :sleep_talk=>{:canonical_move_key=>:sleep_talk,:move_key=>:sleep_talk,:runtime_skill_key=>:mv_sleep_talk,:name=>"夢話",:name_en=>"Sleep Talk",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:sleep_talk_v057}],:behavior_status=>:adapted_sleep_only_safe_active_damage_replay_v057},
    :sky_uppercut=>{:canonical_move_key=>:sky_uppercut,:move_key=>:sky_uppercut,:runtime_skill_key=>:mv_sky_uppercut,:name=>"衝天拳",:name_en=>"Sky Uppercut",:type=>:fighting,:move_type=>:fighting,:category=>:physical,:damage_category=>:physical,:canonical_power=>85,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fighting,:contact=>true,:force_contact_range=>true,:sky_uppercut_v057=>true,:effects=>[{:type=>:damage,:power=>85}],:behavior_status=>:implemented_airborne_exception_v057},
    :skull_bash=>{:canonical_move_key=>:skull_bash,:move_key=>:skull_bash,:runtime_skill_key=>:mv_skull_bash,:name=>"火箭頭錘",:name_en=>"Skull Bash",:type=>:normal,:move_type=>:normal,:category=>:physical,:damage_category=>:physical,:canonical_power=>100,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:contact=>true,:force_contact_range=>true,:charge_v057=>60,:effects=>[{:type=>:damage,:power=>100}],:behavior_status=>:implemented_charge_def_plus1_release_v057},
    :shadow_claw=>{:canonical_move_key=>:shadow_claw,:move_key=>:shadow_claw,:runtime_skill_key=>:mv_shadow_claw,:name=>"暗影爪",:name_en=>"Shadow Claw",:type=>:ghost,:move_type=>:ghost,:category=>:physical,:damage_category=>:physical,:canonical_power=>70,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:ghost,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>70,:crit_bonus=>0.075}],:behavior_status=>:implemented_high_crit_v057},
    :role_play=>{:canonical_move_key=>:role_play,:move_key=>:role_play,:runtime_skill_key=>:mv_role_play,:name=>"扮演",:name_en=>"Role Play",:type=>:psychic,:move_type=>:psychic,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:psychic,:effects=>[{:type=>:role_play_v057,:duration=>300}],:behavior_status=>:adapted_temporary_effective_ability_copy_v057},
    :heal_bell=>{:canonical_move_key=>:heal_bell,:move_key=>:heal_bell,:runtime_skill_key=>:mv_heal_bell,:name=>"治癒鈴聲",:name_en=>"Heal Bell",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:sound=>true,:effects=>[{:type=>:heal_bell_v057}],:behavior_status=>:adapted_active_team_cure_soundproof_respected_v057},
    :feather_dance=>{:canonical_move_key=>:feather_dance,:move_key=>:feather_dance,:runtime_skill_key=>:mv_feather_dance,:name=>"羽毛舞",:name_en=>"Feather Dance",:type=>:flying,:move_type=>:flying,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:flying,:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>-2}],:behavior_status=>:implemented_stat_stage_v057},
    :drill_run=>{:canonical_move_key=>:drill_run,:move_key=>:drill_run,:runtime_skill_key=>:mv_drill_run,:name=>"直衝鑽",:name_en=>"Drill Run",:type=>:ground,:move_type=>:ground,:category=>:physical,:damage_category=>:physical,:canonical_power=>80,:accuracy=>95,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:ground,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>80,:crit_bonus=>0.075}],:behavior_status=>:implemented_high_crit_v057},
    :crabhammer=>{:canonical_move_key=>:crabhammer,:move_key=>:crabhammer,:runtime_skill_key=>:mv_crabhammer,:name=>"蟹鉗錘",:name_en=>"Crabhammer",:type=>:water,:move_type=>:water,:category=>:physical,:damage_category=>:physical,:canonical_power=>90,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:water,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>90,:crit_bonus=>0.075}],:behavior_status=>:implemented_high_crit_v057},
    :water_spout=>{:canonical_move_key=>:water_spout,:move_key=>:water_spout,:runtime_skill_key=>:mv_water_spout,:name=>"噴水",:name_en=>"Water Spout",:type=>:water,:move_type=>:water,:category=>:special,:damage_category=>:special,:canonical_power=>150,:accuracy=>100,:priority=>0,:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>260.0,:visual_kind=>:area_hit,:visual_style=>:water,:radius=>999.0,:global_direct=>true,:dynamic_power_v057=>:water_spout,:effects=>[{:type=>:damage,:power=>150,:directional=>false}],:behavior_status=>:implemented_user_hp_scaled_enemy_side_v057},
    :switcheroo=>{:canonical_move_key=>:switcheroo,:move_key=>:switcheroo,:runtime_skill_key=>:mv_switcheroo,:name=>"掉包",:name_en=>"Switcheroo",:type=>:dark,:move_type=>:dark,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:dark,:effects=>[{:type=>:switcheroo_v057}],:behavior_status=>:implemented_held_item_swap_bridge_v057},
    :spike_cannon=>{:canonical_move_key=>:spike_cannon,:move_key=>:spike_cannon,:runtime_skill_key=>:mv_spike_cannon,:name=>"尖刺加農炮",:name_en=>"Spike Cannon",:type=>:normal,:move_type=>:normal,:category=>:physical,:damage_category=>:physical,:canonical_power=>20,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>235.0,:visual_kind=>:projectile,:visual_style=>:normal,:multi_hit_v049=>true,:multi_hit_min=>2,:multi_hit_max=>5,:effects=>[{:type=>:damage,:power=>20}],:behavior_status=>:implemented_multi_hit_v057},
    :reflect_type=>{:canonical_move_key=>:reflect_type,:move_key=>:reflect_type,:runtime_skill_key=>:mv_reflect_type,:name=>"鏡面屬性",:name_en=>"Reflect Type",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:normal,:effects=>[{:type=>:reflect_type_v057}],:behavior_status=>:adapted_battle_type_override_v057},
    :ice_ball=>{:canonical_move_key=>:ice_ball,:move_key=>:ice_ball,:runtime_skill_key=>:mv_ice_ball,:name=>"冰球",:name_en=>"Ice Ball",:type=>:ice,:move_type=>:ice,:category=>:physical,:damage_category=>:physical,:canonical_power=>30,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:ice,:contact=>true,:force_contact_range=>true,:dynamic_power_v057=>:ice_ball,:sequence_v057=>:ice_ball,:effects=>[{:type=>:damage,:power=>30}],:behavior_status=>:implemented_consecutive_double_power_v057},
    :conversion=>{:canonical_move_key=>:conversion,:move_key=>:conversion,:runtime_skill_key=>:mv_conversion,:name=>"紋理",:name_en=>"Conversion",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:conversion_v057}],:behavior_status=>:adapted_first_active_move_type_v057},
    :brick_break=>{:canonical_move_key=>:brick_break,:move_key=>:brick_break,:runtime_skill_key=>:mv_brick_break,:name=>"劈瓦",:name_en=>"Brick Break",:type=>:fighting,:move_type=>:fighting,:category=>:physical,:damage_category=>:physical,:canonical_power=>75,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fighting,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>75},{:type=>:brick_break_v057}],:behavior_status=>:implemented_screen_clear_v057},
    :bone_rush=>{:canonical_move_key=>:bone_rush,:move_key=>:bone_rush,:runtime_skill_key=>:mv_bone_rush,:name=>"骨棒亂打",:name_en=>"Bone Rush",:type=>:ground,:move_type=>:ground,:category=>:physical,:damage_category=>:physical,:canonical_power=>25,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>235.0,:visual_kind=>:projectile,:visual_style=>:ground,:multi_hit_v049=>true,:multi_hit_min=>2,:multi_hit_max=>5,:effects=>[{:type=>:damage,:power=>25}],:behavior_status=>:implemented_multi_hit_v057},
    :assist=>{:canonical_move_key=>:assist,:move_key=>:assist,:runtime_skill_key=>:mv_assist,:name=>"借助",:name_en=>"Assist",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:assist_v057}],:behavior_status=>:adapted_active_allies_safe_damage_replay_v057},
    :arm_thrust=>{:canonical_move_key=>:arm_thrust,:move_key=>:arm_thrust,:runtime_skill_key=>:mv_arm_thrust,:name=>"猛推",:name_en=>"Arm Thrust",:type=>:fighting,:move_type=>:fighting,:category=>:physical,:damage_category=>:physical,:canonical_power=>15,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fighting,:contact=>true,:force_contact_range=>true,:multi_hit_v049=>true,:multi_hit_min=>2,:multi_hit_max=>5,:effects=>[{:type=>:damage,:power=>15}],:behavior_status=>:implemented_multi_hit_v057},
    :thief=>{:canonical_move_key=>:thief,:move_key=>:thief,:runtime_skill_key=>:mv_thief,:name=>"小偷",:name_en=>"Thief",:type=>:dark,:move_type=>:dark,:category=>:physical,:damage_category=>:physical,:canonical_power=>40,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:dark,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>40},{:type=>:thief_v057}],:behavior_status=>:implemented_item_steal_v057},
    :tail_glow=>{:canonical_move_key=>:tail_glow,:move_key=>:tail_glow,:runtime_skill_key=>:mv_tail_glow,:name=>"螢火",:name_en=>"Tail Glow",:type=>:bug,:move_type=>:bug,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:bug,:effects=>[{:type=>:stat_stage,:stat=>:spatk,:stages=>3}],:behavior_status=>:implemented_stat_stage_v057},
    :spider_web=>{:canonical_move_key=>:spider_web,:move_key=>:spider_web,:runtime_skill_key=>:mv_spider_web,:name=>"蛛網",:name_en=>"Spider Web",:type=>:bug,:move_type=>:bug,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>220.0,:visual_kind=>:target_hit,:visual_style=>:bug,:effects=>[{:type=>:mean_look_v053,:duration=>300}],:behavior_status=>:implemented_switch_lock_bridge_v057},
    :smelling_salts=>{:canonical_move_key=>:smelling_salts,:move_key=>:smelling_salts,:runtime_skill_key=>:mv_smelling_salts,:name=>"清醒",:name_en=>"Smelling Salts",:type=>:normal,:move_type=>:normal,:category=>:physical,:damage_category=>:physical,:canonical_power=>60,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:normal,:contact=>true,:force_contact_range=>true,:dynamic_power_v057=>:smelling_salts,:effects=>[{:type=>:damage,:power=>60},{:type=>:smelling_salts_cure_v057}],:behavior_status=>:implemented_paralysis_double_then_cure_v057},
    :dual_chop=>{:canonical_move_key=>:dual_chop,:move_key=>:dual_chop,:runtime_skill_key=>:mv_dual_chop,:name=>"二連劈",:name_en=>"Dual Chop",:type=>:dragon,:move_type=>:dragon,:category=>:physical,:damage_category=>:physical,:canonical_power=>40,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:dragon,:contact=>true,:force_contact_range=>true,:multi_hit_v049=>true,:multi_hit_min=>2,:multi_hit_max=>2,:effects=>[{:type=>:damage,:power=>40}],:behavior_status=>:implemented_two_hit_v057},
    :clear_smog=>{:canonical_move_key=>:clear_smog,:move_key=>:clear_smog,:runtime_skill_key=>:mv_clear_smog,:name=>"清除之煙",:name_en=>"Clear Smog",:type=>:poison,:move_type=>:poison,:category=>:special,:damage_category=>:special,:canonical_power=>50,:accuracy=>nil,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>230.0,:visual_kind=>:projectile,:visual_style=>:poison,:effects=>[{:type=>:damage,:power=>50},{:type=>:clear_smog_v057}],:behavior_status=>:implemented_never_miss_reset_stages_v057},
    :clamp=>{:canonical_move_key=>:clamp,:move_key=>:clamp,:runtime_skill_key=>:mv_clamp,:name=>"貝殼夾擊",:name_en=>"Clamp",:type=>:water,:move_type=>:water,:category=>:physical,:damage_category=>:physical,:canonical_power=>35,:accuracy=>85,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:water,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>35},{:type=>:bound_v052,:duration=>300,:interval=>60,:ratio=>0.0625,:style=>:water}],:behavior_status=>:implemented_bound_bridge_v057},
    :bonemerang=>{:canonical_move_key=>:bonemerang,:move_key=>:bonemerang,:runtime_skill_key=>:mv_bonemerang,:name=>"骨頭回力鏢",:name_en=>"Bonemerang",:type=>:ground,:move_type=>:ground,:category=>:physical,:damage_category=>:physical,:canonical_power=>50,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>235.0,:visual_kind=>:projectile,:visual_style=>:ground,:multi_hit_v049=>true,:multi_hit_min=>2,:multi_hit_max=>2,:effects=>[{:type=>:damage,:power=>50}],:behavior_status=>:implemented_two_hit_v057},
    :blaze_kick=>{:canonical_move_key=>:blaze_kick,:move_key=>:blaze_kick,:runtime_skill_key=>:mv_blaze_kick,:name=>"火焰踢",:name_en=>"Blaze Kick",:type=>:fire,:move_type=>:fire,:category=>:physical,:damage_category=>:physical,:canonical_power=>85,:accuracy=>90,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:instant,:range_px=>52.0,:visual_kind=>:contact_hit,:visual_style=>:fire,:contact=>true,:force_contact_range=>true,:effects=>[{:type=>:damage,:power=>85,:crit_bonus=>0.075}],:secondary_effects=>[{:group=>0,:type=>:ailment,:status=>:burn,:chance=>10,:receiver=>:target,:duration=>180,:interval=>30,:tick_maxhp_ratio=>0.0125}],:behavior_status=>:implemented_high_crit_burn_v057},
    :barrage=>{:canonical_move_key=>:barrage,:move_key=>:barrage,:runtime_skill_key=>:mv_barrage,:name=>"投球",:name_en=>"Barrage",:type=>:normal,:move_type=>:normal,:category=>:physical,:damage_category=>:physical,:canonical_power=>15,:accuracy=>85,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>235.0,:visual_kind=>:projectile,:visual_style=>:normal,:multi_hit_v049=>true,:multi_hit_min=>2,:multi_hit_max=>5,:effects=>[{:type=>:damage,:power=>15}],:behavior_status=>:implemented_multi_hit_v057},
    :work_up=>{:canonical_move_key=>:work_up,:move_key=>:work_up,:runtime_skill_key=>:mv_work_up,:name=>"自我激勵",:name_en=>"Work Up",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>1},{:type=>:stat_stage,:stat=>:spatk,:stages=>1}],:behavior_status=>:implemented_stat_stage_v057},
    :twineedle=>{:canonical_move_key=>:twineedle,:move_key=>:twineedle,:runtime_skill_key=>:mv_twineedle,:name=>"雙針",:name_en=>"Twineedle",:type=>:bug,:move_type=>:bug,:category=>:physical,:damage_category=>:physical,:canonical_power=>25,:accuracy=>100,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:projectile,:range_px=>235.0,:visual_kind=>:projectile,:visual_style=>:bug,:multi_hit_v049=>true,:multi_hit_min=>2,:multi_hit_max=>2,:effects=>[{:type=>:damage,:power=>25}],:secondary_effects=>[{:group=>0,:type=>:ailment,:status=>:poison,:chance=>20,:receiver=>:target,:duration=>180,:interval=>30,:tick_maxhp_ratio=>0.015}],:behavior_status=>:implemented_two_hit_poison_v057},
    :spacial_rend=>{:canonical_move_key=>:spacial_rend,:move_key=>:spacial_rend,:runtime_skill_key=>:mv_spacial_rend,:name=>"亞空裂斬",:name_en=>"Spacial Rend",:type=>:dragon,:move_type=>:dragon,:category=>:special,:damage_category=>:special,:canonical_power=>100,:accuracy=>95,:priority=>0,:target_type=>:enemy_targeted,:policy=>:current_target,:delivery=>:beam,:range_px=>240.0,:visual_kind=>:beam,:visual_style=>:dragon,:effects=>[{:type=>:damage,:power=>100,:crit_bonus=>0.075}],:behavior_status=>:implemented_high_crit_v057},
    :sharpen=>{:canonical_move_key=>:sharpen,:move_key=>:sharpen,:runtime_skill_key=>:mv_sharpen,:name=>"稜角化",:name_en=>"Sharpen",:type=>:normal,:move_type=>:normal,:category=>:status,:damage_category=>:status,:canonical_power=>nil,:accuracy=>nil,:priority=>0,:target_type=>:self,:policy=>:self,:delivery=>:instant,:range_px=>0.0,:visual_kind=>:self_fx,:visual_style=>:normal,:effects=>[{:type=>:stat_stage,:stat=>:atk,:stages=>1}],:behavior_status=>:implemented_stat_stage_v057},
    :searing_shot=>{:canonical_move_key=>:searing_shot,:move_key=>:searing_shot,:runtime_skill_key=>:mv_searing_shot,:name=>"火焰彈",:name_en=>"Searing Shot",:type=>:fire,:move_type=>:fire,:category=>:special,:damage_category=>:special,:canonical_power=>100,:accuracy=>100,:priority=>0,:target_type=>:ground_enemy,:policy=>:best_cluster,:delivery=>:aoe,:range_px=>260.0,:visual_kind=>:area_hit,:visual_style=>:fire,:radius=>999.0,:global_direct=>true,:effects=>[{:type=>:damage,:power=>100,:directional=>false}],:secondary_effects=>[{:group=>0,:type=>:ailment,:status=>:burn,:chance=>30,:receiver=>:target,:duration=>180,:interval=>30,:tick_maxhp_ratio=>0.0125}],:behavior_status=>:adapted_enemy_side_aoe_v057},
  }
  MOVE_PRESENTATION_V057 = {
    :metal_burst=>{:move_key=>:metal_burst,:motion=>:stationary_cast,:pose=>:attack,:visual_kind=>:target_hit,:projectile_visual=>:steel,:impact_visual=>:steel,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :recycle=>{:move_key=>:recycle,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :psyshock=>{:move_key=>:psyshock,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:projectile,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:none,:timing=>:projectile_impact,:sfx_profile=>:organic_v0561},
    :pluck=>{:move_key=>:pluck,:motion=>:contact_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:flying,:impact_visual=>:flying,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :nightmare=>{:move_key=>:nightmare,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:ghost,:impact_visual=>:ghost,:persistent_visual=>:nightmare_aura,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :miracle_eye=>{:move_key=>:miracle_eye,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:miracle_eye_mark,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :foul_play=>{:move_key=>:foul_play,:motion=>:contact_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:dark,:impact_visual=>:dark,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :entrainment=>{:move_key=>:entrainment,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :dragon_tail=>{:move_key=>:dragon_tail,:motion=>:contact_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:dragon,:impact_visual=>:dragon,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :cross_chop=>{:move_key=>:cross_chop,:motion=>:lunge_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:fighting,:impact_visual=>:fighting,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :comet_punch=>{:move_key=>:comet_punch,:motion=>:multi_contact,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :air_cutter=>{:move_key=>:air_cutter,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:area_hit,:projectile_visual=>:flying,:impact_visual=>:flying,:persistent_visual=>:none,:timing=>:area_same_frame,:sfx_profile=>:organic_v0561},
    :torment=>{:move_key=>:torment,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:dark,:impact_visual=>:dark,:persistent_visual=>:torment_mark,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :sludge_wave=>{:move_key=>:sludge_wave,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:area_hit,:projectile_visual=>:poison,:impact_visual=>:poison,:persistent_visual=>:none,:timing=>:area_same_frame,:sfx_profile=>:organic_v0561},
    :sleep_talk=>{:move_key=>:sleep_talk,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :sky_uppercut=>{:move_key=>:sky_uppercut,:motion=>:lunge_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:fighting,:impact_visual=>:fighting,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :skull_bash=>{:move_key=>:skull_bash,:motion=>:charge_dash,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:charge_aura,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :shadow_claw=>{:move_key=>:shadow_claw,:motion=>:lunge_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:ghost,:impact_visual=>:ghost,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :role_play=>{:move_key=>:role_play,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:psychic,:impact_visual=>:psychic,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :heal_bell=>{:move_key=>:heal_bell,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :feather_dance=>{:move_key=>:feather_dance,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:flying,:impact_visual=>:flying,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :drill_run=>{:move_key=>:drill_run,:motion=>:charge_dash,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:ground,:impact_visual=>:ground,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :crabhammer=>{:move_key=>:crabhammer,:motion=>:lunge_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:water,:impact_visual=>:water,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :water_spout=>{:move_key=>:water_spout,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:area_hit,:projectile_visual=>:water,:impact_visual=>:water,:persistent_visual=>:none,:timing=>:area_same_frame,:sfx_profile=>:organic_v0561},
    :switcheroo=>{:move_key=>:switcheroo,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:dark,:impact_visual=>:dark,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :spike_cannon=>{:move_key=>:spike_cannon,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:projectile,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:projectile_impact,:sfx_profile=>:organic_v0561},
    :reflect_type=>{:move_key=>:reflect_type,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :ice_ball=>{:move_key=>:ice_ball,:motion=>:spin_contact,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:ice,:impact_visual=>:ice,:persistent_visual=>:sequence_trail,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :conversion=>{:move_key=>:conversion,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :brick_break=>{:move_key=>:brick_break,:motion=>:lunge_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:fighting,:impact_visual=>:fighting,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :bone_rush=>{:move_key=>:bone_rush,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:projectile,:projectile_visual=>:ground,:impact_visual=>:ground,:persistent_visual=>:none,:timing=>:projectile_impact,:sfx_profile=>:organic_v0561},
    :assist=>{:move_key=>:assist,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :arm_thrust=>{:move_key=>:arm_thrust,:motion=>:multi_contact,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:fighting,:impact_visual=>:fighting,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :thief=>{:move_key=>:thief,:motion=>:contact_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:dark,:impact_visual=>:dark,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :tail_glow=>{:move_key=>:tail_glow,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:self_fx,:projectile_visual=>:bug,:impact_visual=>:bug,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :spider_web=>{:move_key=>:spider_web,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:target_hit,:projectile_visual=>:bug,:impact_visual=>:bug,:persistent_visual=>:spider_web_mark,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :smelling_salts=>{:move_key=>:smelling_salts,:motion=>:contact_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :dual_chop=>{:move_key=>:dual_chop,:motion=>:multi_contact,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:dragon,:impact_visual=>:dragon,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :clear_smog=>{:move_key=>:clear_smog,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:projectile,:projectile_visual=>:poison,:impact_visual=>:poison,:persistent_visual=>:none,:timing=>:projectile_impact,:sfx_profile=>:organic_v0561},
    :clamp=>{:move_key=>:clamp,:motion=>:contact_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:water,:impact_visual=>:water,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :bonemerang=>{:move_key=>:bonemerang,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:projectile,:projectile_visual=>:ground,:impact_visual=>:ground,:persistent_visual=>:none,:timing=>:projectile_impact,:sfx_profile=>:organic_v0561},
    :blaze_kick=>{:move_key=>:blaze_kick,:motion=>:lunge_return,:pose=>:attack,:visual_kind=>:contact_hit,:projectile_visual=>:fire,:impact_visual=>:fire,:persistent_visual=>:none,:timing=>:contact_hit_hold,:sfx_profile=>:organic_v0561},
    :barrage=>{:move_key=>:barrage,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:projectile,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:projectile_impact,:sfx_profile=>:organic_v0561},
    :work_up=>{:move_key=>:work_up,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :twineedle=>{:move_key=>:twineedle,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:projectile,:projectile_visual=>:bug,:impact_visual=>:bug,:persistent_visual=>:none,:timing=>:projectile_impact,:sfx_profile=>:organic_v0561},
    :spacial_rend=>{:move_key=>:spacial_rend,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:beam,:projectile_visual=>:dragon,:impact_visual=>:dragon,:persistent_visual=>:none,:timing=>:beam_impact,:sfx_profile=>:organic_v0561},
    :sharpen=>{:move_key=>:sharpen,:motion=>:stationary_cast,:pose=>:charge,:visual_kind=>:self_fx,:projectile_visual=>:normal,:impact_visual=>:normal,:persistent_visual=>:none,:timing=>:cast_resolve,:sfx_profile=>:organic_v0561},
    :searing_shot=>{:move_key=>:searing_shot,:motion=>:stationary_cast,:pose=>:shoot,:visual_kind=>:area_hit,:projectile_visual=>:fire,:impact_visual=>:fire,:persistent_visual=>:none,:timing=>:area_same_frame,:sfx_profile=>:organic_v0561},
  }
  MOVE_COVERAGE_VIII_VISUAL_V057 = {}
  MOVE_COVERAGE_VIII_AUDIO_V057 = {}
  MOVE_COVERAGE_VIII_MOVE_V057.each do |k,d|
    p=MOVE_PRESENTATION_V057[k]||{}
    MOVE_COVERAGE_VIII_VISUAL_V057[k]={:visual_kind=>p[:visual_kind]||d[:visual_kind],:style=>p[:projectile_visual]||d[:visual_style],:hide_logical_projectile=>false,:timing=>p[:timing],:persistent_visual=>p[:persistent_visual]}
    MOVE_COVERAGE_VIII_AUDIO_V057[k]={:type=>d[:type],:category=>d[:category],:visual_kind=>d[:visual_kind],:audio_style=>d[:visual_style],:organic_palette=>:v0561,:special=>true}
  end
end
